### ISSUE TITLE
No tiene Autenticacion Proxy

### ISSUE THREAD

**Issue by darvinrivera** [tonikelope/megabasterd#1]
El programa esta genial pero necesito que tenga autenticacion proxy para poder descargar o subir archivos.

**Comment by tonikelope** [comment]
¡Gracias! Lo meto en cuanto pueda.

Salu2 ;)

**Comment by tonikelope** [comment]
Añadido. Lo he probado en un proxy sin autenticar. ¿Puedes probarlo tú en uno que requiere autenticación?

https://mega.nz/#F!oEtgBYaR!EMdqrcZsNAZl79oM5fvwfg

Salu2 ;)

**Comment by darvinrivera** [comment]
Funciona perfecto con proxy y autenticación. El unico detalle: Encripta la contraseña para que no se va en texto plano.
Mil gracias.

**Comment by tonikelope** [comment]
OK!

Cierro.
