### ISSUE TITLE
MEGA/MC API FATAL ERROR -15

### ISSUE THREAD

**Issue by NeryCast** [tonikelope/megabasterd#10]
Cuando cargo un DLC quiero descargar y me sale esto: MEGA/MC API FATAL ERROR -15, saludos, Windows 7 64 Bits

**Comment by BakasuraRCE** [comment]
I am getting the same error on Arch Linux, using v2.08

**Comment by NeryCast** [comment]
@BakasuraRCE 2.08 too, and the 2.06 Not start the download.

**Comment by tonikelope** [comment]
Fixed. (Remember for "large files" you need a premium account for download).
