### ISSUE TITLE
Error 1 2

### ISSUE THREAD

**Issue by 83rn15** [tonikelope/megabasterd#100]
Hello Team,

KIndly support me with the following issue im downloading some files but after around half percent done the program is saying Error 1 and 2 6 11 and other numbers blinking and it wont continue the download im using Megabasterd 6.31

**Comment by waseem2341** [comment]
even i have same issue and saying errors 1 2 and 3 and my download stops and not continuing after the half percent please help us

**Comment by DFNCTSC** [comment]
@83rn15 @waseem2341 Those errors just mean there was a problem with one of the proxies, nothing else. You can continue to download the file perfectly fine. If the download speed goes to 0, that just means wait -- it doesn't mean it's broken.

This issue should be closed.
