### ISSUE TITLE
Each New Version Creates Separate Config Folder

### ISSUE THREAD

**Issue by DFNCTSC** [tonikelope/megabasterd#101]
With every update MegaBasterd creates a new folder (i.e. `\.megabasterd6.31\`) in the current users directory in `C:\Users\{usernamehere}\`

Should remove the numerals and just use `\.megabasterd\` that way program settings and current downloads/uploads will carry over as well.

**Comment by tonikelope** [comment]
This is intentionally the case, since the structure of the `megabasterd.db` file can change between different versions.

Regards.
