### ISSUE TITLE
breaking the interface

### ISSUE THREAD

**Issue by xyz777** [tonikelope/megabasterd#102]
changing the font completely breaks the interface and i dont even know how to restore the default one 
[https://imgur.com/a/m3wnJOX](url)

**Comment by tonikelope** [comment]
I can't reproduce that error. What operating system and java version do you use?

One way to fix it would be to delete the MegaBasterd .megabasterdxxx configuration folder but you would lose your configuration and the list of pending transfers.

Regards.
