### ISSUE TITLE
Subdirectories are all renamed 'MALFORMED_ATTRIBUTES'

### ISSUE THREAD

**Issue by GAPPSRefusenik** [tonikelope/megabasterd#104]
First off let me say I love the program and thanks a lot for maintaining this! Your tool has unique features that are a must in my opinion, especially that you can increase the upload slots to more than 6, and the best of them all - support for multiple accounts.

This seems to be more of a cosmetic issue, but I thought I should be raising it anyway. My upload queue got stuck last night (waiting for upload...), perhaps there is a correlation. So here goes: When uploading a folder with subdirectories, each of them is renamed 'MALFORMED_ATTRIBUTES'. It's not very time-consuming to rename them manually afterward because the folder hierarchy seems to stay in place (the former alphabetical order). Still, I would appreciate it if it were possible to simply mirror entire folder structures, much like it is with the MEGAsync client.

Just for the record, I'm on Windows 7 x64 (not for long now, planning to switch to Linux Mint when updates are getting canceled in January).

**Comment by tonikelope** [comment]
I think it's a problem that only happens with Windows, but I don't know exactly why. 

Can you try running MegaBasterd from CMD.exe like this?

`java -Dfile.encoding=UTF-8 -jar MegaBasterd_6.29.jar`

**Comment by tonikelope** [comment]
Hello. I don't think in a RaspberryPI MegaBasterd works fluently but you can try. About the error you make, sometimes MEGA fails and that's why the chunk that was being uploaded fails and shows the counter in red but usually fixes itself and the upload ends finally. It's not something related to Windows.

**Comment by GAPPSRefusenik** [comment]
Thanks for the information! My guess was that it's related to MEGA itself. You are right, most of the time the upload completes eventually, even though it might take significantly longer due to the hiccups. Perhaps I'm uploading too much and MEGA tries to throttle me?

By the way, I discovered something funny; I checked if MEGAsync had the same hiccups, and noticed that when you select a folder with subdirectories that you have uploaded with MegaBasterd, the folders named 'MALFORMED_ATTRIBUTES' actually show up with the (somewhat) correct names. The problem seems to be related to the source path having several subdirectories, like this:

\source\sub1\sub2\files

In MEGAsync, there are displayed in this format:

\source\sub1sub2\files

Strange that they are not displayed like this in the browser though.

**Comment by tonikelope** [comment]
I don't think MEGA limits raises, but they're the only ones who really know how their service works internally.

I don't use Windows, so I can't do tests in depth, but those kind of problems are usually a thing of the Windows JVM...

Regards.

**Comment by GAPPSRefusenik** [comment]
Please don't start using Windows on my account. :grin: I hate myself for not having switched to Linux years ago. Looking forward to it and will certainly test MegaBasterd on Linux further.

Uploads have all gone smooth over the last 24 hours on Windows 10. MEGAsync is significantly slower. I have no idea how you manage to be faster than the official upload tool, but I'm loving it!
