### ISSUE TITLE
Downloads Stop / Slots

### ISSUE THREAD

**Issue by Xarmy** [tonikelope/megabasterd#105]
Hey Tonikelope! I've been using MegaBasterd for 3 days and I have had two issues.

Right now Im downloading something in MegaBasterd and I can't because the downloads simply stop. They do nothing. The downloads and the download speed are --------

Also, the slots are set to 6, but everytime I start a download, it goes to 20 slots.

Those were my two issues, hope you fix this soon!

Btw, thank you, because before this issues began, I could download a 13 Gb game :)

**Comment by tonikelope** [comment]
That behavior is normal. When the MEGA download limit is reached if SmartProxy is enabled, the number of slots is automatically increased to a maximum (20) and the download proxies are activated. The problem with proxies is that their speed is variable and sometimes they fail giving timeout (which gives the sensation that the download is frozen).

Regards.
