### ISSUE TITLE
This Process cannot access the file because it is being used by another program

### ISSUE THREAD

**Issue by Deimos206** [tonikelope/megabasterd#106]
Hello,

I seem to have stumbled upon an issue when trying to download my movie file. I made sure no other down-loaders were open to interfere with the download process on megabasterd, but to no avail. I'm not sure whats causing this issue, if there's a setting or process that I need to close, would you be so kind to assist me with this matter.

Thank You, 

Deimos
![GitHub issue pic](https://user-images.githubusercontent.com/54787667/64088465-920c6480-cd0f-11e9-9341-45fd23259ece.PNG)

**Comment by tonikelope** [comment]
Is it still happening to you?

**Comment by fuckchina6489** [comment]
I also have this problem. Fix it @tonikelope
