### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by NikoofDeath** [tonikelope/megabasterd#108]
I had used the program with no issue beforehand, but now whenever I try to use it (whether it is the versions I had previously downloaded, the newest versions, or versions in between) after the kim pic, the main window opens for a split second (without any GUI), then closes with no error.
Running the jar with verbose output the last message I get is
`[Loaded sun.security.validator.EndEntityChecker from C:\Program Files\Java\jre1.8.0_221\lib\rt.jar]`
Could this be a java issue? A Windows update issue?

**Comment by tonikelope** [comment]
> 

Could this be a java issue? A Windows update issue?
--

It seems to be.
