### ISSUE TITLE
Drag & Drop + Uploading multiple folders

### ISSUE THREAD

**Issue by alilife** [tonikelope/megabasterd#109]
Hi.
Thanks for your awsome project.
Can you please add an option that we could upload files by drag & dropping them into specific area of megabasterd?
and also it would be awsome to be able to add multiple folders for upload and each folder would be uploaded to a seprate folder on mega... I hope you know what I mean.

**Comment by tonikelope** [comment]
https://github.com/tonikelope/megabasterd/releases/tag/v6.34

Drag and drop in the main window area.

Regards.
