### ISSUE TITLE
Sometimes, MegaBasterd recognizes the link, but doesn't begin to download

### ISSUE THREAD

**Issue by eamontoyaa** [tonikelope/megabasterd#11]
Hi.

Sometimes, when I try to download a file with MegaBasterd, it recognizes the link, but doesn't begin to download. What can be happening?

My OS is Ubuntu 16.04.

Thanks.

**Comment by tonikelope** [comment]
Have you tried using a MEGA PRO account for download? Mega limits free
account bandwith.

Regards.
