### ISSUE TITLE
Potential Enhancement(s)

### ISSUE THREAD

**Issue by xghostxx** [tonikelope/megabasterd#111]
Firstly, thank you for all the work you have done on this program. It works wonderfully. 

I have written some suggestions below for things that could be useful to implement:

1) A "resume all paused" button. the pause all button is very useful but after this the user has to manually resume each one. if there are a few files this is not a big deal, but if there are multiple, it can be a bit more troublesome.

2) When the program is searching for a proxy, it often shows "------" where it would normally show the current download speed. I think it could be useful here to write "Searching for Proxy" or something similar instead of "-----". This lets the user know that the program is in fact still running and that there is nothing to worry about. Similarly, if no downloads were running, this could state "Not Active" or something similar. If all downloads are paused, then "All Downloads Paused", which can prevent the issue of pausing but then forgetting to resume the downloads. Similarly if all downloads are complete it could state "Downloads Complete" or "None in Queue", depending on which statement is true.

Thanks!

**Comment by tonikelope** [comment]
Point 1 is implemented in https://github.com/tonikelope/megabasterd/releases/tag/v6.36

About point 2, when "------" appears in the speed can be due to various factors, not just the proxies. I'll figure out how to give more information about what's going on when I have a while.

Regards.
