### ISSUE TITLE
3 Problems 

### ISSUE THREAD

**Issue by DJboutit** [tonikelope/megabasterd#114]
Still has 3 problems 

1 uses way to much ram my computer has 12gb ram and the program uses like 4gb to 4.5gb ram when downloading files

2 Still can not download files inside of folders

3 When a file get to 100% download it takes way to long to finalize the file 

Please fix these 3 things thx

**Comment by Pein1911** [comment]
I got download show "error 1", "error 2","error ..." red text on right side, Dl speed just go to 0 or very slow, its Smart Proxy or Slot problem, i tried use VPN anw, but not change
