### ISSUE TITLE
Settings Blank When screen is Flipped Portrait

### ISSUE THREAD

**Issue by Drunkender** [tonikelope/megabasterd#116]
The settings screen of MB is blank when the screen is flipped portrait 1024*1280 on windows 10.

Tested on MB 6.43.jar and 6.31.jar

Haven't testing the exe's.

**Comment by Drunkender** [comment]
Still a problem with MB_6.48.jar

**Comment by Drunkender** [comment]
Tested again with MB_6.55 jar AND exe this time still not working.

**Comment by tonikelope** [comment]
I have no idea what you might be going through. I've tried Windows 10 to move the screen and I can't reproduce the error you're making. If you can record a video and put here the details of your equipment, we could advance something...

Regards.

**Comment by Drunkender** [comment]
Windows 10 Home Build 1903
Intel i3-6500
Amd Rx 480 8GB
I have it connected to and old Multisync 1990SXI 1280 x 1024 Monitor Flipped Portrait

[Image](https://imgur.com/a/xIgWslx)

Note when not flipped Portrait but Regular landscape this is not an issue.

If you need more information or details please ask.
