### ISSUE TITLE
Slow download speeds

### ISSUE THREAD

**Issue by ssgfanboy** [tonikelope/megabasterd#117]
I am on the latest 6.43 and I am only downloading at around 50 KB/s despite having over 150 Mbps on a slow day (normally hovers around 300). Sometimes the download freezes for several minutes then picks up again at the 50 KB/s. I've tried everything from limiting parallel downloads to 1 and increasing slots but nothing works.

**Comment by tonikelope** [comment]
It's probably a proxy problem and that's something I can't solve, I'm sorry. Normally, closing and reopening the application will catch new faster proxies. 

Regards.
