### ISSUE TITLE
Update the software without loosing the queue | Actualizar el programa sin perder la cola

### ISSUE THREAD

**Issue by LuisAlfredo92** [tonikelope/megabasterd#118]
I want to update the software, but if I do that, then I lose all my download queue (That are almost 300, so if I do that I cant recover them easily)
How can I update without loosing the queue?

Quiero actualizar el programa, pero si lo hago pierdo toda mi cola de descargas (Que son casi 300, por lo que no podría recuperarlas fácilmente)
Cómo puedo actualizar sin perder la cola de descargas?

**Comment by tonikelope** [comment]
Hola. Depende de si la versión que tienes es muy antigua o no. Cierra tu versión de MegaBasterd. Descarga la nueva, ejecútalo y ciérralo. En tu carpeta de usuario verás una carpeta llama ".megabasterdXXX" (XXX es tu versión) y dentro esta la base de datos interna de MegaBasterd. Copia el archivo y pégalo en la carpeta ".megabasterd6.43"

Si tienes suerte y vienes de una versión no muy antigua debería funcionar todo sin problemas al abrirlo.

Salu2 ;)

**Comment by LuisAlfredo92** [comment]
Funcionó perfecto!
Muchas gracias
