### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by UnrealLoop** [tonikelope/megabasterd#119]
This occurs sometimes and random too but whenever a file is being downloaded, the percentage displayed on megabasterd for the file download would reduce i.e. it would show 80% or 90% completed,then would change back to 60% or 70% and proceed to download till 100%. Though the integrity check done by megabasterd on the file shows no problem.

If I'm downloading from the mega site through browser and I see the same occuring with it i.e. the percentage reducing and then increasing, the download would turn red and show as corrupted.

**Comment by tonikelope** [comment]
That can happen when downloading several simultaneous chunks fails (because of some connection or MEGA problem). The total progress of the download because you start downloading the chunks again. Not much can be done, sorry.

Regards.
