### ISSUE TITLE
not decoding...etc

### ISSUE THREAD

**Issue by rickzzzz** [tonikelope/megabasterd#12]
Regards,

i like this project but believe there are some stuff to fix and improve.
running now from winXP up to date

 when i copied link to click board instead of adding new link it cleans the list, it should add more links, i guess

i thought it was going to decode Megadownloader links

real samples:
mega://enc2?V1Uyf7CKpg5MooWSuq7HuSSDJW9_5jUsFzYZdzCxBVnZzXO6Su8hNr5dB83DXlA_nO5wjt2U0M8b5YY9ftYYWcM9mgAEcsl1zsgt2-DMq7U
mega://enc2?pz3V31Oz5V9NJko-8UKymvb0uZFkEFSrAll_Y3HzWjx2w6CK3SGZL5YHY2I7gs8lHY9n2c0m71-mxQm8NcM-o6EWS7Abm7TCbACyOSmhZ3c
mega://enc2?fP8kbINzEwH04Ya4gUQBXr7IelGjHV-qvnf81XvWtJhhRRUpXA_wyFAw7ejFiMHZYAiqQSgY00Ks6kIYjkbaRjZD8SfQkhHBuySDQ9Y045A
mega://enc2?pNrSFludEeQ4BSmyYznfodV3zCrKN-PrbuwadH6cqKzmkKGx3sDorXTh7ZAntNAkcd0KzpHCd8nbXjKTqXqR8OhqkhqDt68TsZHP9mrFLdk
mega://enc2?emFXTwuZdwIZGYNzFsrTCnSAssJYil-_VZ40W7DqJvUxAm-rV7mfN7Fa9Q-kgdiskqbjoPuCskN5cajWHaiob6DSL-HobHHgJyg-Jqq9sjk
mega://enc2?QNU2bjTXNMs0y5_GSwLcbVyZXTe2IrhuSmf0CEEhA93oTBpyKmzhedPmTCynDyDNLf63KWHzOS3Oz8Is35P4ROMMoIthtCaaT7Hvy_UfGrY
mega://enc2?IoPul5OwVxYXtawasJ_1ZNoYyAzuJFzLStN4HNo8NaG03nwbbvNVWDqh9Q5rwtnaCfFyvKXUQXbeORvmGFO5TQ
mega://enc2?IopShFfvVY9KsfE1vbNatoBYf5m5xI7jM5snwr2_OJXlESMuVur8nq99peV_BavmLTASDAGcTqzu20Ck3RwmTQ

it copied the links to list but never adds them to download, don't give any warning or error, just do nothing
version i got it's suppose to be the latest one (2.11)

My Best Regards

**Comment by tonikelope** [comment]
mega://enc2?V1Uyf7CKpg5MooWSuq7HuSSDJW9_5jUsFzYZdzCxBVnZzXO6Su8hNr5dB83DXlA_nO5wjt2U0M8b5YY9ftYYWcM9mgAEcsl1zsgt2-DMq7U
mega://enc2?pz3V31Oz5V9NJko-8UKymvb0uZFkEFSrAll_Y3HzWjx2w6CK3SGZL5YHY2I7gs8lHY9n2c0m71-mxQm8NcM-o6EWS7Abm7TCbACyOSmhZ3c
mega://enc2?fP8kbINzEwH04Ya4gUQBXr7IelGjHV-qvnf81XvWtJhhRRUpXA_wyFAw7ejFiMHZYAiqQSgY00Ks6kIYjkbaRjZD8SfQkhHBuySDQ9Y045A
This links are OFFLINE (error -9)
mega://enc2?pNrSFludEeQ4BSmyYznfodV3zCrKN-PrbuwadH6cqKzmkKGx3sDorXTh7ZAntNAkcd0KzpHCd8nbXjKTqXqR8OhqkhqDt68TsZHP9mrFLdk
mega://enc2?emFXTwuZdwIZGYNzFsrTCnSAssJYil-_VZ40W7DqJvUxAm-rV7mfN7Fa9Q-kgdiskqbjoPuCskN5cajWHaiob6DSL-HobHHgJyg-Jqq9sjk
mega://enc2?QNU2bjTXNMs0y5_GSwLcbVyZXTe2IrhuSmf0CEEhA93oTBpyKmzhedPmTCynDyDNLf63KWHzOS3Oz8Is35P4ROMMoIthtCaaT7Hvy_UfGrY

This links are ONLINE and downloading (2.11):
mega://enc2?IoPul5OwVxYXtawasJ_1ZNoYyAzuJFzLStN4HNo8NaG03nwbbvNVWDqh9Q5rwtnaCfFyvKXUQXbeORvmGFO5TQ
mega://enc2?IopShFfvVY9KsfE1vbNatoBYf5m5xI7jM5snwr2_OJXlESMuVur8nq99peV_BavmLTASDAGcTqzu20Ck3RwmTQ
 Default behaviour is to clean the link box when you copy some link. If you want to add a link list, select and copy them all.

About Windows XP, i will test asap.

Regards.

**Comment by rickzzzz** [comment]
i test them with megadownloader 1.7, just checked them, all are online
if you add them to medadownloader it verifies after adding links, i would like to get original source, obviously i lost them, i would like to use other download manager for this task, megadownloader won't work with legit mega account, that's why i'm trying your app., you know actually mega has more limits
jdownloader decode most of those link but not all

**Comment by rickzzzz** [comment]
i found this : https://github.com/denysvitali/megadecrypter

maybe can help you for basterd, don't know anything about compiling or programing stuff

Regards

**Comment by tonikelope** [comment]
This is a Java problem. The solution (tested in Windows XP with Java 1.8) is here[https://stackoverflow.com/questions/6481627/java-security-illegal-key-size-or-default-parameters](url)

Regards.
