### ISSUE TITLE
Upload Error MEGA API -9

### ISSUE THREAD

**Issue by luisr1vas** [tonikelope/megabasterd#123]
Recien voy actualizando de la version MegaBasterdJRE_6.59 a MegaBasterdJRE_6.60 y en la subida marca error, adjunto imagen:

Con la version anterior 6.59 no presenta este bug.

Windows 10 x64.

![image](https://user-images.githubusercontent.com/38728192/66424619-92191780-e9d3-11e9-8c7e-2b885555bfa8.png)

**Comment by tonikelope** [comment]
Try https://github.com/tonikelope/megabasterd/releases/latest

Regards.
