### ISSUE TITLE
Stuck Download

### ISSUE THREAD

**Issue by Hanzemon** [tonikelope/megabasterd#125]
![image](https://user-images.githubusercontent.com/32701428/66673442-968d3c80-ec2e-11e9-9584-8d1a29de2c3d.png)

It's like this since yesterday, It only updates "Tot. Error: 1" "2" "3" and so on... until it goes back to 1.

**Comment by tonikelope** [comment]
That's because the proxies will be saturated. Normally, closing the program and continuing the download takes new proxies and fixes itself. 

Regards.

**Comment by Hanzemon** [comment]
Yes, I didn't want to close it at first because I thought that I would lose the progress. Before reading your answer I gave up and closed it, later that day I opened it again and the download finished flawlessly. 

However today I'm trying to download anoother file and "closing->reopening" doesn't seem to work in this case.
