### ISSUE TITLE
Proxy list questions

### ISSUE THREAD

**Issue by jacobslusser** [tonikelope/megabasterd#126]
Just came across this project and since it is a bit lite on the documentation, I had a question about the proxy list. 

It looks to me that the way megabasterd circumvents the mega daily IP restriction for bandwidth is to use a proxy. 

Where is this list of proxies sources from? How frequently is the list updated? With everyone using the same list, does having more people using megabasterd result in more of those proxies hitting their daily limits?

Thanks for the project.

**Comment by tonikelope** [comment]
> It looks to me that the way megabasterd circumvents the mega daily IP restriction for bandwidth is to use a proxy.

Yes.

> Where is this list of proxies sources from?

Several sources of public proxies are used which are conveniently filtered and ordered .

> How frequently is the list updated?

60 minutes

> With everyone using the same list, does having more people using megabasterd result in more of those proxies hitting their daily limits?

I'm afraid it is. I will try to add more public proxy sources, and in some future update I will add the option to use a personal list.

Regards.
