### ISSUE TITLE
My download is stuck and it's not automatically resumed

### ISSUE THREAD

**Issue by mega385** [tonikelope/megabasterd#127]
My download is not automatically resumed since I update the app into 6.64 .. To resume download I have to restart this app.. Please fix this .. Coz my lot's of data is spoiled and because of this I didn't work on other things.please help

**Comment by mega385** [comment]
Now I update the app into 6.65 but still my problem is not solved

**Comment by Jroddmqz** [comment]
I am using version 6.69 and the downloads get stuck every so often until I restart the application.
