### ISSUE TITLE
Download stuck

### ISSUE THREAD

**Issue by mega385** [tonikelope/megabasterd#129]
![IMG20191013184928](https://user-images.githubusercontent.com/56484042/66716472-b0c04980-edeb-11e9-95fd-56a49864d1ae.jpg)
This is what happens on every download...this is happens on every 5 minutes from yesterday almost I restart the app 50 time's over and still got the same problem

**Comment by mega385** [comment]
Still happening with 6.69

**Comment by Hunam6** [comment]
Still happening with 6.71 (at 98% :/)

![image](https://user-images.githubusercontent.com/38606542/67163076-fbe9d780-f36a-11e9-80c8-37ce36e61f32.png)

**Comment by pedrix2019** [comment]
![error mega](https://user-images.githubusercontent.com/56852155/67251962-9a8f3a80-f436-11e9-91cd-db420a8a588c.png)

**Comment by pedrix2019** [comment]
de ahi no pasa

**Comment by pedrix2019** [comment]
version 6.72

**Comment by DJboutit** [comment]
I have the same problem with 6.72 I downloaded 3 files 2 finished 1 stuff at 99% for 15hrs now.  When you added Java jre the program is 65% worse

**Comment by tonikelope** [comment]
Downloads using SmartProxy can be "frozen" and continue as soon as new proxies become available. There is nothing that can be done to improve this, except to put more proxies or fewer people using it at the same time, I'm sorry.

**Comment by Stoltverd** [comment]
This still happens and I'm NOT using any proxy

**Comment by DjangoZorro** [comment]
This is indeed still happening and I'm also not using a proxy...

**Comment by x-kazumi** [comment]
Same here. Still happening and I'm not using any proxy. After it stopped the download i tried restarting it and nopw it doesnt download a single file?

**Comment by CrazyCSIW6** [comment]
7.40, still an issue.

**Comment by iamayushkr** [comment]
7.43 is still an issue.

**Comment by 5u8han** [comment]
Is this fixed yet? V7.46 still stuck at 0%

**Comment by anburocky3** [comment]
I can experience this in v7.49 too. 

Needs some way to cover this scenario. I am not using any smartproxy by the way.

**Comment by Jaime-06** [comment]
yep, still happening at v7.49

**Comment by techdiot** [comment]
> ![IMG20191013184928](https://user-images.githubusercontent.com/56484042/66716472-b0c04980-edeb-11e9-95fd-56a49864d1ae.jpg) This is what happens on every download...this is happens on every 5 minutes from yesterday almost I restart the app 50 time's over and still got the same problem

try deleting the mega basterd and install once again, the download will start automatically. it worked for me.

**Comment by Hunam6** [comment]
> I don't think anyone needs to use this software anymore, right? If I'm not mistaken, Mega doesn't limit download speed or size anymore.

It's still needed, Mega still limits your monthly transfer, https://mega.io/pricing.

**Comment by BlackSheep47** [comment]
Guy's simply use Cloudflare WARP and use megabasterd
