### ISSUE TITLE
No descarga archivos.

### ISSUE THREAD

**Issue by NeryCast** [tonikelope/megabasterd#13]
![sin titulo](https://user-images.githubusercontent.com/19565251/30239739-b9a9728a-9517-11e7-8e53-10cd9b772635.png)

No descarga el archivo :(

**Comment by tonikelope** [comment]
https://github.com/tonikelope/megabasterd/issues/11

**Comment by TheMortimer30** [comment]
Hola buenos dias, comienzo por agradecer por la aplicación, iba todo bien hasta que deje una descarga de 12.,36gb durante la noche, y ahora al revisar, solo hay 12,02gb descargados y los archivos estan al 95%+ como si estuviesen descargando pero en realidad no hacen nada,tengo la ultima version del jar 6.78
![Error](https://user-images.githubusercontent.com/58473369/70053913-3f17a700-15b5-11ea-8780-91396bfbce74.png)
Como ven, ahi esta trabado,lleva mas de 5 horas, asumo, ya que lo deje durante la noche a partir de las 1-2a.m. aprox.

**Comment by tonikelope** [comment]
Hola. Sí, voy a revisar este tema de la finalización de descargas a fondo.

Disculpad que tarde en responder algo más de lo normal pero estoy más liado.

Salu2 ;)

**Comment by krow5370** [comment]
Ya hay solucion?
