### ISSUE TITLE
Enlace de mega erróneo

### ISSUE THREAD

**Issue by Marin56** [tonikelope/megabasterd#130]
Las ultimas actualizaciones me han dado ese error, a pesar que los enlaces estan corectos. ¿A que se debe? Ya que ultimamente me estaba funcionando bien, pero desde dos actualizaciones atras me da este erro enlace de mega erróneo.

**Comment by tonikelope** [comment]
Hola. Necesito el enlace que te falla para probarlo.

**Comment by Marin56** [comment]
https://mega.nz/#F!lKZCCQzC!ultTRiHTMjjTSTEBn4_PLA?IChmwA5K  Ese es uno pero no importa si pongo otro siempre me dice que el enlace es erróneo. El enlace a mi parecer esta bien ya que lo tengo en mi cuenta de mega.

**Comment by tonikelope** [comment]
Hola. Tienes que poner el enlace a la carpeta y seleccionar el archivo que quieres descargar desde MegaBasterd. 

https://mega.nz/#F!lKZCCQzC!ultTRiHTMjjTSTEBn4_PLA

Salu2 ;)
