### ISSUE TITLE
takes too long to finalize uploads (CBC-MAC)

### ISSUE THREAD

**Issue by alilife** [tonikelope/megabasterd#131]
Hi.
Why does it take too long to finalize uploads? sometimes it takes more than uploading itself

**Comment by tonikelope** [comment]
The algorithm used by MEGA to calculate the CBC-MAC code is very slow and sometimes there is the "paradox" that it takes less time to upload the file than to generate the code. The only way to speed up the CBC-MAC generation is to use a faster CPU and/or a faster hard disk. It's a limitation of MEGA, I'm sorry.

Regards.
