### ISSUE TITLE
Me he descargado la última versión 6.73 y cuando la abro me aparece la 6.38

### ISSUE THREAD

**Issue by alfon6666** [tonikelope/megabasterd#133]
Me he descargado la última versión 6.73 y cuando la abro me aparece la 6.38.

Saludos.

**Comment by luisAzcuaga** [comment]
Esto es porque el proceso se sigue ejecutando, busca junto al reloj de windows, click derecho -> cerrar. Después, intenta volver a iniciar el 6.73 :)

**Comment by luisAzcuaga** [comment]
> Me he descargado la última versión 6.73 y cuando la abro me aparece la 6.38.
> 
> Saludos.

Esto es porque el proceso se sigue ejecutando, busca junto al reloj de windows, click derecho -> cerrar. Después, intenta volver a iniciar el 6.73 :)

**Comment by luisAzcuaga** [comment]
@alfon6666 Esto es porque el proceso se sigue ejecutando, busca junto al reloj de windows, click derecho -> cerrar. Después, intenta volver a iniciar el 6.73 :)
