### ISSUE TITLE
6.74 errores al descargar esta carpeta

### ISSUE THREAD

**Issue by biejis** [tonikelope/megabasterd#136]
https://mega.nz/?fbclid=IwAR0AGJxcFA1HYTM4chEQbVUn9ZEAYuToajE6M_zTNdNCMh9FqawyfPVA-wE#F!bf4ljCZQ!plzAE9zfW8GSmOYTSFeM8A
![image](https://user-images.githubusercontent.com/29903063/67646253-e9901080-f90b-11e9-8f81-19548ecadb5a.png)

**Comment by tonikelope** [comment]
The correct folder link is:

https://mega.nz/#F!bf4ljCZQ!plzAE9zfW8GSmOYTSFeM8A

Salu2 ;)
