### ISSUE TITLE
Program doesn't run

### ISSUE THREAD

**Issue by MProductionYT** [tonikelope/megabasterd#138]
When I try to open the program it only appeared the splash screen, and then it dissapears, no interface, no program, nothing. I'm using the latest version and both exe and jar didn't work.
I'm using Windows 10 1903 update and latest Java version.

**Comment by thegreatestminer** [comment]
Try opening a command prompt and try running `java -jar MegaBasterd_6.75.jar`.

If it gives any console output there, paste it here.

**Comment by vehosah** [comment]
> Try opening a command prompt and try running `java -jar MegaBasterd_6.75.jar`.
> 
> If it gives any console output there, paste it here.

i tried that,it said error accessing jar file

**Comment by MSaqib123** [comment]
its not working i also download  java kit
