### ISSUE TITLE
Downloads stuck at 98/99% when transfer quota exceeded

### ISSUE THREAD

**Issue by RekovPDX** [tonikelope/megabasterd#139]
I've noticed this problem cropping up repeatedly when running up against mega.nz's transfer quota. Some of the downloads will get to 98% or 99% and then stall out. It always happens when the slots field is greyed out and locked at 1.

![stall](https://user-images.githubusercontent.com/26471198/68040567-cd81cb80-fc8b-11e9-9387-2dc9bd90e29b.png)

You can manually 'resume' these downloads by cancelling them within megabasterd, and then hitting restart. They'll lose progress, for example I cancelled a download at 98%. It restarted at 81%, and managed to finish.

Every time I've done this though, I've ended up with a corrupt file. Rars result in CRC errors when extracting. So really, when this bug happens you have to delete the file and start the whole download from scratch.

**Comment by wefalltomorrow** [comment]
Same issue here sadly.

https://i.imgur.com/BVXc0P8.png

**Comment by tonikelope** [comment]
> I've noticed this problem cropping up repeatedly when running up against mega.nz's transfer quota. Some of the downloads will get to 98% or 99% and then stall out. It always happens when the slots field is greyed out and locked at 1.
> 
> ![stall](https://user-images.githubusercontent.com/26471198/68040567-cd81cb80-fc8b-11e9-9387-2dc9bd90e29b.png)
> 
> You can manually 'resume' these downloads by cancelling them within megabasterd, and then hitting restart. They'll lose progress, for example I cancelled a download at 98%. It restarted at 81%, and managed to finish.
> 
> Every time I've done this though, I've ended up with a corrupt file. Rars result in CRC errors when extracting. So really, when this bug happens you have to delete the file and start the whole download from scratch.

Please activate the option to check the integrity of the downloaded files to see if the next time you cancel and continue the download at the end passes the integrity test.

I have already explained many times that when using proxies to download, it is possible that the download seems "blocked" because the proxies are slow to respond or respond very slowly. This is more noticeable at the end of the download, when there are only a few chunks left to download "blocked" in slow proxies. In those cases, restarting the application usually helps because new proxies are assigned. 

Regards

**Comment by wefalltomorrow** [comment]
[**@tonikelope**](https://github.com/tonikelope) commented on [3 Nov 2019, 22:47 GMT+11](https://github.com/tonikelope/megabasterd/issues/139#issuecomment-549128761 "2019-11-03T11:47:58Z - Replied by Github Reply Comments"):
> I have already explained many times that when using proxies to download, it is possible that the download seems "blocked" because the proxies are slow to respond or respond very slowly. This is more noticeable at the end of the download, when there are only a few chunks left to download "blocked" in slow proxies. In those cases, restarting the application usually helps because new proxies are assigned.
> 
> Regards

Would it be possible to add a function to assign new proxies whilst in-app?

**Comment by tonikelope** [comment]
> [**@tonikelope**](https://github.com/tonikelope) commented on [3 Nov 2019, 22:47 GMT+11](https://github.com/tonikelope/megabasterd/issues/139#issuecomment-549128761):
> 
> > I have already explained many times that when using proxies to download, it is possible that the download seems "blocked" because the proxies are slow to respond or respond very slowly. This is more noticeable at the end of the download, when there are only a few chunks left to download "blocked" in slow proxies. In those cases, restarting the application usually helps because new proxies are assigned.
> > Regards
> 
> Would it be possible to add a function to assign new proxies whilst in-app?

I'll add it when I can.

**Comment by wefalltomorrow** [comment]
Thanks mate, appreciate it.

**Comment by RekovPDX** [comment]
Thank you for the clarification tonikelope. The verify integrity checkbox really helps in terms of making sure the files download okay.

> -Auto restart SmartProxy download if is more than 2 minutes without receiving any data.
So this is supposed to automatically restart the downloads if they get stuck? I've tested this a little using 6.78, and it seems to work a lot of the time, though I've still got a few stuck downloads. Unfortunately I haven't yet figured out exactly what conditions cause this.

Restarting the client + verify integrity mostly solves this issue though, so that's great!

**Comment by WildFearless** [comment]
So you need your own proxies for this? Thats kinda pointless..

**Comment by mridullpandey** [comment]
i hit pause all now how to resume the download

**Comment by techdiot** [comment]
Once try  going to advanced settings and reset mega basterd and also try without using the API key
