### ISSUE TITLE
Problemas con la subida

### ISSUE THREAD

**Issue by axo1** [tonikelope/megabasterd#14]
Hola, tengo problemas con la subida. Antes me subía a máxima velocidad, pero ahora llegado a un punto se bloquea y no sube más. Podrías arreglarlo? Gracias, un saludo
![sdes7op](https://user-images.githubusercontent.com/33151891/32100840-b65d4eb6-bb15-11e7-8681-ea6ea0ee8501.png)

**Comment by tonikelope** [comment]
Hola. ¿Puedes lanzar Megabasterd desde la consola con:

java -jar MegaBasterd******.jardín


y pegarme aquí lo que salga?

Gracias.

Un saludo.

**Comment by axo1** [comment]
Uso Windows 10, si me puedes explicar cómo hacerlo te lo envío

**Comment by tonikelope** [comment]
No te preocupes. Creo que tengo localizado el fallo y estoy corrigiendolo. Estará en un rato y subiré la nueva versión. 

Disculpa las molestias.

Un saludo.

**Comment by axo1** [comment]
Muchas gracias, currazo el tuyo y de molestias nada.
Saludos!
