### ISSUE TITLE
Update still shows v6.19

### ISSUE THREAD

**Issue by sefton22** [tonikelope/megabasterd#140]
having downloaded v6.74, it's still showing as v6.19 and is prompting that an update is available

**Comment by savefromgoogle** [comment]
The issue on your side is most likely that Java class libraries are being cached by your system.

Proceed as follows: Download the new app. Close the old app. Delete the old app executable. Restart the OS, or at least re-login your user account. Start the new executable. Then it should be updated.

**Comment by sefton22** [comment]
having downloaded v6.75 everything worked. just seen v6.85 has been released
