### ISSUE TITLE
Problema o Bug

### ISSUE THREAD

**Issue by Serdx** [tonikelope/megabasterd#144]
Hola, a veces cuando dejo descargando archivos, por alguna razon fallan, se queda el archivo temporal solo por donde iba la descarga, y tengo que volver a buscar el archivo, y ponerlo a descarga. Querria saber si es posible que haga algo para que las descargas nunca se paren y desaparezcan del programa. Es como si de repente la descarga tuviese un error y en vez de decirlo, esta misma se borra del programa pero queda el archivo temporal.

**Comment by Serdx** [comment]
Creo que una de las razones es por que le doy a limpiar todas las descargas terminadas, y borra tambien las que hayan tenido error

**Comment by tonikelope** [comment]
Acabo de cambiar el comportamiento del botón que limpia las descargas finalizadas para que no limpie las canceladas.
