### ISSUE TITLE
Downloads stop after a while

### ISSUE THREAD

**Issue by ChaI-LacK** [tonikelope/megabasterd#148]
I have been using Megabasterd for a year now, and i must say I am really grateful. Recently I have noticed that it stops downloading even though I have stable connection and the only way to get them done is by restarting the program. I am not exactly sure if the issue is from Mega servers, my connection (I tried it from different locations with different connections) or the program. Downloading something overnight became bothersome since it would just get stuck. I hope you'd consider this feedback to improve the program and please contact if you need more info.
Thank you tonikelope.

**Comment by tonikelope** [comment]
I've added an option that resets the downloads in case for any reason you don't receive data in 120 seconds. I hope this helps to finish the downloads.
