### ISSUE TITLE
BUG Duplicado carpeta chunks

### ISSUE THREAD

**Issue by F-J-V** [tonikelope/megabasterd#149]
Hola, gracias por el programa. Funciona muy bien.

El fallo ocurre cuando estoy descargando una carpeta con varias subcarpetas, cuando encontramos el mismo nombre de archivo en varias subcarpetas.

Ejemplo: En una subcarpeta el primer archivo se llama "1. Instrucciones para comenzar.mp4".

En la carpeta de chunks se forma una carpeta con el nombre ".mb_chunks_" a la que se le añade el nombre del archivo, por lo que queda ".mb_chunks_1. Instrucciones para comenzar.mp4".

Si antes de que termine la descarga de este archivo, comienza otro de otra subcarpeta con el mismo nombre, aunque la subcarpeta de descarga tenga otro nombre, la carpeta de chunks tendrá el mismo nombre, ".mb_chunks_1. Instrucciones para comenzar.mp4". Supongo que el programa intenta crearla y como ya existe empieza a descargar dentro de ella, por lo que se mezclan los chunks e invalida las dos descargas.

Para poder descargas estos archivos tengo que borrar la carpeta del chunk, el archivo temporal, y asegurarme que que no estén las dos descargas a la vez. anulando una de ellas y descargarla después.

No se si podrías formar el nombre de carpeta chunks añadiendo una parte irrepetible en vez de "mb_chunks", o pausar una descarga si la carpeta del chunk que intenta crear ya existe, o cualquier otra forma que impida que se descarguen dos archivos con el mismo nombre en la misma carpeta chunks.

Saludos.

**Comment by tonikelope** [comment]
Hola. Lo revisaré en cuanto tenga un huequecillo. ¡Gracias por avisarme!

Salu2 ;)

**Comment by tonikelope** [comment]
Ahora se concatena el file_key del archivo a 'mb_chunks_' El file_key suele ser aleatorio y no se repite (técnicamente es posible usar el mismo file_key para subir dos ficheros distintos pero no se hace que yo sepa en ningún gestor de subidas).

Salu2 ;)

**Comment by F-J-V** [comment]
Perfecto :)
Saludos.
