### ISSUE TITLE
Mejorar la lista de cuentas para subir contenido

### ISSUE THREAD

**Issue by Mitt9** [tonikelope/megabasterd#15]
Hola,

Tengo bastantes cuentas de MEGA, más de 50, pero sólo en 7 estoy subiendo contenido actualmente de forma simultanea. Cada cuenta la uso para subir un contenido en específico.

Todas las cuentas las registro con el mismo correo, pero con variaciones, es decir, tengo una cuenta de correo estoesunaprueba@gmail.com y también e.sto.es.un.a.pru.eba@gmail.com (Para Google las dos son la misma cuenta, pero para MEGA no... jeje) y así en todas las cuentas.

Cuando voy a añadir una cuenta al programa sólo me pide el correo y la contraseña, pero no me deja ponerle una etiqueta. Entonces, cuando voy a subir un contenido y tengo una lista de 7 cuentas todas iguales, no se cual de todas es la que quiero usar para subir el contenido y tengo que perder el tiempo en mirarlo de forma manual en un archivo .txt donde tengo apuntado todas las cuentas y el contenido que subo.

Entonces esto es un problema, porque yo vengo de usar MegaUploader donde sí te deja poner una etiqueta para que puedas identificarlo, y como no me funciona correctamente el programa pues me recomendaron este y funciona muy bien, pero tengo este problema que para mi es muy molesto.

Por favor, en la próxima actualización implementad esa opción. Sería tal que así:

estoesunaprueba@gmail.com | contraseñacualquiera | Para subir X contenido
est.oesun.aprue.ba@gmail.com | contraseñacualquiera | Para subir Y contenido
e.stoe.suna.prue.ba@gmail.com | contraseñacualquiera | Para subir Z contenido
e.stoesu.nap.rue.b.a@gmail.com | contraseñacualquiera | Para subir A contenido
esto.es.u.napr.ue.b.a@gmail.com | contraseñacualquiera | Para subir N contenido

Espero que se haya entendido lo que quiero que se implemente, cualquier duda preguntádmelo.

Saludos.

**Comment by tonikelope** [comment]
Hola. Prometido para la próxima actualización (que espero que sea en breve).

Salu2 ;)

**Comment by tonikelope** [comment]
Lo he implementado, pero por falta de tiempo no he añadido un campo nuevo a la tabla, sino que los correos ahora pueden llevar de forma opcional un alias al final usando '#' Ejemplo:

```
estoesunaprueba@gmail.com#Para subir X contenido | contraseñacualquiera
est.oesun.aprue.ba@gmail.com#Para subir Y contenido | contraseñacualquiera
e.stoe.suna.prue.ba@gmail.com#Para subir Z contenido | contraseñacualquiera
```
Espero que sea útil.

Salu2 ;)

**Comment by Mitt9** [comment]
De hecho, con eso basta. 

Muchas gracias. Ahora ya no me liaré. 😄
