### ISSUE TITLE
Archivos temporales archivo.rar.mctemp que no se descargan 

### ISSUE THREAD

**Issue by RVSWeb** [tonikelope/megabasterd#152]
Saludos maquina !
Gracias por crear este maravilloso programa.
Tengo varios archivos temporales en el directorio donde me estaba descargando los archivos que necesito.
Son del tipo :
archvios1.rar.mctemp 
archvios2.rar.mctemp 
etc.
Estos archivos no llegaron a descargarse junto con la colección de rar que agregue al programa y no sé como incluirlos de nuevo a la lista de descargas del programa megabasterd para que los descargue nuevamente y complete la colección de archivos que necesito para descomprimir todas las partes.

![Anotación 2019-12-07 142842](https://user-images.githubusercontent.com/8049648/70375477-7b713d00-18fe-11ea-82f0-baa10a832f01.gif)

**Comment by tonikelope** [comment]
Hola. Tendrías que volver a meter los enlaces de descarga de esos archivos
en MegaBasterd como si quisieras volver a descargarlos y MegaBasterd
continuará por donde iba (fíjate que también tiene que haber varias
carpetas que se llaman .mb_chunks_xxxxxxxxx que contienen los trocitos
descargados de cada archivo RAR).

Salu2 ;)

**Comment by RVSWeb** [comment]
Genial ! Gracias por dedicarme tu tiempo.
Una vez más , Gracias por crear este maravilloso programa!
