### ISSUE TITLE
Tratamiento de ¡Descarga CANCELADA!

### ISSUE THREAD

**Issue by F-J-V** [tonikelope/megabasterd#153]
Hola, buen programa.

A veces, cuando tenemos una descarga pesada y de muchos archivos, sucede que por algún error algunos archivos aparecen como ¡Descarga CANCELADA!, con dos botones, el de "cerrar" que elimina la descarga, y el de "reiniciar" que vuelve a poner el archivo en descarga.

Si le damos a reiniciar todo solucionado, el problema aparece si cerramos megabasterd y volvemos a abrir, o si le damos al botón de arriba a la derecha de "Cerrar las que finalizaron", pues estas acciones borran la ¡Descarga CANCELADA! de la lista, por lo que cuando termina la descarga total, nos encontramos que faltan estas descargas, y hay que volver a cargarlas para que se descarguen.

Creo que los archivos que están en ¡Descarga CANCELADA! solo deberían de desaparecer de la lista de descargas si pulsamos expresamente en el botón de "cerrar", puesto que a veces, tenemos muchas descargas finalizadas y si se nos pasa revisarlas todas y pulsamos el botón "Cerrar las que finalizaron" o cerramos el programa por cualquier motivo, perdemos estas descargas sin darnos cuenta.

Afortunadamente, cuando se anula una descarga de esta manera permanece el archivo temporal, por lo que cuanto termina una descarga, reviso si ha quedado algún archivo temporal, para saber cual tengo que volver a descargar.

Saludos.

**Comment by tonikelope** [comment]
¡Hola! Me parece lógico lo que comentas. Lo cambiaré en la próxima
actualización.

Salu2 ;)

**Comment by F-J-V** [comment]
Hola, ha quedado perfecto, ¡Gracias!

**Comment by derensd** [comment]
Hola esta muy bueno el programa que has creado,
tengo una duda ya que justamente hoy e decubiero tu programa 
y tengo problema en el cual yo e intentado descargar un archivo de 2,50 gb y el programa cuando
lo pongo a descargar no los descargar no muestra ningun mb de baja 
no se si llegara a ser un problema de mi computadora o algo pero no lo descargar.
queria ver si me podrias llegar a ayudar a poder utilizar el programa adecuadamente.
post: por si acaso no tengo ningun proxy activado y me e descargar el megaboster.jar
