### ISSUE TITLE
Uploading from Megabasterd results in subfolders being renamed to MALFORMED-ATTRIBUTES

### ISSUE THREAD

**Issue by AlecHex** [tonikelope/megabasterd#154]
I am aware someone had an issue like this before but couldn't really find a solution in that thread. When I maybe upload a discography of an artist, all the albums are renamed to MALFORMED-ATTRIBUTES and so I have to rename each folder again one by one, which with the UI of mega is literally time consuming. Is there any fix for that?

**Comment by tonikelope** [comment]
Please, put here your MegaBasterd version, Java version and OS.
