### ISSUE TITLE
Archivo .chunk y .chunk.mctemp

### ISSUE THREAD

**Issue by IribarrenWeb** [tonikelope/megabasterd#155]
Cuando termine una descargar, y abro la carpeta de destino, el programa habia creado un un archivo .rar.mctemp que es el archivo principal que deberia ser el .rar para descomprimir y listo, pero no pesaba los 1.83 GB que tendria que pesa, pero tambien descargo una carpeta que es la que pesa los 1.83GB y en su interior estan todas las partes del archivo en si, pero todas son archivos .rar.chunk y su num de parte. Es como si el programa luego de terminar la descarga no hubiera unido todas esas partes que descargo en el archivo .rar principal y los dejo en ese formato que no tengo ni idea de como unificar.

**Comment by tonikelope** [comment]
Si la descarga ha terminado correctamente no debería haber ni chunks ni archivos temporales. Eso suele pasar cuando se cierra la aplicación antes de tiempo.
