### ISSUE TITLE
No comienzan las descargas

### ISSUE THREAD

**Issue by mmiraglia** [tonikelope/megabasterd#156]
Al usar la versión 6.80 agrego 2 enlaces y jamás comienza la descarga.
Adjunto el log de la ejecución.
[log.txt](https://github.com/tonikelope/megabasterd/files/3940643/log.txt)

**Comment by tonikelope** [comment]
MEGA link?

**Comment by tonikelope** [comment]
¿Te pasa con la 6.79?

**Comment by mmiraglia** [comment]
Es el mismo problema con la versión 6.79
Los links que quiero bajar son:
https://mega.nz/#!YQl2EKTQ!CrXOm96wMQA71T7HuOewQrC983JgNBysRKM9XDOTVxs
http://mega.nz/#!NN0k0IzT!Dh3cgIhjunNERiuA4UvONIseSBo672-uxJWENzcm7fc

**Comment by DescargaProgramasFull** [comment]
Antes de descargar configura tu cuenta de Mega desde Ajustes/Cuentas

**Comment by mmiraglia** [comment]
Cuando trato de agregar la información de mi cuenta da este error:
`dic 09, 2019 1:57:21 PM com.tonikelope.megabasterd.SettingsDialog lambda$save_buttonActionPerformed$6
GRAVE: Illegal key size
`

**Comment by IribarrenWeb** [comment]
Me pasa lo mismo, pero con la diferencia de que a mi me empezó la descarga pero a los 20 min se paro y ahora no quiere arrancar por mas que lo reinicie y cancele las descargas y las vuelva a cargar. Con la 6.79 pasaba lo mismo pero con la diferencia que al reiniciar el programa y reiniciar la descarga, empezaba otra vez a descargar.

**Comment by MariioCL** [comment]
Mismo problema con la ultima versión, ahora no inicia ninguna descarga

**Comment by tonikelope** [comment]
Probad con la versión Portable porque es posible que tengáis algún problema con vuestra instalación de Java.

**Comment by fekysan** [comment]
> Es el mismo problema con la versión 6.79
> Los links que quiero bajar son:
> https://mega.nz/#!YQl2EKTQ!CrXOm96wMQA71T7HuOewQrC983JgNBysRKM9XDOTVxs
> http://mega.nz/#!NN0k0IzT!Dh3cgIhjunNERiuA4UvONIseSBo672-uxJWENzcm7fc

ya pude descargar estos archivos solo que tienen contraseña jejeje
