### ISSUE TITLE
SmartProxy

### ISSUE THREAD

**Issue by MariioCL** [tonikelope/megabasterd#157]
¿Hay algún problema con el SmartProxy del programa? Ya que luego de descargar algunos archivos, el programa no continua descargando archivos y tengo que esperar que pasen algunas horas para que MEGA liberé la cuota de descarga para descargar nuevamente. Tengo la opción "Utilizar descargas multi slot" activadas con el número 6, además de la opción "Utilizar SmartProxy".

No recuerdo en que versión pero antes no tenia problemas con descargar muchos archivos en pocas horas.

**Comment by tonikelope** [comment]
Hola. Lo que ocurre con SmartProxy es que la lista interna de MegaBasterd a medida que más gente va utilizando la aplicación lógicamente pierde efectividad. Por eso añadi la opción de usar una lista de proxys personalizada.

Cuando SmartProxy se activa automáticamente la palabra slots de la descarga se tiene que poner azul.

Salu2 ;)
