### ISSUE TITLE
Necesito tu ayuda

### ISSUE THREAD

**Issue by DJHunter740** [tonikelope/megabasterd#158]
Primero que todo gracias por tu programa, me ayuda un monton
Hace un tiempo que me esta sucediendo este fallo, las descargas llegan al 100% pero cuando abro la carpeta de descarga me sale 
![2019-12-11](https://user-images.githubusercontent.com/58794071/70669625-e72c1080-1c44-11ea-986a-c8141708ba4b.png)
y no se como descomprimir la descarga
gracias por tu ayuda de antemano

**Comment by tonikelope** [comment]
Hola. COn estos datos que me das no puedo hacer muchp. Sólo comentarte que aunque la barra de progreso marque 100% hastq que el estado de la descarga no cambie a verde y diga que ha terminado la descarga correctamente, la descarga no termina y si la detienes o sales antes te ecnontrarás con un archivo temporal y trozos que no se han juntado. Tienes que dejar que la descarga termine de forma normal.

Salu2 ;)
