### ISSUE TITLE
[Sugerencia] Interfaz manipulable

### ISSUE THREAD

**Issue by GATOQSECOMIO** [tonikelope/megabasterd#16]
En la ultima versión 2.29 me resulta imposible ver en "options" la parte baja para aceptar o denegar los cambios realizados. No cuento con mucha resolución (1366x768) de forma que no aparecen los últimos
elementos en las opciones.
Si la resolución es de *x800 entonces si se visualiza pero no es la resolución recomendada para mi monitor. Existe alguna forma de manipular/redimensionar la ventana de opciones?

![2017-11-27 13_12_46-](https://user-images.githubusercontent.com/19736343/33266093-78f50470-d374-11e7-87bc-be0b6ed467ed.png)

Gracias por tu esfuerzo.
Info: SO Windows7x64

**Comment by tonikelope** [comment]
Hola. Tienes razón. En cuanto tenga un hueco hago la ventana de settings modificable en tamaño y lo subo.

Salu2;)

**Comment by GATOQSECOMIO** [comment]
@tonikelope gracias por la atención! Sin duda Megabasterd es una app que, por ahora, no tiene remplazo, gracias otra vez. Saludos.

**Comment by tonikelope** [comment]
Hecho.

Salu2 ;)
