### ISSUE TITLE
Download PROblem

### ISSUE THREAD

**Issue by baba339** [tonikelope/megabasterd#161]
downloading speed become invisible after some and then it shows an error why please tell me and can i use the streaming link with idm to download?

**Comment by tonikelope** [comment]
When MEGA download bandwidth is exhausted and proxies are used it can happen from time to time. If the download spends more than 120 seconds without downloading anything it will autorestart to try to catch better proxies and finish the download.

Regards.

**Comment by baba339** [comment]
so what should i do,not use proxies?
