### ISSUE TITLE
mejorar uso de proxys

### ISSUE THREAD

**Issue by Superhackman** [tonikelope/megabasterd#163]
te recomiendo que el tema de proxys solo se utilice para generar links de descargas y luego que el archivo que se está descargando con megabasterd utilice la ip real de cada usuario, así no habría problemas con velocidades lentas
ejemplo: el otro método que se usa con megadownloader 1.7 y psiphon que antes de iniciar una descarga con megadowloader te conectas a cualquier país con el vpn y luego inicia la descarga hasta que se ve que se está descargando y despues desconectas el vpn y la descarga continua, porque? porque el link que se generó quedó almacenado en megadownloader y fue generado con otra ip y luego la descarga empieza a usar ip real del usuario sin problema alguno de errores o bajas velocidades nada de eso, estaria interesante que hicieras la prueba de solo usar el proxy unicamente para generar links y ya y al estar descargando utilice ip real del usuario es decir del proveedor que provee

**Comment by ArnyetLich** [comment]
Disculpe, pero que tipo de proxy puedo utilizar? cualquier proxy? donde puedo encontrar estas proxys? puedo utilizar vpn de terceros?
un disculpa y gracias

**Comment by Superhackman** [comment]
sorry but this topic is addressed to the developer

**Comment by tonikelope** [comment]
Hola. 

> te recomiendo que el tema de proxys solo se utilice para generar links de descargas y luego que el archivo que se está descargando con megabasterd utilice la ip real de cada usuario, así no habría problemas con velocidades lentas
> ejemplo: el otro método que se usa con megadownloader 1.7 y psiphon que antes de iniciar una descarga con megadowloader te conectas a cualquier país con el vpn y luego inicia la descarga hasta que se ve que se está descargando y despues desconectas el vpn y la descarga continua, porque? porque el link que se generó quedó almacenado en megadownloader y fue generado con otra ip y luego la descarga empieza a usar ip real del usuario sin problema alguno de errores o bajas velocidades nada de eso, estaria interesante que hicieras la prueba de solo usar el proxy unicamente para generar links y ya y al estar descargando utilice ip real del usuario es decir del proveedor que provee

Hola. Esas pruebas ya las hice antes de añadir el SmartProxy. MEGA limita las descargas por IP, no por enlace. Claro que es posible obtener el enlace de descarga enmascarando tu direccción IP con un proxy o una VPN y después desconectarlo y descargar con el enlace con tu IP normal, pero el contador de descarga asociado a tu IP seguirá incrementándose hasta que tu IP ya no pueda descargar de ningún enlace durante un tiempo. Desconozco si MEGA ha relajado sus restricciones y además tampoco tengo mucho tiempo para experimentos, pero antes era como lo describo.

Salu2 ;)

PD: no ignoro problemas. Simplemente le doy prioridad a bugs reales y no temas de descargas lentas por proxys que ya he explicado varias veces que no dependen de mi.

**Comment by ArnyetLich** [comment]
muchas gracias
