### ISSUE TITLE
Megabasterd stuck

### ISSUE THREAD

**Issue by ChaI-LacK** [tonikelope/megabasterd#167]
I have a whole row of 100% downloads that are just stuck. I checked task manager and megabasterd isn't using anything (just 80mb ram/ no network, no disk), i think it starts not responding after some time. Turning it off and on again works sometimes, but having a long list of small downloads makes it a torture.
![image](https://user-images.githubusercontent.com/58135214/71119998-bc5d3180-21db-11ea-8d81-7553bffc17b8.png)
Thank you for your service, please dont take these as complaints but as feedback to make the app perfect. You're doing a great job.

**Comment by tonikelope** [comment]
Although the download marks 100% it's really 99.9% and it's rounded, but until it appears in green as downloaded it doesn't end. MEGA quite often gives timeout error when downloading a chunk, and the bad thing about this type of error is that you have to wait about a minute until it jumps the timeout and retries the download of the chunk or chunks that have failed (all this is done transparently to the user). In addition, makes a few updates added a function to each download that monitors the progress and in case the download does not receive a byte in 120 seconds force restart the download. If any download gets stuck at 100% for more than 120 seconds and doesn't self-start, something else is going on.

Regards.
