### ISSUE TITLE
Problems when downloading mega files

### ISSUE THREAD

**Issue by kabbalah10** [tonikelope/megabasterd#17]
Attached screenshot of the problem, are almost 8 addresses that tells me that are not valid. I use Archlinux 86x64 and I have Gnome 2.26 installed
![captura de pantalla de 2017-11-29 11-07-29](https://user-images.githubusercontent.com/19537918/33385844-9a5548a8-d4f7-11e7-9c0c-a14ef20ca3ef.png)

**Comment by tonikelope** [comment]
I think it's now fixed. 

Regards.

**Comment by kabbalah10** [comment]
Thanks for the response, but the problem remains the same just just down the program again and try to download a mega file and the same message.

**Comment by kabbalah10** [comment]
> https://mega.nz/#!CEcz3LRD!a1E9oFyznuVCsg2vd87kl8HDd9Ttny3_GCGFIsOImwk%20

**Comment by tonikelope** [comment]
I have just tried with 2.35 and it downloads. What version did you download?

Regards.

**Comment by kabbalah10** [comment]
2.35 y 2.11

**Comment by kabbalah10** [comment]
2.36 neither download I'dont know that occur

**Comment by tonikelope** [comment]
Hi. Could you try 2.39 please? I just checked it out.

**Comment by kabbalah10** [comment]
I tried with Linux Mint and with Windows 10 and none of them worked, it's strange because yesterday worked fine.

![captura de pantalla de 2017-11-29 18-24-41](https://user-images.githubusercontent.com/19537918/33404542-afc50648-d532-11e7-9064-c554dc172eb6.png)

**Comment by kabbalah10** [comment]
Change the java environment from 9 to 8 and nothing

**Comment by kabbalah10** [comment]
With other link It working

**Comment by tonikelope** [comment]
Please, PASTE HERE ALL the links you are trying to download (no screenshots).

Regards.
