### ISSUE TITLE
Deja de descargar, stop downloading

### ISSUE THREAD

**Issue by alfaman1** [tonikelope/megabasterd#174]
Después de descargar 500mb la descarga se paró y queda de esta manera.
After downloading 500mb, the download stopped and looks like this.

[https://ibb.co/mvp2w0J](url)

Nota: Justo ahora comenzó a descargar pero demasiado lento. 27B/S
Note: Right now it started downloading but too slow. 27B / S

**Comment by tonikelope** [comment]
Los proxys a veces descargan muy lento. La unica opción es esperar a que cambie de proxy o reiniciar la aplicación para forzar a que coja nuevos proxys.

Salu2 ;)
