### ISSUE TITLE
Error 1/2/3/4

### ISSUE THREAD

**Issue by UserDistortion** [tonikelope/megabasterd#175]
Agrego los enlaces para descargar y cuando va al 13% o antes de empezar debajo de los Slots aparece un error en rojo que dice "Error 1" el número varía entre 1 y 4 moviéndose en el orden 1, 2, 3, 4 y volviendo a repetirse.
No sé a qué pueda deberse pero es la falla más molesta que le encontré al .jar.

**Comment by tonikelope** [comment]
Es normal. Cuando la descarga de algún slot falla se marca en rojo el total de slots que fallan. 

Salu2 ;)
