### ISSUE TITLE
resets, bugs, stuck downloads

### ISSUE THREAD

**Issue by teasermegatz** [tonikelope/megabasterd#177]
hello, first of thank you for the app!

some questions im interested in:

letting dls run overnight with like 10 slots, having a long queue. next day, most of the time the original 10 are stuck at 98-99% and none of the new ones have started or some of them have like 20-30%, but what pisses me off most is that from the 10 99% downloads, 8 restart completly or nearly completly on app restart,

its infuriating that one file needs 3-4 attempts (and like double download volume) to finish downloading.

the pause button takes forever, you dont even know if its doing something.

closing the app takes also forever if you dont just end it, i dont have an hour to let the app go to sleep.

no way to sort the running downloads, no way to force a smart proxy reset inapp.

i love the app but sometimes its just getting frustrating if not even one download finishes correctly without restart or some other fixing.

**Comment by metoxys** [comment]
Unfortunately I've been having the same issues this week, using 6.91. Upgrading to 6.95 to see if that's any better

**Comment by HyperScorpio** [comment]
I have the same problem too.

**Comment by tonikelope** [comment]
I haven't been able to reproduce that bug. When a chunk download fails by timeout (60 seconds) it restarts the chunk download transparently. Besides this, there is another mechanism that monitors each MegaBasterd transfer independently and restarts it in case it gets stuck and doesn't transfer data for 5 minutes. Therefore, I find it very strange that downloads are stopped at 99%. Which format of MegaBasterd do you use? Jar or exe? Java version? Operating system?

I also need the execution log of when that happens to you to try to see if any error occurs. For that, as I have explained many times, you have to launch MegaBasterd by console:

`java -jar MegaBasterdxxx.jar`

Regards.

**Comment by HyperScorpio** [comment]
I found the problem, this is a trick of mega website, i download at least 5GB and after that the speeds decreeses at least 20kb/s slow. And i was downloading one each time and it's not problem of being big sizes.

**Comment by teasermegatz** [comment]
hey tomikelope, didnt meant to be rude with the first post.

seems 6.96 (or my switch to from java to win mobile) fixed some of the issuses like the stuck 99% but im gonna test it tonight with with a queue of 10 slots 5 run/5 wait.

**Comment by HyperScorpio** [comment]
Well i found a nother trick but we need to use MEGAsync and a tool to change VPN.

**Comment by savefromgoogle** [comment]
I was having an issue with downloads that are stuck since a couple of versions/months now.

My workaround is to regularly restart MegaBasterd through a bash script, like this:
```#!/bin/bash
while true
do
	nohup /usr/bin/java -jar /home/user/MegaBasterd_6.97.jar &
	sleep 45m
	pkill --signal 15 -f MegaBasterd.*\.jar
	sleep 3s
done```

**Comment by teasermegatz** [comment]
hey, had some test with 6.96 and it worked good, some unexpected errors but no stuck downloads anymore. 

6.97 i tested only short because the slots dropped rapidly mid-download and stuck at -1 so i switched back to 6.96 which works fine.

**Comment by ultimatelyco** [comment]
Each new version keeps getting worse for me.  The most stable version for me is windows portable 6.91.  All versions hang or get stuck but that version recovers the best once forced to close and reopen.  The latest version 7.1 is the worst for me.  I was forced to close and when I reopen it consistently says fatal error already connected.  And with past versions I could resume downloads between versions if I kept the dl chunks and pointed the download link to the same directory but now it says file already exists and refuses to continue.   

I love and appreciate the program but I am staying on 6.91

**Comment by RubySapior** [comment]
Yea i also keep getting FATAL ERROR! Already connected.
Guess ill download the 6.91

**Comment by ultimatelyco** [comment]
6.91 is my safety net.  Though I may have to fight with it, it will eventually complete all transfers.  

I haven't completely put 7.2 through the paces. Its better but im still getting fatal error after awhile.  I have faith you'll get it eventually and you are putting out new versions at light speed today.

**Comment by ultimatelyco** [comment]
So far everything is good for me in 7.9.  Best version so far.

**Comment by shahnitav** [comment]
My downloads are not initiating at all, the files do get loaded in the queue with the label 'Downloading file from MEGA' but without any speed. Megabasterd 6.8 was working fine with running downloads but they get stuck at 1GB, whereas all the 7.0+ version can't even start downloads.

**Comment by SASHWAT12** [comment]
Use vpn when download stops, genrally it stops after 3gb of download. If you have large file then use vpn with ip shuffle or disconnect and connect vpn again.

**Comment by thunderpants** [comment]
Yep .i mentioned in another thread ,my 5gb download stopped at 91%.
I closed Megabasterd (make sure it's completely c;losed in systray)
I booted up Megasync to check with the same file download and it flashed up a warning saying i had used up my quota.
Then i started a  vpn , restarted megabasterd again and resumed the download ok.
