### ISSUE TITLE
Getting "mega link error" when trying to download from a folder

### ISSUE THREAD

**Issue by invaderdan** [tonikelope/megabasterd#178]
First time I've ever had a problem, getting "mega link error" when trying to load this folder link: https://mega.nz/#F!3zAwzB5B!geI0kA0qocBYz_Xyovty8w!mrYjmDzL

any help would be amazing :)

**Comment by tonikelope** [comment]
That kind of subfolder link doesn't work at the moment. The alternative is to use the link like this: 

https://mega.nz/#F!3zAwzB5B!geI0kA0qocBYz_Xyovty8w

and select the subfolder you want to download from inside MegaBasterd. If I have time I will add support for this type of link.

Regards.

**Comment by Mohitsachdev** [comment]
Hey brother i want this link plz……
It show mega link error
https://mega.nz/folder/uWRXDQKA#muXzoiz6qAJIFCIxvSkIIQ/folder/2DpnRKzB

**Comment by tonikelope** [comment]
![Screenshot_20220109_183503](https://user-images.githubusercontent.com/1344008/148693795-dec8736a-1692-48e6-8d47-f3e7e9866e19.png)

The folder loads, but because it has so much content it takes a long time and you have to be patient. I recommend you to use the web browser (better chrome) to select the subfolder you want to download.

**Comment by rahin147** [comment]
give this mega 13 tb link please

**Comment by rahin147** [comment]
> ![Screenshot_20220109_183503](https://user-images.githubusercontent.com/1344008/148693795-dec8736a-1692-48e6-8d47-f3e7e9866e19.png)
> 
> The folder loads, but because it has so much content it takes a long time and you have to be patient. I recommend you to use the web browser (better chrome) to select the subfolder you want to download.

sir give this mega 13 tb link please
