### ISSUE TITLE
Doesn't start/doesn't work

### ISSUE THREAD

**Issue by ElMorenoJuan** [tonikelope/megabasterd#18]
The program shows its starting window (Kim Dotcom's picture) and stays there forever. However, it does show the tray icon, and if I double click it the program's interface will show, though starting a new download doesn't show the window to paste the desired link. In other words it doesn't work properly. I tried again after disabling my antivirus and unpacking the .zip again, also I tried putting it in the antivirus ignore list, but nothing changed. Win 10, java updated. Hope you can fix this soon and all my kudos to you for this awesome little app!

**Comment by ElMorenoJuan** [comment]
Nevermind lol, a simple reboot did the trick. Pretty strange tho. Maybe this info will be useful if anyone else has the same problem.

**Comment by tonikelope** [comment]
I'm glad it's working for you now.
