### ISSUE TITLE
getting fatal error

### ISSUE THREAD

**Issue by glh290** [tonikelope/megabasterd#180]
when starting the downloads, im getting fatal error already connected, shortly after the program generates the temp file. I assume this is the smart proxy not connecting properly as I've hit my local download limit. this started for me earlier today when I loaded up 7.2, and is persisting in 7.4.

**Comment by Alex1331xela** [comment]
Same issue here, so it's not just you.

**Comment by glh290** [comment]
I'm having moderate success with 6.97 and 6.99. the slow dowloads there could just be my proxy list. its kinda sad tho, 7.2 did fix my issues with restarting a download.

**Comment by tonikelope** [comment]
There's been a couple of regressions. I think they're corrected now (7.5). Sorry for the inconvenience.

**Comment by glh290** [comment]
is 7.5 supposed to be a source release only?

**Comment by tonikelope** [comment]
Yes. Go back to 6.97 for now

Sorry for the inconvenience. I'll arrange everything as soon as possible.
