### ISSUE TITLE
Fallo botón pause all y cerrar programa

### ISSUE THREAD

**Issue by F-J-V** [tonikelope/megabasterd#182]
Hola, en la versión 7.6 al pulsar el botón "pause all" aparece el de "resume all", pero cuando terminan de pararse las descargas desaparece el botón "resume all" y no se puede volver a iniciar las descargas.

Solo puedo cerrar el programa, pero cuando lo abro de nuevo han desaparecido todas las descargas, y las tengo que cargar de nuevo, aunque enseguida reconoce los archivos que ya están descargados.

Igualmente si salgo aunque espere a cerrar de forma segura al volver a entrar el programa aparece en blanco sin ninguna descarga.

Saludos

**Comment by tonikelope** [comment]
Creo que está arreglado en la 7.7 pero es necesario purgar la base de datos interna con las instrucciones que he puesto en la descarga de la nueva versión.

Disculpad las molestias.

**Comment by F-J-V** [comment]
¡Que rapidez! 👍 
El botón de pausa ya funciona bien, pero si salgo del programa se siguen borrando las descargas. He seguido las instrucciones.

Saludos.

**Comment by tonikelope** [comment]
No consigo reproducir lo que comentas. Además, en la actualizacion anterior no he tocado nada del botón de pausa. Grábame si puedes un video de los pasos que sigues a ver si consigo entender qué te pasa. 

¿Usas el .jar o el .exe?

Salu2 ;)

**Comment by F-J-V** [comment]
Hola, esta tarde lo intento.

El botón de pause all vuelve a fallar en la 7.7 solo funcionó bien la primera vez.

Normalmente uso el jar, pero he probado con el exe y pasa lo mismo, al pausar desaparecen no solo el botón resume all, sino todos los botones de reanudar de las descargas, y al cerrar el programa independientemente de que lo pause o no, se borran las descargas.
 
Con la versión 6.95 no ocurre nada de esto.

Saludos

**Comment by tonikelope** [comment]
A ver si hay suerte con la 7.8

Salu2 ;)

**Comment by F-J-V** [comment]
Con la 7.8 versión jar ya se ha corregido que se borren las descargas al salir del programa, pero lo del botón resume all sigue fallando, por ejemplo tengo 10 descargas activas, pulso pause all y el botón pasa a llamarse resume all, se van cerrando las descargas y aparecen los de reanudar individuales, pero al pausarse la ultima descarga se borra el botón resume all y todos los botones de reanudar individuales, por lo tanto la única opción es salir del programa y volver a entrar.

de momento no puedo hacer grabación, en cuanto pueda la subo.

saludos.

**Comment by F-J-V** [comment]
Nuevas pruebas.
El problema de la desaparición del botón resume all ocurre después de haber descargado unos 4 o 5 gigas, que el programa deja de descargar y empiezan las descargas a pararsey empezar con otras.

Antes cada descarga esperaba un minuto o mas sin descargar para pararse para salir del estado de descarga y pasar a la cola de espera, pero ahora tarda solo dos o tres segundos, por lo que si tengo 10 descargas simultaneas el programa entra en un estado de parar e iniciar descarga nueva constantemente. En este estado ocurre lo de borrarse el botón resume all.

De todos modos el botón no funciona correctamente, si lo pulso cuando el programa está descargando, solo funciona bien con una o dos descargas simultáneas, puesto que si tengo más, si lo pulso y alguna descarga termina antes de que llegue a pausarse, empieza una nueva descarga y esa ya no se pausa, por lo que quedan varias pausadas y otras no, y si vuelvo a pulsar el botón  se reanudan las que estaban pausadas y se pausan las que estuvieran activas, por lo que no consigues pasarlas todas, pasando el botón únicamente a alternar entre las que están activas y las que están pausadas.

No he probado esto ahora en versiones anteriores, pero sí recuerdo que antes pausaba y se paraban todas.

Saludos.

**Comment by F-J-V** [comment]
[video.zip](https://github.com/tonikelope/megabasterd/files/4036366/video.zip)
En este vídeo se reproduce el error del botón después de haber estado descargando unos 4 gigas. En otras versiones anteriores se pasa un buen rato así hasta que comienzan de nuevo las descargas. Como siempre que uno quiere demostrar algo, la primera vez que pulso el botón funciona, pero a la segunda veras el fallo.

Cuando si está descargando a buen ritmo no desaparece el botón, pero como te comenté el funcionamiento falla a veces y simplemente alterna entre unos cuantos pausados y los que están activos en ese momento. Si hace falta también lo grabo.

Saludos.

**Comment by F-J-V** [comment]
[video2.zip](https://github.com/tonikelope/megabasterd/files/4037077/video2.zip)
En este segundo vídeo muestro el funcionamiento del botón pause all cuando el programa está descargando a buen ritmo. Nuevamente la primera vez que lo pulso funciona bien, pero otras veces desde la primera vez.
Como veras, cada vez que pulso el botón pause all, se alternan las descargas activas con las pausadas, y así indefinidamente, y ya no vuelve a cambiar el nombre del botón por resume all, se queda en pause all.

Saludos.

**Comment by tonikelope** [comment]
Hola. Que las descargas se paren solas al empezar tan deprisa es raro. No
da tiempo a ver el error que aparece en rojo. Necesitaría que ejecutaras
por consola MegaBasterd y me pegues aqui el log de errores.

Salu2 ;)

**Comment by F-J-V** [comment]
Hola, por la salida normal (java -jar MegaBasterd_7.8.jar > log.txt) no sale absolutamente nada, se queda a cero, todo el log sale por la salida de errores (java -jar MegaBasterd_7.8.jar 2> log.txt).

Este log es del programa recién abierto y que ya falla por tener descargas anteriores. Ahora también al darle al botón de salir me sale una pantallita nueva que no había visto antes, advirtiéndome que se están aprovisionando transferencias o algo parecido, si estoy seguro de querer salir. Supongo que es correcto, pero nunca me había salido.

[log.txt](https://github.com/tonikelope/megabasterd/files/4038036/log.txt)

Saludos.

**Comment by F-J-V** [comment]
Hola, en la versión 7.9 el botón de pause all no falla, pero prefiero el comportamiento que tenia con las versiones 6.97 y anteriores, puesto que a veces pausar todos los archivos tarda bastante, y ahora el botón queda inhabilitado hasta que se pausen todas las descargas, mientras que en versiones anteriores podías volver a iniciar las descargas sin tener que esperar.

Puse una descarga de unos 9 gigas, y cuando llegó a 4 se detuvieron las descargas, al rato se reanudó pero muy lento y los números de descargas se pusieron todos en rojo, en vez de azul.

Salí del programa y volví a entrar, pero sigue igual, descarga lenta y números en rojo, no se ponen en azul.

he echo un log para que veas lo de los números en rojo, también comentarte, esto desde siempre, que salir del programa si espero a que se detenga de forma segura tarda mínimo unos 10 minutos, a veces mucho mas.

De momento me paso a la versión 6.97. He puesto la misma descarga y ahora mismo no descarga, como es habitual después de unos 4 gigas, pero las rallas de las descargas están en azul. Normalmente se pega así un buen rato y luego comienza de nuevo a descargar.

log versión 7.9: [errorlog.txt](https://github.com/tonikelope/megabasterd/files/4043369/errorlog.txt)

Saludos.

**Comment by tonikelope** [comment]
De momento dejaré el botón así. Sobre las rayas naranjas, se ponen así cuando se empiezan a usar los proxys por haber agotado el límite de descarga diario de MEGA. En la 6.97 no cambiaba de color la velcoidad sino que se ponia en azul la palabra SLOTS, pero es lo mismo.

Salu2 ;)
