### ISSUE TITLE
7.8 - 2 issues.

### ISSUE THREAD

**Issue by rfmsec** [tonikelope/megabasterd#183]
I've encountered issues while trying to download using the latest version.

1) FATAL ERROR already connected - this happens to all of the downloads after adding them.
2) Error registering download: [SQLITE_CONSTRAINT] Abort due to constraint violation (UNIQUE constraint failed: downloads.path, downloads.filename)
![image](https://user-images.githubusercontent.com/43323904/71981131-643dac00-322a-11ea-923f-c57f3806f10e.png)

**Comment by savefromgoogle** [comment]
Just checking, have you been following the instructions for that version?

> It's recommended to reset MegaBasterd
>
> RUN NEW VERSION AND IMPORT SETTINGS FROM PREVIOUS VERSION.   
> EXPORT YOUR SETTINGS.
> RESET MEGABASTERD in order to clean transferences internal database (you will lose your transferences (temp files will be preserved)).
> IMPORT SETTINGS
>
> Note: copy and paste your current transfers links in a txt file before RESET.

**Comment by Sibbs** [comment]
that happened to me on v7.6, but it hasnt happened since, just go to c drive /user/your name and delete all the megabasterd folders , then load up prog and redo your settings

**Comment by Zomba13** [comment]
I'm also getting the "FATAL ERROR already connected" issue. It started happening this week on multiple versions. I've deleted the files in User, deleted the old versions, reset the program and I still get it. Got it today after 51% on a 9.something GB file so it isn't getting past the limit. I even then tried my VPN but it still didn't resume.

Using the Windows portable app version.

**Comment by ultimatelyco** [comment]
Yeah the fatal error is definitely not fixed.  I too deleted both mega folders in User and problem persists.  It doesn't seem to happen until after about 4-6gb are downloaded.  Once it happens, there doesn't seem to be any work around.  It is a shame because I was getting great speeds on the new version without any downloads stuck at 99 or 100% etc.  I eventually downgraded to 6.91 where it was like half the speed and like two to three of the dl stuck and forced me to restart the app to get clear finished, but it did finish.

**Comment by Vig2OOO** [comment]
Same here, FATAL ERROR still persists even after deleting all Mega folders.

**Comment by tonikelope** [comment]
I need you run MegaBasterd from console and paste here log

`java -jar MegaBasterdxxxxx.jar > log.txt`

**Comment by savefromgoogle** [comment]
> I need you run MegaBasterd from console and paste here log
> 
> `java -jar MegaBasterdxxxxx.jar > log.txt`

I added some log here: https://github.com/tonikelope/megabasterd/issues/185#issuecomment-572585738
