### ISSUE TITLE
This Mega Folder Freezes Megabasterd Link Grabber Window

### ISSUE THREAD

**Issue by Sibbs** [tonikelope/megabasterd#184]
https://mega.nz/#F!3bongAIJ!NsrbRj3nK0DPEKylkd_gKg

im on 7.8, and i deleted my megabasterd folders in my user c drive folder, and redid settings so it was completely reset, ive never encountered a mega folder link that froze the program before, i know the links is good too, see for yourself

Also a change proxy button on the main window would be awesome, if it had to restart the prog to change it, thats cool , it could automatically pause downloads then change and restart, or have the program automatically change it , if download stops for 5-10 secs, i use my own proxies, and if a download stops, i would like it to change to a new proxy in seconds, instead of manually pausing downloads, deleting proxy line, restarting program, that gets old fast, by the way awesome program you got, your a real lifesaver, for people who cant afford mega premium, Thank You!

**Comment by tonikelope** [comment]
Hello.

I just tried it with version 7.8 and it works fine. I need you to run
MegaBasterd from the console and paste the output here to see if there are
any errors when reading the link. Which version of Java and Windows?

java -jar MegaBasterdxxxxx.jar > log.txt

**Comment by Sibbs** [comment]
i was using the windows portable version
