### ISSUE TITLE
Continuous Stopping of Downloads

### ISSUE THREAD

**Issue by BatchAssassin** [tonikelope/megabasterd#185]
Downloads continuously stop since 6.97. 7.8 seemed to fix it at first, but started doing it again a while later. If I hit "Pause All" it pauses everything, but no resume button appears, so the only way to resume downloads is to restart the program, but then the downloads keep stopping again. Switching back to 6.97 fixes the issue, but also resets settings. Running on Windows 10 x64.

**Comment by tonikelope** [comment]
¿Log?

**Comment by BatchAssassin** [comment]
> ¿Log?

Where do I find the log? I don't see one in the program's directory. Using .exe version.

**Comment by savefromgoogle** [comment]
Same here on Ubuntu Linux.

The error message that is being displayed continuously is "FATAL: Already connected". The download is stopped and restarted. After a 3 second wait, the same begins again, in a constant loop.

**Comment by tonikelope** [comment]
Thanks for the log. I can't get into this right now. I'm giving it top priority and I'll try to see what happens as soon as I get some time off.
