### ISSUE TITLE
Slot Setting not working properly

### ISSUE THREAD

**Issue by Cyphco** [tonikelope/megabasterd#187]
I'm downloading a few files currently and i notice that the Slot number always jumps to 20 and doesnt stop at the 5 i chose in the Settings.

And a little side note, would be nice if we could import our own HTTP Proxy list (not sure if its already possible but it would be nice to speed up things)

**Comment by tonikelope** [comment]
When the proxy download is activated, the number of slots is increased to the maximum in order to maximize the download speed through the proxies, which is usually lower than when downloading directly.

On the personal proxy list it is possible to enter it in settings>downloads at the bottom.
