### ISSUE TITLE
Alternate fonts causing missing text

### ISSUE THREAD

**Issue by Juesto** [tonikelope/megabasterd#188]
so im using the jar version on windows, i don't know where the config is located, i am not sure what's the alternative fonts are targeted for...
![image](https://user-images.githubusercontent.com/12691160/72534409-8308f780-3855-11ea-9cf5-f0c43bb24ff2.png)

**Comment by tonikelope** [comment]
In Windows, config file is in your user Folder Delete it.

Regards.

**Comment by Juesto** [comment]
You didn't specify the path...

**Comment by Juesto** [comment]
Also I just checked in the jar folder and the alternate font seems to be notosanscjk which is chinese/japanese/korean and it does not work under windows 7 because of the format it's in

**Comment by Juesto** [comment]
@tonikelope disculpa, aun no encontré la ruta de la configuración

**Comment by Juesto** [comment]
ok, it's `.megabasterd`
idk why i didnt see it

**Comment by Juesto** [comment]
still, the font does not work in windows 7, that's the whole issue here.
