### ISSUE TITLE
Run external script on 509 bandwidth error

### ISSUE THREAD

**Issue by lightc786** [tonikelope/megabasterd#189]
Was this ever implemented? https://github.com/tonikelope/megabasterd/issues/113

I intend to have a script to reboot my modem to get a new ip address rather than use smartproxy which can be unreliable and slow to complete larger downloads.

**Comment by tonikelope** [comment]
Advanced settings > Run external command...

**Comment by lightc786** [comment]
Running 7.12 on Windows, if I put the path to the script I want it to run when it reaches the MEGA download limit, it doesn't launch the script... Am I doing something wrong?

I've tried with and without quotations. See screenshot

![image](https://user-images.githubusercontent.com/55266233/72783092-8d2f4b00-3bf3-11ea-884d-953e27cd9bcf.png)
