### ISSUE TITLE
Error en la subida

### ISSUE THREAD

**Issue by axo1** [tonikelope/megabasterd#19]
Me sale este error cada vez que quiero subir algo, a ver si lo puedes solucionar
https://i.imgur.com/tLD1nbe.png

Saludos!

**Comment by tonikelope** [comment]
Hola. La versión 2.61 no es compatible con las anteriores (es necesario instalarla en un directorio limpio y configurar los ajustes de cero). 

Otra opción si tienes muchas cuentas de mega metidas y no quieres perderlas, es aguantar con la 2.60 hasta que en la 2.62 meta una opción que adapte los ajustes antiguos al nuevo formato de forma transparente. 

Salu2

**Comment by axo1** [comment]
Gracias por la aclaración, al final llené las cuentas que tenía con otro programa así que ahora borro los ajustes y me quedo con esta.
Saludos!
