### ISSUE TITLE
Watchdog error

### ISSUE THREAD

**Issue by Jajajano** [tonikelope/megabasterd#191]
When my download hits 46% it appears an announce that says something like "Watchdog error!"
and it stops downloading

**Comment by Jajajano** [comment]
Oh and my download size's is 684 mb and I have another download that have 4.38 GB. Sorry bad english

**Comment by tonikelope** [comment]
It's the default behavior. When a transfer remains more than 5 minutes without receiving any data, it is automatically reset.

Regards.
