### ISSUE TITLE
Seeking while streaming

### ISSUE THREAD

**Issue by promegabasterd** [tonikelope/megabasterd#193]
Hey, I've run into a small problem while streaming an MKV-video
```
--> mpv (localhost-link)..... (streaming an mkv)
[mkv] Expected element 0x1c53bb6b not found
[mkv] Expected element 0x1254c367 not found
[mkv] Corrupt file detected. Trying to resync starting from position 5834...
[mkv] Cluster found at 5844.
```
But video playback works like a charm...

Only seeking doesn't work, it looks like MegaBasterd downloads everything until reaching the sought position..

Any thoughts?

**Comment by tonikelope** [comment]
mpv didn't go very well with megabasterd ever (and I don't know very well why). However, mplayer has worked well for me so far. If you can use mplayer, I recommend it.

**Comment by promegabasterd** [comment]
Thanks!! mplayer works much better :)
