### ISSUE TITLE
Mejorar compatibilidad con Java 13

### ISSUE THREAD

**Issue by InventM4n** [tonikelope/megabasterd#194]
Con Java 13 el explorador de archivos tarda en cargar unos 10-15 segundos y cada vez que tratas de abrir una carpeta lo mismo, con Java 8 no pasa.

**Comment by andrewjmetzger** [comment]
English translation: 

> With Java 13 the file explorer takes about 10-15 seconds to load, and every time you try to open a folder the same slowness occurs. With Java 8 it doesn't happen [only with Java 13].

**Comment by InventM4n** [comment]
You didn't solve the problem, when you use java 11+ if you try to open file explorer you must wait 20-30 seconds

**Comment by tonikelope** [comment]
Hola. Acabo de probar la versión portable que incluye OpenJDK 14 y no soy
capaz de reproducir nada de eso. Tampoco me pasa con OpenJDK 11.

Te recomiendo que pruebes alguna versión portable o cambies la versión de
Java del sistema.

Salu2 ;)
