### ISSUE TITLE
Couldn't Bypass Download Limit 

### ISSUE THREAD

**Issue by Signup-pawan** [tonikelope/megabasterd#195]
Hi,

Thanks for the app :)

First 5GB downloaded normally without any problems.. after that like any other application(MegaDownloader) it couldn't download. Stuck with download speed even when we try to download on VPN. If I switch on VPN Download Speed is 30 to 120 KB else showing blank as in below image.

If there is any workaround please let us know.

Thanks again Bro for the app :) @tonikelope 

![image](https://user-images.githubusercontent.com/55138565/73515431-49bab500-441b-11ea-8c54-61d9cf7d9257.png)

**Comment by DogegoD** [comment]
I have this same issue

**Comment by patros36** [comment]
Same here and for a long time. @tonikelope this should be fixed asap as this is the primary function of this software.

**Comment by rumqye** [comment]
go to edit->setting
make sure option : use smartproxy was checklist
![smartproxy](https://user-images.githubusercontent.com/66983463/84838282-2f991080-b064-11ea-8260-fce9b41b51de.jpg)

**Comment by patros36** [comment]
ofc it is, it is checked by default. Only thing i don't have are my own proxies, but megabasterd should use several public ones and those are probably those i would find on my own.

**Comment by TwinTechSolutions** [comment]
https://github.com/clarketm/proxy-list/blob/master/proxy-list.txt

**Comment by TwinTechSolutions** [comment]
Use the above proxy list its updated daily might help

**Comment by jimsy3** [comment]
mine downloads like 9gb and then limit kicks in and i have to change the ip lol

**Comment by oluwasemilorebadejo** [comment]
> 

i am having the same issue right now. what do i do pls

> mine downloads like 9gb and then limit kicks in and i have to change the ip lol

**Comment by dhaval079** [comment]
> ofc it is, it is checked by default. Only thing i don't have are my own proxies, but megabasterd should use several public ones and those are probably those i would find on my own.

/

**Comment by CallMeRana** [comment]
i got a solution for downloading speed . ! Just DONT DOWNLOAD 😆
