### ISSUE TITLE
[v2.62] Error SQL en la subida

### ISSUE THREAD

**Issue by GATOQSECOMIO** [tonikelope/megabasterd#20]
Tengo la ultima versión de MBasterd v2.62. Ocurre el error `[SQLITE ERROR]SQL error or missing database` en el siguiente contexto:
+ La subida es a través de una cuenta de mega activa (pre-seleccionada) y con espacio suficiente para la subida.
+ Uso `multi-slot` (6) en el proceso de subida
+ Son archivos `.mp4` de menos de 200 mbs
+ Tras elegir los parámetros para la subida (cuenta y archivos) aparece el error en cada uno de ellos durante el proceso de subida (inexistente, el error aparece previamente, antes de subir)
+ Acudir a `Restart` tras el error deriva en `Provisioning upload, please wait...` pero no resuelve el problema, se queda en carga constante sin ningún cambio aparente.
 
Adjunto una imagen del error
![2017-12-30 18_45_12-megabasterd 2 62](https://user-images.githubusercontent.com/19736343/34456203-293e8a00-ed91-11e7-915b-b1e4b4aa0747.png)
SO W7x64bits

Gracias de antemano, saludos.

**Comment by tonikelope** [comment]
Hola. Sí, es normal porque a partir de la 2.61 ha cambiado el formato interno que usa el programa para almacenar las subidas. Tiene solución fácil pero tendrás que volver a meter los ajustes del programa.

1) Antes de nada, si tienes cuentas de Mega exportalas a un fichero.

2) Cierra MegaBasterd y elimina el fichero megabasterd.db

3) Abre Megabasterd, importa tus cuentas y configura los ajustes a tu gusto. (Después elimina el fichero de cuentas exportado por seguridad).

Disculpad las molestias. (En siguientes actualizaciones no hará falta).

Salu2 ;)

**Comment by GATOQSECOMIO** [comment]
@tonikelope El problema, tal como dices, se ha solucionado borrando `megabasterd.db`. He exportado e importado las cuentas, después he borrado el archivo resultante de la exportación y listo. Puedo confirmar que funciona sin problemas la subida.
Gracias otra vez.

**Comment by tonikelope** [comment]
En la versión 2.63 he añadido la opción de exportar/importar TODOS los ajustes (no sólo las cuentas). Sólo recordar, que antes de exportar los ajustes es necesario SALVAR las modificaciones.
Cierro.
