### ISSUE TITLE
Downloads Slow Way Down

### ISSUE THREAD

**Issue by DJboutit** [tonikelope/megabasterd#200]
Downloads get to like 60% to 70% complete and they slow down to like 250kbps when they start out they start at like 8mbps to 12mpbs.  This has happened the last 10 files I have download it should not take 4 to 6 hrs to download 1gb if you have fast internet.  Please fix this thx

**Comment by AlfonsoRiberio** [comment]
Trust me, it won't get fixed. There is zero rhyme or reason to which files will suddenly slow to a crawl or freeze entirely. You can have three files chugging along topping out your connection speed and a fourth just frozen and twitchy with error messages. They all constantly flash error messages actually, regardless of whether they're downloading smooth as butter or not. All in all, fuck this app

**Comment by JaggB** [comment]
Same issue here, tried various versions, including ones from last years releases. Seems like it downloads ~5GB at max speed (30mb/s) but then slows downs to 300kb/s. Only workaround is to change VPN Server.

**Comment by raj664** [comment]
HI,

### Im facing issue with Mega-Basterd  7.50 

1.  **.download suddenly stuck** 

-    Downloading dashboard show  "_zbc KB/bdcv GB"_ 
![Screenshot from 2022-07-14 13-58-40](https://user-images.githubusercontent.com/44313300/178938982-6478d023-bd88-41a8-98b0-a2cd4bcc25fa.png)


2. After some time the terminal show connections time out

- My screen would be active  mode ,I do some learning stuff & parallel i download the videos ,  Please let me know what would be the problem.
- O.S Ubuntu  22.04 LTS 
- Mega-Basterd  7.50

![Screenshot from 2022-07-14 13-57-51](https://user-images.githubusercontent.com/44313300/178939237-aecfe86d-af49-43ca-bb69-66c3a984f3dc.png)
