### ISSUE TITLE
Interface can block for extremeely long time as FolderLinks attempt to load

### ISSUE THREAD

**Issue by spiralsam** [tonikelope/megabasterd#204]
Win10 x64:

When adding Folder Links as downloads, the FolderLinks dialog opens ("Folder link detected!"), allowing which files to checkmark and retrieve.

The problem is that I've had the following more than once with various meganz Folder Links I've tried to add:

The dialog opens, with the entire folder section blank except the greyed out "root" folder. The button in the lower right corner of the dialog is labeled "Loading" as if it's retrieving the folder contents. All dialog buttons are greyed out. Then instead of retrieving any contents, the dialog simply stays in that state. This dialog is not closable. It's modal. The Megabasterd main window operates in the background normally (downloading files), But the application is stuck like this.

NOTE: As I was writing this issue with MegaBasterd running in the background, I had originally thought the application was stuck forever - meaning I could only close it by killiing the java.exe process. It turns out that eventually (we're talking estimate 10+ minutes later unable to do anything), Megabasterd eventually returns either the content or "MEGA LINK ERROR!" and returns to normal. The links this has happened for are probably usually large GB folder links.

There is no indication what is happening and no way to even abort or know it's fetching folders silently and not just locked up.

SIDE NOTE: The MEGA LINK ERROR might be related to #178. An indication of this in the interface could be helpful.

**Comment by tonikelope** [comment]
Example slow link?

**Comment by silenceofthewans** [comment]
I'm getting this too. Here's a link that does this ([Base64 Decode](https://www.base64decode.org/)):
aHR0cHM6Ly9tZWdhLm56LyNGIVJ0QlhqU0FZIWF0bEdlSVdmbEFwem1hYzh1LXk5cWc=

**Comment by tonikelope** [comment]
I can't reproduce the problem you're talking about. That link loads in 1 second. What version and "flavor" of MegaBasterd do you use? Java version? Operating system?

**Comment by silenceofthewans** [comment]
OS: Win 10 64-bit

I was using 7.22 but I saw that you pushed a new update and the problem is solved in 7.23 for me. Thanks!

> PS: you can copy and paste base64 encoded links in MegaBasterd

That's cool I didn't know that. Will definitely save me some time.
