### ISSUE TITLE
Megabasterd descarga y luego se detiene

### ISSUE THREAD

**Issue by MaTiMeNdeZ** [tonikelope/megabasterd#205]
Hola!

Ante todo muchas gracias por esta aplicación y la dedicación que le brindas!

Mi problema reside (y quizás es el de muchos también) en que desde hace un tiempo a la fecha la aplicación deja de descargar lo que le pongas. Y pueden pasar 10 segundos o 10 días que no retoma, se queda toda la descarga congelada. ¿Sabrías qué podría ser? ¿Tendría que aplicar alguna configuración a la aplicación que desconozco?

Gracias de antemano!

NOTA: tengo la ultima versiom (7.21).

**Comment by tonikelope** [comment]
Hola. Casi seguro que es problema de los proxys. Como ya he comentado muchas veces, el problema del SmartProxy es que utiliza una lista de proxys públicos y dependiendo del momento del día esos proxys se saturan antes o después. MegaBasterd está diseñado para reanudar de forma automática las descargas cuando vuelven a funcionar (además de que tiene implementados varios mecanismos anti "congelación" que en caso de no descargar nada durante más de 5 minutos reinicia la descarga de forma automática). 

Me temo que poco más puedo hacer con el tema de los proxys. He implemtando la opción de usar una lista de proxys privada aunque la opción que yo recomiendo es usar una cuenta PRO de MEGA.

Salu2 ;)
