### ISSUE TITLE
Mi usuario/contraseña no se envía a Mega

### ISSUE THREAD

**Issue by moremorenoadan** [tonikelope/megabasterd#21]
¡Buenas!

Me han pasado esta cuenta para "contar" los errores que me da Megabasterd de vez en cuando. Disculpa si te llegan algunos más graves y éste es del montón. Aún así, ¡feliz año!

Uso Megabasterd para descargar archivos de Mega (evidentemente) y cuando he superado la cuota de Mega deja de descargar. Tengo cuenta en Mega y pongo mi usuario/contraseña en Megabasterd (y se guardan correctamente) pero a la hora de descargar, fallan.

No da un error aparente, pero salen esas rayitas y el asterisco y nunca descarga.
<img width="489" alt="megabasterd_error" src="https://user-images.githubusercontent.com/6573947/34645617-c734723a-f352-11e7-8164-27d3a9514e33.png">
Sin embargo, si es un enlace de Mega (no ELC) lo puedo descargar de mi cuenta de Mega perfectamente. Pero desde MEgabasterd, no me deja al superar la cuota (sea ELC o no).

Muchas gracias! y si necesitas más datos, pídemelos que hago las pruebas que necesites.

Un saludo y ¡gracias de nuevo!

**Comment by tonikelope** [comment]
Buenas. Para que te salga la opción de descargar usando una cuenta de MEGA, tienes que activar la opción en settings>downloads (USE MEGA ACCOUNT FOR DOWNLOAD/STREAM).

En cuanto tenga un rato quitaré esa opción porque no es intuitiva y puede dar lugar a confusión (o despiste).

Salu2 ;)
