### ISSUE TITLE
Error con Descargas/Subidas (Lista Larga)

### ISSUE THREAD

**Issue by project001-dev** [tonikelope/megabasterd#210]
Últimamente la ultima version está presentando unos errores cuando ya son los últimos archivos en cola para descargar o subir. 

Agrego un corto vídeo sobre el inconveniente: 

https://drive.google.com/open?id=1mU1IAvK1kabLBN5PhpPiEetYGDIN-lD3

Esto solo sucede cuando es una lista larga, si es corta (<100 no sucede.)

¿Como puedo activar el log? para así la próxima vez que vaya a cargar algo largo dejarlo activado y que salga el error en el log.

**Comment by tonikelope** [comment]
Hola. Pues con el vídeo no entiendo bien qué te pasa. Las transferencias tienen un mecanismo mediante el cual si no se envía o recibe ningún dato durante 5 minutos seguidos, la transferencia se resetea automáticamente. Pero no parece que sea eso lo que está pasando.

Para ver el log tienes que lanzar MegaBasterd por consola de comandos (en windows CMD.EXE). 

`java -jar MegaBasterdxxx.jar > log.txt`

**Comment by project001-dev** [comment]
> Hola. Pues con el vídeo no entiendo bien qué te pasa. Las transferencias tienen un mecanismo mediante el cual si no se envía o recibe ningún dato durante 5 minutos seguidos, la transferencia se resetea automáticamente. Pero no parece que sea eso lo que está pasando.
> 
> Para ver el log tienes que lanzar MegaBasterd por consola de comandos (en windows CMD.EXE).
> 
> `java -jar MegaBasterdxxx.jar > log.txt`

Vale, mira acá volvió a surgir el error (y eran menos de 100 archivos por subir):

[MegaBasterd.log](https://github.com/tonikelope/megabasterd/files/4335306/MegaBasterd.log)

**Comment by tonikelope** [comment]
He comprobado que los errores que te dan al final son error -4 que e sun error raro de MEGA que cuando se produce hay que reiniciar la subida entera. No hay una solución a ese error. Es aleatorio aunque bajando el número de subidas simultáneas puede mejorar.

Salu2 ;)
