### ISSUE TITLE
How to use proxies to bypass download limit

### ISSUE THREAD

**Issue by GutHib123** [tonikelope/megabasterd#211]
Can someone please tell me how to use the proxies and/or related scripts to bypass the download limit. Thanks.

**Comment by rumqye** [comment]
go to edit->setting
make sure smartproxy option was checklist
![smartproxy](https://user-images.githubusercontent.com/66983463/84838028-9c5fdb00-b063-11ea-8309-37c34383248e.jpg)

**Comment by goodstuff626** [comment]
> go to edit->setting
> make sure smartproxy option was checklist
> ![smartproxy](https://user-images.githubusercontent.com/66983463/84838028-9c5fdb00-b063-11ea-8309-37c34383248e.jpg)

What is a good website to grab the proxy list from? Do I just copy and paste the proxy list to the megabasterd settings or do I have to format/type them in a certain way for the proxy list to work?
