### ISSUE TITLE
When adding mega link, nothing happens, just hangs, shows greyed out "root" folder

### ISSUE THREAD

**Issue by goodstuff626** [tonikelope/megabasterd#212]
And the button to start the download is not showing up. Really weird because I was using it earlier tonight, and it was working fine. Then all of a sudden this started happening.

**Comment by tonikelope** [comment]
Example link?

**Comment by goodstuff626** [comment]
I'll send it to your email,

**Comment by goodstuff626** [comment]
Thank you tonikelope. Just so other people know, mega links that look like this: mega.nz/?fbclid= might not start in megabasterd, they must look like this: mega.nz/#F

**Comment by xmorhpx** [comment]
buenas alguna solucion para este problema
