### ISSUE TITLE
[IMPORTANT] New mega link format

### ISSUE THREAD

**Issue by tonikelope** [tonikelope/megabasterd#215]
MEGA has started using a new format for both file and folder links. While I'm adding support for these new links in MegaBasterd, **the temporary solution is to change them manually to the old format.** 

**FOLDER LINKS**:

NEW `https://mega.nz/folder/xxxxxxx#zzzzzzzzzzzzzzzzzzzzzz`

OLD `https://mega.nz/#F!xxxxxxx!zzzzzzzzzzzzzzzzzzzzz`

**FILE LINKS**:

NEW `https://mega.nz/file/yyyyyyy#bbbbbbbbbbbbbbbbbbb`

OLD `https://mega.nz/#!yyyyyy!bbbbbbbbbbbbbbbbbbb`

Sorry for the inconvenience.

**Comment by sauul03** [comment]
I tried to use the old format and it isn't adding the download at all, neither detecting the link copied

**Comment by Skeltom** [comment]
> 
> 
> I tried to use the old format and it isn't adding the download at all, neither detecting the link copied

It wasnt working for me eather. My problem was I forgot the second # to an !

NEW https://mega.nz/file/yyyyyyy#bbbbbbbbbbbbbbbbbbb

OLD https://mega.nz/#!yyyyyy!bbbbbbbbbbbbbbbbbbb
                                              ^

**Comment by Gladuin** [comment]
You made a mistake, the old format for folders isn't `https://mega.nz/#F!xxxxxxx#zzzzzzzzzzzzzzzzzzzzz` but `https://mega.nz/#F!xxxxxxx!zzzzzzzzzzzzzzzzzzzzz` (the second `#` needs to be an `!`)

**Comment by comixkiste** [comment]
thanks for the temporary solution!

**Comment by Morrisonuk** [comment]
Sorry if I'm being dense here. This is my first time trying to use this.

The folder links shows as below for me:
https://mega.nz/folder/xxxxxxxx/folder/zzzzzzzz

Not as: 
https://mega.nz/folder/xxxxxxx#zzzzzzzzzzzzzzzzzzzzzz

Am I looking at the wrong link?

**Comment by Nox1793** [comment]
> Sorry if I'm being dense here. This is my first time trying to use this.
> 
> The folder links shows as below for me:
> https://mega.nz/folder/xxxxxxxx/folder/zzzzzzzz
> 
> Not as:
> https://mega.nz/folder/xxxxxxx#zzzzzzzzzzzzzzzzzzzzzz
> 
> Am I looking at the wrong link?

You can follow the guidelines and remove the /folder/zzzzzzzz
the link should work.

**Comment by leo1115** [comment]
Waiting for a fix. Hopefully soon. thank you.

**Comment by gusallc** [comment]
thanks men

**Comment by ByronPiedrahita** [comment]
Example of link new https://mega.nz/folder/BopWWaID#BqJDMZNO6cTs9LHvmY958A/folder/0kIRkY7C
Change to Old
https://mega.nz/#F!BopWWaID!BqJDMZNO6cTs9LHvmY958A
And is all

**Comment by jjrrcc11** [comment]
Hello can someone help. I have the below link. The first link is unchanged, the second is what I have changed it to. However I am receiving a 'MEGA LINK ERROR' still.

https://mega.nz/folder/c5hw2IwI#VqtQS5UBITenakydqN8eUQ/file/kg5QUI5S

https://mega.nz/#F!c5hw2IwI!VqtQS5UBITenakydqN8eUQ/file/kg5QUI5S

**Comment by adekmaulana** [comment]
> Hello can someone help. I have the below link. The first link is unchanged, the second is what I have changed it to. However I am receiving a 'MEGA LINK ERROR' still.
> 
> https://mega.nz/folder/c5hw2IwI#VqtQS5UBITenakydqN8eUQ/file/kg5QUI5S
> 
> https://mega.nz/#F!c5hw2IwI!VqtQS5UBITenakydqN8eUQ/file/kg5QUI5S

https://mega.nz/#F!c5hw2IwI!VqtQS5UBITenakydqN8eUQ

**Comment by jjrrcc11** [comment]
> > Hello can someone help. I have the below link. The first link is unchanged, the second is what I have changed it to. However I am receiving a 'MEGA LINK ERROR' still.
> > https://mega.nz/folder/c5hw2IwI#VqtQS5UBITenakydqN8eUQ/file/kg5QUI5S
> > https://mega.nz/#F!c5hw2IwI!VqtQS5UBITenakydqN8eUQ/file/kg5QUI5S
> 
> https://mega.nz/#F!c5hw2IwI!VqtQS5UBITenakydqN8eUQ

Thankyou!

**Comment by cristoiroberto** [comment]
Hello,

I converted the link https://mega.nz/file/ltxFxLCT#2DEpkapJ_IEudUbyaobucq5vvuMuBuAZuA0I3gLsYeM and it shows in the app but download never starts. Why? Thanks

**Comment by KaosEstOrdo** [comment]
The Old format works 100% im gonna put an example for my case (File link):

https://mega.nz/file/3fpFmApS#sctL8FeRfGKjBpYQPD1hPrAJz1PSvQIyINte8UKRvRk

changed:

https://mega.nz/#!3fpFmApS!sctL8FeRfGKjBpYQPD1hPrAJz1PSvQIyINte8UKRvRk

Look carefully the characters to change!

Good Luck!

**Comment by KaosEstOrdo** [comment]
> Hello,
> 
> I converted the link https://mega.nz/file/ltxFxLCT#2DEpkapJ_IEudUbyaobucq5vvuMuBuAZuA0I3gLsYeM and it shows in the app but download never starts. Why? Thanks

The Old format works 100% im gonna put an example for my case (File link):

https://mega.nz/file/3fpFmApS#sctL8FeRfGKjBpYQPD1hPrAJz1PSvQIyINte8UKRvRk

changed:

https://mega.nz/#!3fpFmApS!sctL8FeRfGKjBpYQPD1hPrAJz1PSvQIyINte8UKRvRk

Look carefully the characters to change!

Good Luck!

**Comment by capsload2** [comment]
Its not working when converting to the "old" link.

NEW LINK:
https://mega.nz/folder/DRlFBYqD#wFO_-sZKQM3olcNgs4C6hg

OLD LINK:
https://mega.nz/#F!DRlFBYqD!wFO_-sZKQM3olcNgs4C6hg

```
Reading link metadata...
Oooops, something went bad. EXIT CODE (3)
```

**Comment by hamza6092** [comment]
Can someone tell me the the pasword of this megalink

**Comment by hamza311936-cmyk** [comment]
Hi

**Comment by hamza311936-cmyk** [comment]
Please opan

**Comment by rafaelcalheiros** [comment]
Hi do u have a new link??
