### ISSUE TITLE
v7.24

### ISSUE THREAD

**Issue by iamleifaa** [tonikelope/megabasterd#219]
How to speed up the download speed? My normal mega speed is 7-9mbps when i use megabasterd the speed im getting is only @11.40kb/s (sometime 5kb)

**Comment by jcm96** [comment]
I have the same problem, does anyone know how to solve it?

**Comment by iamleifaa** [comment]
The fastest speed i got on using this is i think 700kbps or something. Any fix for this? Any particular settings that we should do.
