### ISSUE TITLE
Uploads don't work?

### ISSUE THREAD

**Issue by jayt55** [tonikelope/megabasterd#22]
Can't seem to use the uploader portion. It only wants to upload extremely small files and ignores any video files or rar files I try to upload.

**Comment by tonikelope** [comment]
![screenshot_20180127_203354](https://user-images.githubusercontent.com/1344008/35475597-9ef87bcc-03a1-11e8-8786-649ed5338c01.png)

**Comment by jayt55** [comment]
I'm a windows user.

**Comment by tonikelope** [comment]
Launch It from CMD.exe using java -jar (google for more info).

Regards.

**Comment by jayt55** [comment]
Okay. I did it. It just says "0 bytes" and doesn't recognize the video file. No change.
![screenshot_1](https://user-images.githubusercontent.com/35861958/35476449-0652b734-037e-11e8-96fa-0d0cbee9446b.png)

**Comment by tonikelope** [comment]
In the CMD.exe window, are there any message? Could you paste here? I will also need the folder and file names to rule out any problems with characters that are not allowed.

Regards.

**Comment by jayt55** [comment]
No, there's nothing that comes up in the command prompt at all. As for the characters, I renamed a video file to "01" and it still just says 0 bytes. I also tried "zzz" and it still just says 0 bytes on the uploader window.

**Comment by tonikelope** [comment]
It's weird...  I can't figure out how to reproduce the error. Have you tried to move to another folder the file?

Regards.

**Comment by jayt55** [comment]
No change. I don't know what the problem is, but I hope you can figure it out.

**Comment by tonikelope** [comment]
Could you put here you OS, Java Version, antivirus, etc.?

**Comment by petrik23** [comment]
same problem on windows server 2012, how can you solve?

**Comment by axo1** [comment]
A mí tampoco me funcionan las subidas hoy, no sé si es error temporal de mega o del programa, pongo algo a subir y no aparece nada

**Comment by tonikelope** [comment]
Hola. Parece error puntual de algunos servidores de Mega porque me pasa con unas cuentas y con otras no.

Salu2 ;)

**Comment by axo1** [comment]
Era temporal sí, estoy subiendo ahora sin problemas
Saludos!

**Comment by petrik23** [comment]
![2018-02-20_081029](https://user-images.githubusercontent.com/10188662/36411454-92559e82-15ca-11e8-8f03-62ea44ecefca.png)

**Comment by tonikelope** [comment]
I added a control in version 2.95 to try to limit the error. Please download and test it to see if any error messages appear.

**Comment by axo1** [comment]
Buenas, desde ayer estoy teniendo problemas con la subida y no sé si solo me pasa a mí o es un errror temporal de mega que está fallando bastante últimamente.
Pongo algo a subir y empieza con buena velocidad pero al cabo de un rato la velocidad baja hasta que se detiene y deja de subir, he probado a bajarle los slots y nada.. 
Saludos!

**Comment by tonikelope** [comment]
Hola. Creo que estan tocando algo en MEGA porque también he notado que algunos ficheros descargan lentisimo. De todas formas, ¿puedes ejecutar desde la consola de comandos y fijarte si salta algún error durante la subida?

**Comment by axo1** [comment]
No tengo ni idea de qué comandos poner en la cmd para ejecutarlo xD
Aún así, he vuelto a probar a subir algo y vuelve a funcionar como lo hace normalmente. A ver cuanto dura esto...
Gracias por la atención, saludos!
