### ISSUE TITLE
"MEGA LINK ERROR!"

### ISSUE THREAD

**Issue by sebastianchokka** [tonikelope/megabasterd#220]
Link:
https://mega.nz/folder/pQ9zSKgD#nts_39aNUmo51f8XOLepXQ/folder/VYkzCAqD

I tried formatting it like this:
https://mega.nz/#F!pQ9zSKgD#nts_39aNUmo51f8XOLepXQ/folder/VYkzCAqD

Both don't work, what do I do?

**Comment by ByronPiedrahita** [comment]
https://mega.nz/#F!pQ9zSKgD!nts_39aNUmo51f8XOLepXQ

**Comment by capsload2** [comment]
All my Links wont work. I changed to the new format.

(for security, i removed the latest 2 letters)

https://mega.nz/#F!4QN30JgI!X5vVUrjaoKHYwaNKFnwr
https://mega.nz/#F!8REBiIYJ!YsjjlQ927T023eeachpV
https://mega.nz/#F!kQtBURZb!V4F5LFnGVrOI0g6k_1M6
https://mega.nz/#F!eNEGlDQZ!_VgGtiuMDAdg4A_4MJs3
https://mega.nz/#F!5ZckzSiR!J-aiJbSJIi39I6XoPCF
https://mega.nz/#F!RZllGQTT!rfcOUSY7leyeFmlKjvz_
https://mega.nz/#F!yvQThY7Y!-AzzHwLbTqbs8dXZy7Ap
