### ISSUE TITLE
v7.24 stuck at recognising folder

### ISSUE THREAD

**Issue by vashishtmarhwal** [tonikelope/megabasterd#223]
When I add a folder link, It gets stuck at Folder Link found and then nothing is loaded

**Comment by DJboutit** [comment]
I have been complaining for 8 month now that the program is not able to download anything inside a folder S M H.  75% of the stuff I want to download is inside folders now and I can not even get it with this program.  If only one thing is fixed over the next 4 to 8 month being able to download folders or inside folders should be #1 issue fixed.  #2 the high resource usage from the program.

**Comment by tonikelope** [comment]
Example link?

**Comment by DJboutit** [comment]
File inside a folder link https://tinyurl.com/y9bdvn27

Folder link https://tinyurl.com/yb7h23pv

**Comment by tonikelope** [comment]
https://tinyurl.com/ycq62lsy works in 7.24 (Just copy it to tclipborad and MegaBAsterd will detect it) https://mega.nz/#F!kvRVGIKY!AgB-nwqLq_2wKOUCdWgRtQ

https://tinyurl.com/y7j5jq4g Links inside folders are not supported sorry.

Regards.
