### ISSUE TITLE
Scalling issue with HiDPi (4K Resolution) Laptop

### ISSUE THREAD

**Issue by MohandL3G** [tonikelope/megabasterd#225]
I have this Toshiba Laptop with 4K Resolution, there's alot of apps that have scaling issues, most of the time I just change the "High DPI scalling override" to "System"
I have done this to MegaBasterd:
![Annotation 2020-04-26 052550](https://user-images.githubusercontent.com/31743237/80296899-e7095900-877e-11ea-8d95-1864fee8e4a2.jpg)

But with no luck it's still the same, text is so small and it's hard to read anything:
![Untitled](https://user-images.githubusercontent.com/31743237/80297217-7a438e00-8781-11ea-982c-4085e484043f.jpg)

Please can you fix this? and Thanks in Advance :)

**Comment by tonikelope** [comment]
Hi. Have you tried to increase font size on MegaBasterd advanced settings?

Regards.

**Comment by MohandL3G** [comment]
@tonikelope Yeah I tried it and it works great, I can read the text now, thanks for the suggestion 😄
