### ISSUE TITLE
Can't start a new download

### ISSUE THREAD

**Issue by Newaccount1970** [tonikelope/megabasterd#226]
After clicking the new download button nothing happens and it just turns grey.
![image](https://user-images.githubusercontent.com/64614099/80757463-7e323000-8b34-11ea-9ca4-5062e3cbe9de.png)

**Comment by tonikelope** [comment]
Is it still happening?

**Comment by Newaccount1970** [comment]
> 
> 
> Is it still happening?

Seems to work now. Will tell you if it breaks again.
