### ISSUE TITLE
v7.24 is not voiding the download limit or downloading really slow

### ISSUE THREAD

**Issue by kwikas** [tonikelope/megabasterd#227]
This is happening on a few PCs in a several regions (US, EU).
While quota is not reached - everything is fine.
As soon as quota is reached, it just can either stop, or go back and forth in a loop stopping and downloading, but _really_ slow (10 to 50KB) even on 200-300Mbps connection.
Started to see this within last week. Was OK, or just not facing prior.

Any help or advice?

Regards,

**Comment by tonikelope** [comment]
This is a topic that has been discussed at length. Unfortunately, the proxies that are used when reaching the mega limit have a completely unpredictable performance as they are public proxies.  MegaBasterd maximizes the number of download slots when using proxies to take advantage of all the bandwidth, but if by chance several slots are "trapped" in slow proxies, it will feel like the application doesn't download, when it is a matter of proxies. It's not something I can do any more.

I've said this many times before. There are 3 solutions:

1) Use a PRIVATE proxy list.

2) Use a VPN.

3) Use a MEGA PRO account.

Regards.
