### ISSUE TITLE
troyan.agent

### ISSUE THREAD

**Issue by LuckZika** [tonikelope/megabasterd#228]
Hola este ejecutable contiene un troyano.agnet que es como un backdoor ya que tiene el acceso a todos tus datos puede borrarlos,etc etc etc ni me imagino,segundo el creador de esto lo creo al parecer en linux, no estoy diciendo que todo lo que se cra en ese sistema operativo sea virus pero es una sospecha mas ya que desde ahi se pueden hacer cosas que en windos no 0/10 no lo recomiendo,a no ser que quieras un troyano

**Comment by tonikelope** [comment]
Imagino que te refieres a la versión de Windows en formato .exe creado con la herramienta http://launch4j.sourceforge.net/

El análisis anti-virus:

https://www.virustotal.com/gui/file/9bce9fdcf1c35c430e57f02e2572a67203700deaaa71755a1220e257677462e9/detection

Como puede verse en el análisis, uno de los antivirus (uno chino que no me suena de nada) da como resultado que el archivo supuestamente contiene un troyano. Bien, no digo que los chinos tengan problemas con los virus, pero creo que en este caso tiene pinta de ser un fallo del motor de análisis. 
No obstante, tenéis a vuestra disposición la versión en formato .jar que es multiplataforma y si no fuera suficiente, el código fuente completo de la aplicación.

Un saludo.

PD: como consejo para el futuro, antes de abrir un hilo así, es mejor contar hasta 20.

------------------------------------------------------------------------------------------------------------------------------


As you can see from the analysis, one of the antivirus programs (a Chinese one which is the first time I know of its existence) results in the file supposedly containing a Trojan. Well, I'm not saying that the Chinese have a problem with viruses, but I think in this case it looks like a bug in the scanning engine. 
However, you have at your disposal the .jar version which is cross-platform and if that's not enough, the complete source code of the application.

Regards.

PS: as a tip for the future, before opening such a thread, it is better to count to 20.
