### ISSUE TITLE
begin queued downloads as soon as existing downloads are finished downloading, as opposed to assembling

### ISSUE THREAD

**Issue by ewortzman** [tonikelope/megabasterd#231]
currently, a download is not considered finished until the file chunks are assembled and the file is complete.  That means that if my maximum downloads is set to 5, there can only be 5 files downloading _or_ assembling.  I think that once all the chunks for a file are done downloading, we should consider that download complete and let the next download start, and have a different type of job for assembling the file chunks. 

I don't know if this is the norm, but for me it seems that most often the "assembly" phase takes as long or longer than the download.  So I spend a lot of time with megabasterd having 5 files in the "joining file chunks" phase and nothing being pulled down from MEGA.  I think this can be improved.

**Comment by tonikelope** [comment]
Totally agree.  I implement it ASAP.

Greetings.
