### ISSUE TITLE
Uses Way To Many Resources And Takes Way To Long To Download A folder please 

### ISSUE THREAD

**Issue by DJboutit** [tonikelope/megabasterd#233]
2 most urgent  issues that need to be fixed A S A P 

Megabastered is a resource hog it uses 40% more resources than a video encoder does S M H.  My computer is not slow I have a I7 3770 and 12gb DDR 3 and this program makes computer so slow I can not really do anything elese.  I have said this like 10 times before still not even 35% better in 8 months.  

Your only allowed to link to the main folder not any sub folders or individual files lame.  It should not take 3+ hrs to download a folder with 2gb to 4gb worth of files.  On a speed test I get 550mbps down I can download 2gb to 4gb in 15min.

**Comment by Sibbs** [comment]
thats on your comp bro, (maybe virus or malware) , i have a 11 year old computer and i can even play demanding games while megabasterd runs in the background, so i dont know what to tell you
