### ISSUE TITLE
Very slow in downloading....

### ISSUE THREAD

**Issue by Lucaaaaaaaaa** [tonikelope/megabasterd#234]
My wifi is really fast. If i do a speedtest it is giving me an average of 800mb/s If i am downloading something on Torrent it is arround 70mb/s wich is reasonable but with MegaBasterd i get an average of arround 1mb/s wich is really weird. Even when i have everything closed. It also drops to arround 20kb/s and not just sometimes it does that alot. I hope there is a fix for this. I have not got any limit on the download speed. Please Help!!!

**Comment by rumqye** [comment]
it probably because of proxy, search for another proxy. If possible premium proxy, paste the proxy you found on "SmartProxy" box, then click save
megabasterd will use your own proxy instead of default proxy
