### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by xperiafan13-rom** [tonikelope/megabasterd#24]
INFORMACIÓN: pool-2-thread-1 Filewriter waiting for chunk [0]...
feb 01, 2018 3:16:51 PM megabasterd.ChunkDownloaderMono run
INFORMACIÓN: pool-2-thread-3 Worker [1]: let's do some work!
feb 01, 2018 3:16:52 PM megabasterd.ChunkDownloaderMono run
INFORMACIÓN: pool-2-thread-3 Failed : HTTP error code : 509
feb 01, 2018 3:16:55 PM megabasterd.ChunkDownloaderMono run
INFORMACIÓN: pool-2-thread-3 Failed : HTTP error code : 509
feb 01, 2018 3:16:59 PM megabasterd.ChunkDownloaderMono run
INFORMACIÓN: pool-2-thread-3 Failed : HTTP error code : 509
feb 01, 2018 3:17:08 PM megabasterd.ChunkDownloaderMono run
INFORMACIÓN: pool-2-thread-3 Failed : HTTP error code : 509

**Comment by tonikelope** [comment]
Just two notes:

1) Try enabling MULTI-SLOT in download settings (this allow to start downloading "big" files).

2) Mega has a bandwidth limit. When you reach it, it gives 509 error and you have to wait a couple of hours to continue the download.

Regards.
