### ISSUE TITLE
In the newest version 7.28- "Use Smartproxy" in the settings is disabled by defualt. Why?

### ISSUE THREAD

**Issue by goodstuff626** [tonikelope/megabasterd#240]
Should I enable it to keep downloading over limit? I'm just confused because every release before this one it was always "On" by default. Thanks for any info.

**Comment by Sibbs** [comment]
he probably got sick of keeping the proxy list updated all the time, unless he found a way to automate that, i agree a terrible feature removal

**Comment by Skeltom** [comment]
Am i mistaken, of dose this mean it no longer bypass the bandwidth limit? It hasn't for me since 7.27.

**Comment by tonikelope** [comment]
> Am i mistaken, of dose this mean it no longer bypass the bandwidth limit? It hasn't for me since 7.27.

The SmartProxy functionality is still active but you will need to get a list of proxies to use on your own.

Greetings.
