### ISSUE TITLE
SmartProxy not work with user:pass

### ISSUE THREAD

**Issue by MFI96** [tonikelope/megabasterd#241]
I tried it in 3 ways. however, it does not accept more than 1000 my proxies. Download not started. Now using proxifier for change proxy. But If you add support I will happy.

example 1 : fi104.nordvpn.com:80:[bwillsboys@sbcglobal.net:seanolan]
example 2 : cz93.nordvpn.com:80:[@wspburt@outlook.com:william1]
example 3 : cz106.nordvpn.com:80:asthenia1111@gmail.com:atataka1

Can you add support for this because more easily : cz106.nordvpn.com:80:asthenia1111@gmail.com:atataka1
ip:port:username:pass
this is more very easily please add new version

Thanks for your program.

If my bad please say me how should add thanks

**Comment by tonikelope** [comment]
The format for proxies with username and password is as follows:

Example for user "**bob**" with pass "**1234567890**":

`proxy1.blablabla.com:80@Ym9i:MTIzNDU2Nzg5MA==`

Here you can encode your proxy user and password in BASE64:

https://codebeautify.org/base64-encode

Regards.
