### ISSUE TITLE
Not continue downloading

### ISSUE THREAD

**Issue by Otakulihao** [tonikelope/megabasterd#242]
Hi, the program stops for example in 188mb and doesn't continue
[megabasterd_DEBUG.log](https://github.com/tonikelope/megabasterd/files/4875561/megabasterd_DEBUG.log)

**Comment by Zeincrath** [comment]
He Otakuliaho, bañate primero, and the same problem happened to me!. the program Megabastererd doesn't work, it does the same thing like mega, it stops and I have to wait like 12 hours to download again.
Some ideas to fix this??

**Comment by Richie-M** [comment]
same issue :(

**Comment by Otakulihao** [comment]
51.254.35.77:8080
212.83.153.143:5836
163.172.168.124:3128
88.198.90.23:3128
189.203.74.143:3128
188.170.233.98:3128
188.170.233.106:3128
212.83.153.143:5836	
163.172.168.124:3128
88.198.90.23:3128
188.213.31.73:808
51.68.207.81:80
85.111.62.162:3128
90.188.255.99:8118
178.63.246.83:8118
212.83.152.105:5836
188.170.233.104:3128
188.170.233.110:3128
13.250.44.105:8888

**Comment by ConorsFlying** [comment]
I noticed the patch notes said "Internal proxy list deactivated". And I'm assuming that list of addresses is used to solve this. Where to I put the proxy list? I tried putting it in the text box for the "use smart proxy" feature but it still doesn't download anything for long.

**Comment by Richie-M** [comment]
i'm using my own proxies so it isnt that
