### ISSUE TITLE
7.28 not downloading past 5gb limit anymore, tried adding proxy list to smartproxy, does nothing

### ISSUE THREAD

**Issue by goodstuff626** [tonikelope/megabasterd#244]
Megabasterd 7.28 has been working fine for me, up until today, it is not going past 5gb download limit. I added proxy list but it does not seem to be working. Is there a detailed write up on how to properly add a proxy list to smartproxy so I know I'm doing it right?

**Comment by johnnyspork** [comment]
The only solution I've found is to use a VPN, switch servers every 5gb, and restart MegaBasterd. Every time you do that you get another 5gb and it cuts off, but at least it works.

**Comment by Filaipus** [comment]
This is kind of weird since this is basically the only reason to use MegaBasterd no? Otherwise might as well use MegaSync or Jdownloader. Hope it gets fixed.

**Comment by goodstuff626** [comment]
> @goodstuff626 The only solution I've found is to use a VPN, switch servers every 5gb, and restart MegaBasterd. Every time you do that you get another 5gb and it cuts off, but at least it works. Also, see the comments on this issue for a way to restore the old proxy list to the app: #245

Hey, thanks for the info johnnyspork. I followed the link there and added the proxies. I used megabasterd today and it downloaded a 10gb megalink no problem, so I was very happy thinking it was finally working again. Then about an hour later I went to download a 1gb file, and megabasterd would not start at all. Same proxies and everything, so I have no idea what is going on with this program. Hopefully there will be a 7.29 update that fixes everything.

**Comment by goodstuff626** [comment]
Actually the 1gb file all of a sudden in megabasterd just said something like, "cancelling download... cancelled download, watchdog service detected" or something weird like that. I've never seen megabasterd throw out a message like that lol.

**Comment by goodstuff626** [comment]
Ok, I think I got it working again. I saw the recent updates to the proxy list located here - https://github.com/tonikelope/megabasterd/blob/proxy_list/proxy.txt
Added them to the settings, and it seems to be downloading past 5gb limit like it should. I do think that a link to the proxy list should be added to main page and explained that they need to be added so there is not so much confusion how to get this program to work.

**Comment by JPHFanedits** [comment]
> 
> 
> Ok, I think I got it working again. I saw the recent updates to the proxy list located here - https://github.com/tonikelope/megabasterd/blob/proxy_list/proxy.txt
> 
> Edit- I now realize that, in order to make this program work, everytime I use it I need to update the proxy list with the newest proxies otherwise it stalls.

And how does one go about doing this??
Asking for a friend (c;

**Comment by RohanTrix** [comment]
> Ok, I think I got it working again. I saw the recent updates to the proxy list located here - https://github.com/tonikelope/megabasterd/blob/proxy_list/proxy.txt
> 
> Edit- I now realize that, in order to make this program work, everytime I use it I need to update the proxy list with the newest proxies otherwise it stalls.

Please elaborate how to do this.

**Comment by JPHFanedits** [comment]
> > Ok, I think I got it working again. I saw the recent updates to the proxy list located here - https://github.com/tonikelope/megabasterd/blob/proxy_list/proxy.txt
> > Edit- I now realize that, in order to make this program work, everytime I use it I need to update the proxy list with the newest proxies otherwise it stalls.
> 
> Please elaborate how to do this.

Copy all of the numbers listed in the proxy list and paste them in the proxy server list in the settings

**Comment by piyushk2000** [comment]
https://www.youtube.com/watch?v=Atv--DPDc4k&ab_channel=LloydTutorial
watch this video it has link in the discription where you can copy latest proxys from

**Comment by NIV54** [comment]
Having the same issue here. Updated the proxy list, but still nothing seems to download past 5GB.
