### ISSUE TITLE
Need smartproxy list

### ISSUE THREAD

**Issue by dheeraj92** [tonikelope/megabasterd#245]
Can anyone share smartproxy list from which we can bypass download limit

**Comment by baranduins** [comment]
https://archive.is/20191015070923/https://raw.githubusercontent.com/tonikelope/megabasterd/proxy_list/proxy_list.txt
Here's an archive of the old megabasterd proxy list. They still seem to work, but otherwise if you search any of those it brings up similar lists/sites.

**Comment by johnnyspork** [comment]
The only solution I've found is to use a VPN, switch servers every 5gb, and restart MegaBasterd. Every time you do that you get another 5gb and it cuts off, but at least it works. Thanks @baranduins I'm going to try that archived proxy list and see if that restores MegaBasterd's normal behavior.

**Comment by dheeraj92** [comment]
Thanks guys

**Comment by Robthekilla** [comment]
which vpn johnnyspork?

**Comment by gateremark** [comment]
> The only solution I've found is to use a VPN, switch servers every 5gb, and restart MegaBasterd. Every time you do that you get another 5gb and it cuts off, but at least it works. Thanks @baranduins I'm going to try that archived proxy list and see if that restores MegaBasterd's normal behavior.

Which VPN @johnnyspork ?

**Comment by johnnyspork** [comment]
I haven't been on this thread in over two years folks, please stop asking.
I have no idea which one I was using back then, and nowadays i just use
free public proxy lists if the ones on the github stop working for any
reason and that seems to work fine.

**Comment by Goldmaster** [comment]
for anyone having issues https://privatebin.net/?31e990a2c871515d#13S9LTayW5WJzpZu6VoPsc4sociZE6zehxPztfx3SSFs

**Comment by tonikelope** [comment]
Third party non tested https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/http.txt

**Comment by petesimon** [comment]
> Third party non tested https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/http.txt

alternate link but the same list, and it is updated everyday
https://github.com/TheSpeedX/PROXY-List/raw/refs/heads/master/http.txt
