### ISSUE TITLE
How to start the download?

### ISSUE THREAD

**Issue by CloudHaze** [tonikelope/megabasterd#247]
I was downloading an office 2010, I press pause/all 
And now there is not such a button to (start/resume) the download

Also I enable (smart proxy) but i didn't put any code there, just a blank box.  Of course i have a nord vpn but i didn't activate
So i just put the mega file here and press (lets go baby or something) XD to start the download , but now i just by curiosity pressed (paused/all) but there is not resume button :D
![smart](https://user-images.githubusercontent.com/19179554/89561641-ccfffd80-d7e6-11ea-82cb-57ae8a397f12.png)

**Comment by DJboutit** [comment]
I think the proxy site the program was using is no more so the program will not run downloads any more.

**Comment by DJboutit** [comment]
I think the proxy site the program was using is no more so the program will not run downloads any more.

**Comment by DJboutit** [comment]
I think the proxy site the program was using is no more so the program will not run downloads any more.

**Comment by DJboutit** [comment]
I think the proxy site the program was using is no more so the program will not run downloads any more.
