### ISSUE TITLE
No Descarga

### ISSUE THREAD

**Issue by poncho10101** [tonikelope/megabasterd#25]
Al intentar descargar un archivo de Mega esta no empieza se queda en 0 B
![captura de pantalla 2018-02-28 a la s 11 22 31](https://user-images.githubusercontent.com/15071421/36805171-ea21cacc-1c79-11e8-9899-3544e797c663.png)

La consola muestra esta información:
![captura de pantalla 2018-02-28 a la s 11 24 44](https://user-images.githubusercontent.com/15071421/36805206-0cad14de-1c7a-11e8-9073-67838406000e.png)

**Comment by tonikelope** [comment]
¿Te ocurre con todos los links? Necesitaría el enlace que no te descarga para hacer pruebas, porque es raro ya que no sale ningún error (podría ser saturación puntual de MEGA que desgraciadamente pasa bastante).

Salu2 ;)
