### ISSUE TITLE
Downloads stop abruptly

### ISSUE THREAD

**Issue by MReprogle1** [tonikelope/megabasterd#251]
This might be somewhat related to issue [242](https://github.com/tonikelope/megabasterd/issues/242) but I can't be sure since they are using proxy lists. I have been using this app on Windows for quite some time now and have had no issues on the Windows side, but just set it up in Linux Mint 20 and have a strange issue where the downloads start and run at full speed, then just stop and don't start again until I close the application and allow it to stop transferences safely, then re-open. Sometimes, I have to close it again if it closed too fast the first time, which makes me thinks that it sometimes stops abruptly on its own.

Again, I am using no proxy list and am using a premium account to download with, and am saving to a local temp cache, then to my NAS.

**Comment by tonikelope** [comment]
Please paste debug file.

**Comment by tonikelope** [comment]
Please send me debug file.

**Comment by MReprogle1** [comment]
Sorry, there is a ton here because I kept trying to close then open. Right now, even after a restart, it won't start downloads at all.  I will warn you - I am a total Linux newbie that is trying to slowly migrate everything over, so this might be user error as well.

>LinuxOpenJDK 64-Bit Server VM 11.0.7 /app/jre
Sep 09, 2020 11:35:10 AM com.tonikelope.megabasterd.MainPanel main
INFO: main Waiting 1 seconds before start...
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkWriterManager run
INFO: pool-3-thread-2 ChunkWriterManager: lets do some work! {1}
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkWriterManager run
INFO: pool-3-thread-2 ChunkWriterManager LAST CHUNK WRITTEN -> [348] 3,579,314,176 download1.mkv...
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkWriterManager run
INFO: pool-3-thread-2 ChunkWriterManager waiting for chunk [349] download1.mkv...
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-8 Worker [6]: let's do some work! download2.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-7 Worker [5]: let's do some work! download2.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-5 Worker [3]: let's do some work! download2.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-4 Worker [2]: let's do some work! download2.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-2-thread-8 Worker [6]: let's do some work! download3.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-3 Worker [1]: let's do some work! download2.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-3-thread-3 Worker [1]: let's do some work! download1.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-2-thread-3 Worker [1]: let's do some work! download3.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-2-thread-5 Worker [3]: let's do some work! download3.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-2-thread-4 Worker [2]: let's do some work! download3.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-2-thread-6 Worker [4]: let's do some work! download3.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-2-thread-7 Worker [5]: let's do some work! download3.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkWriterManager run
INFO: pool-2-thread-2 ChunkWriterManager: lets do some work! {1}
Sep 09, 2020 11:35:15 AM com.tonikelope.megabasterd.ChunkWriterManager run
INFO: pool-2-thread-2 ChunkWriterManager LAST CHUNK WRITTEN -> [384] 3,956,801,536 download3.mkv...
Sep 09, 2020 11:35:15 AM com.tonikelope.megabasterd.ChunkWriterManager run
INFO: pool-2-thread-2 ChunkWriterManager waiting for chunk [385] download3.mkv...
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ProgressMeter run
INFO: pool-4-thread-1 ProgressMeter hello! download2.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ProgressMeter run
INFO: pool-2-thread-1 ProgressMeter hello! download3.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkWriterManager run
INFO: pool-4-thread-2 ChunkWriterManager: lets do some work! {1}
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ProgressMeter run
INFO: pool-3-thread-1 ProgressMeter hello! download1.mkv
Sep 09, 2020 11:35:15 AM com.tonikelope.megabasterd.ChunkWriterManager run
INFO: pool-4-thread-2 ChunkWriterManager LAST CHUNK WRITTEN -> [213] 2,163,736,576 download2.mkv...
Sep 09, 2020 11:35:15 AM com.tonikelope.megabasterd.ChunkWriterManager run
INFO: pool-4-thread-2 ChunkWriterManager waiting for chunk [214] download2.mkv...
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-3-thread-4 Worker [2]: let's do some work! download1.mkv
Sep 09, 2020 11:35:15 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-3-thread-8 Worker [6]: let's do some work! download1.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-6 Worker [4]: let's do some work! download2.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-3-thread-7 Worker [5]: let's do some work! download1.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-3-thread-6 Worker [4]: let's do some work! download1.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-3-thread-5 Worker [3]: let's do some work! download1.mkv
Sep 09, 2020 11:35:14 AM com.tonikelope.megabasterd.Download lambda$run$7
INFO: pool-1-thread-9 PROGRESS WATCHDOG HELLO!
Sep 09, 2020 11:35:15 AM com.tonikelope.megabasterd.Download lambda$run$7
INFO: pool-1-thread-12 PROGRESS WATCHDOG HELLO!
Sep 09, 2020 11:35:15 AM com.tonikelope.megabasterd.Download lambda$run$7
INFO: pool-1-thread-15 PROGRESS WATCHDOG HELLO!

**Comment by tonikelope** [comment]
Please paste full file https://pastebin.com/
