### ISSUE TITLE
Comando a utilizar cuando se alcanza el límite de descargas

### ISSUE THREAD

**Issue by joaquinblas** [tonikelope/megabasterd#256]
Buenas, he visto que en ajustes/AVANZADO, está la opción de ejecutar un comando cuando el limite de descarga alcanza el límite, ¿nos puedes ayudar con este tipo de comandos?

una vez que se alcanza el límite se para y no vuelve a descargar hasta que se reauna el limite a las 5 horas, 

Gracias

**Comment by tonikelope** [comment]
Hola. La idea de esa opción es poner la ruta completa a algún ejetubale que por ejemplo resetee tu router para cambiar de IP o bien active una VPN para cambiar tu IP. Al ser comandos ajenos a MegaBasterd no puedo ayudarte más. Depende de lo que cada uno tenga instalado en su equipo.
