### ISSUE TITLE
Unstable numbering/file sorting

### ISSUE THREAD

**Issue by jimsy3** [tonikelope/megabasterd#258]
hi

this is quite nice app, but can you make it to sort the files a bit normal way?
if i want to download part01-part12.rar files etc, then it always starts to download totally random file/number, instead of resuming the one that was already downloaded the most before the app was quit - so if 2GB part01.rar was already downloaded 1.98GB and you quit the app to do something else, the app will later start downloading part09.rar or smth from the very beginning, instead of finishing the 1.98GB file first... so in the end you will just end up with all of the files downloaded into 1.98GB size etc...

this issue can't even be fixed by trying to pause the randomly picked files, because the app will just pick totally random files again later and you have to pause them all before quitting anyway.... so there is no way to fix the issue, unless you sit behind the Pc 24/7 and sort them out manually every time (via "send to top" and "max current downloads" etc...)

**Comment by tonikelope** [comment]
Hi. When you add a list of files to download they are sorted alphabetically. If you re-sort them and close the program, the order of the downloads that were running is saved. If not reordered, the order of the downloads when reopened will be the normal alphabetical order. What you want is for MegaBasterd to sort the downloads when reopening the program by descending download percentage ignoring the order that was preserved when closing the program?

**Comment by jimsy3** [comment]
no, i only have to reorder them, because it usually puts the smallest number file at the end somewhere(not to the last position, but really far down the list) and then i have to push it back up via the "send to top", "max current downloads" and "pause download" etc.... and after i want to quite again, i choose "pause all" and then wait for that safe exit to close the program down.
and when i reopen the program, it picks totally random files again to start them all from the beginning, while all of the other most-downloaded files are put at the ends somewhere again...

**Comment by tonikelope** [comment]
The normal behavior when you add a list of downloads such as part1.rar, part2.rar, etc. is to put them in alphabetical order in descending order (starting with part1.rar) What you say does not correspond to the normal behavior or you have found a bug Can you record your screen?

**Comment by jimsy3** [comment]
well, it already started with the 7.28 version(my first version) and continued with the separate 7.29.jar file, but later i can try the portable 7.29 version, because i probably want to finish these files first to avoid any possible chunk size issues on top of that or smth....
