### ISSUE TITLE
Problem with version 7.29

### ISSUE THREAD

**Issue by fabricio81** [tonikelope/megabasterd#259]
Hi, i got an issue with the new version 7.29, i was using without problems the version 7.28, when the new came i erased the 7.28 and replaced it for 7.29 as i did always with past versions and new releases, i started the program, i configured the options as always, initiated new downloads links, but then when links were trying to be recognized without success, this message is showed:
Mega/MC apiException error Mega Api Error:-9 
This happens with every link i try to download, btw i'm using the portable version for Windows in Windows 7 64 bits, but i tried the 32 bits version too, something funny is that i tried to back to version 7.28 but now that has the same problem, i hope someone could help me with this problem, i'll be very grateful with any help, thanks for read me and greatings.
P.D. excuse my english, it isn't my first language.

**Comment by tonikelope** [comment]
Example link?

**Comment by Robthekilla** [comment]
i get same error 
![image](https://user-images.githubusercontent.com/91676282/175930988-81b7fd84-6169-46b3-adbf-504ad0640b1f.png)
