### ISSUE TITLE
Error al aprovisionar

### ISSUE THREAD

**Issue by DrW3b** [tonikelope/megabasterd#26]
Este es el mensaje que obtengo cuando intento subir un archivo en Windows

**Comment by tonikelope** [comment]
Hola. ¿Con qué versión de MegaBasterd te ocurre? ¿Versión de Windows? ¿Te pasa con algún fichero en concreto o con todos? ¿Te pasa al subir a otra cuenta distinta? Podría ser un problema de permisos del fichero que quieres subir... ¿Te pasa si ejecutas MegaBasterd como administrador?

**Comment by DrW3b** [comment]
Fallo mío. El .jar si funciona, ha sido al convertirlo a .exe con launch4j T_T

**Comment by tonikelope** [comment]
OK
