### ISSUE TITLE
Problem uploading with 7.29

### ISSUE THREAD

**Issue by fluxthings** [tonikelope/megabasterd#260]
Since I upgraded to 7.29 a few days ago I have not been able to use megabasterd to upload any files. As soon as I press "let's dance, baby," the file grabber goes away as usual but nothing else happens - none of the files show up and nothing uploads. I thought it may be something to do with my VPN but the same thing happens with or without that on. I am using Windows Portable.

**Comment by tonikelope** [comment]
Hi. Could you paste here the ..MEGABASTERD_DEBUG file that is generated in your user folder?

**Comment by fluxthings** [comment]
not sure how to attach a file but here's what it reads:
"Windows 10Java HotSpot(TM) 64-Bit Server VM 15.0.1 C:\Program Files\Java\jdk-15.0.1"

**Comment by fluxthings** [comment]
[.MEGABASTERD_DEBUG.log](https://github.com/tonikelope/megabasterd/files/5461525/default.MEGABASTERD_DEBUG.log)

**Comment by tonikelope** [comment]
Hi. Looking at that file is weird, because the portable version includes Java 14, not Java15. Are you sure you are using this version?

https://github.com/tonikelope/megabasterd/releases/download/v7.29/MegaBasterdWINDOWS_7.29_portable.zip

The one loaded through the .bat file?

**Comment by fluxthings** [comment]
that's definitely the version I'm using but I had some trouble opening the program so I downloaded java myself, which may be why I have Java15. should I maybe just delete everything and try to re-download?

**Comment by tonikelope** [comment]
I recommend you to try to run the portable version from the .bat file. 

If you have problems, another option is to uninstall Java 15 and install Java 14 -> 
https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jre_x64_windows_hotspot_14.0.2_12.msi

**Comment by fluxthings** [comment]
thank you, will do!

**Comment by fluxthings** [comment]
this worked, thanks so much for the help!
