### ISSUE TITLE
IO Error for 7.29

### ISSUE THREAD

**Issue by ZeroShadowX** [tonikelope/megabasterd#261]
Tried to download after updating to 7.29 and ran into this problem where the file being downloaded is not saving correctly. 

A IO error is being created where the file is saving (for example) C:\User\Downloads\/file_name instead of as it has been doing C:\User\Downloads\file_name. 

At the end of the IO error I also see (The filename, directory name, or volume label syntax is incorrect) which makes sense as thats not a proper file directory structure.  

I updated from 7.28 and reset Mega and no change. 
Changed my directory path. No Change 
Went back to 7.28 and now the probably presents itself there. 
Deleted all Mega files in User Profiles. No Change 

Have replicated this one two different mega accounts I was downloading from.

Example of errors. 
[https://ibb.co/fN4jHPQ](url)
[https://ibb.co/Kh7X2GD](url)

Hope this helps, if you need anymore info please let me know.

**Comment by tonikelope** [comment]
Could you paste the link?

**Comment by ZeroShadowX** [comment]
Here is the link

https://mega.nz/folder/yyp3WYYA#PXhj1KCburx3PYJKD59j7w

Sorry I forgot to mentioned I tried 32bit portable and the main portable just in case and the results were the same for both. 

I did not update my java so that might be the issue I can test that next if you need me too.
