### ISSUE TITLE
Download is slower than dirt 

### ISSUE THREAD

**Issue by DJboutit** [tonikelope/megabasterd#266]
Version 7.30 has the slowest download speed on any version I have used it should not take 18hrs to download a 2gb file.  My real download speed is 30mbps too 35mbps so I should getting 4mbps+.  I think these proxies this program is using are slower than dirt.  Please fix the download speed it is way to slow.

**Comment by gorcbj** [comment]
Having a similar problem here. Using an older version doesn't seem to help, I tried 7.28 and 7.29 and they had the same issue. Download starts and then speed plummets after a few seconds.
