### ISSUE TITLE
Download not starting

### ISSUE THREAD

**Issue by M-Ivan** [tonikelope/megabasterd#268]
Self explainatory tittle, a few links download (daily limit) and whenever (i assume) my account hits the dailly cap downloads never start, it freezes in something like this, it's been happening since i started using it, please tell me if im doing something wrong, i also uploaded a bunch of proxys on the smart proxys option:  
![image](https://user-images.githubusercontent.com/72365253/99214042-f4834080-27ad-11eb-938a-447873b7cfab.png)

**Comment by DJboutit** [comment]
For me when I hit 5gb it takes to long to search for another proxy to use S M H.  When I am downloading a 20gb It will take like 24hrs to download it way to long to search for proxies then new proxy site the program is slow garbage.
