### ISSUE TITLE
Mega Link Error

### ISSUE THREAD

**Issue by dead1309** [tonikelope/megabasterd#271]
Just as title said below are the link to said folder and image of the error.

![image](https://user-images.githubusercontent.com/52333483/99617641-57aae800-29e5-11eb-8744-e991c1fbd144.png)
https://mega.nz/folder/VE9kwaqK#hM_gSrbvSrRPClEWCbCoYA/folder/VNk3EYBR

**Comment by tonikelope** [comment]
Try this link:

https://mega.nz/folder/VE9kwaqK#hM_gSrbvSrRPClEWCbCoYA

or the legacy format:

https://mega.nz/#F!VE9kwaqK!hM_gSrbvSrRPClEWCbCoYA
