### ISSUE TITLE
[BUG] I'm stuck at 0% even after an hour

### ISSUE THREAD

**Issue by Katylar** [tonikelope/megabasterd#272]
Whenever I try to download, I get stuck with this screen (been at it for over an hour):

![image](https://user-images.githubusercontent.com/12586726/99775965-1e8c8800-2b4b-11eb-97a8-bcdee3f20d2e.png)

**Comment by PhotoGuy87** [comment]
I'm having a similar issue, yesterday it was stuck on 0% for over an hour as well. Then this morning it started working but now it is stuck at 5.02%. Hopefully this is a simple fix.

![image](https://user-images.githubusercontent.com/51462533/99881405-53e2b580-2bdf-11eb-8071-992288d87ce9.png)

**Comment by AviatorTrainman** [comment]
I have this same issue, but only with certain downloads, downloads which still work when downloading directly in the browser. Eventually, it cancels itself, says something about a watchdog timeout error, then restarts.

**Comment by 111125** [comment]
SAME PROBLEM!!!

**Comment by alirioGomez41** [comment]
I also have the same problem! :'c  any solution?

**Comment by Rejected-Peice** [comment]
Same here.
If I try to download the file frm the mega website, it says bandwidth limit exeeded :(
