### ISSUE TITLE
Downloads stuck on "Provisioning download, please wait..."

### ISSUE THREAD

**Issue by Volluris** [tonikelope/megabasterd#273]
As per the title, anything I try to download on version 7.30 give the error in the title.

![image](https://user-images.githubusercontent.com/74924989/99992982-f56c3180-2dae-11eb-8b61-eda4c5a853f0.png)

**Comment by tonikelope** [comment]
Java version? Are you using JAR or portable version? Could you paste .megabaster log file (it is in your windows user folder).
