### ISSUE TITLE
Not working for me (Not downloading more than 5 GB a day)

### ISSUE THREAD

**Issue by Rejected-Peice** [tonikelope/megabasterd#274]
I did not change any settings,
It was working fine 3 days ago.
Now the app is not downloading more than 5 GB a day.
When I go to the official mega site, it says your IP has used up the transfer quota.

**Comment by caafurcias42** [comment]
same here

**Comment by a8underscore** [comment]
go to settings and enable smart proxy

**Comment by SnailMango** [comment]
Same for me
