### ISSUE TITLE
Cannot even start up it.

### ISSUE THREAD

**Issue by CoCo1107** [tonikelope/megabasterd#276]
sorry to ask but i cannot even open it up.
I make sure to update and download the java but the "He Paved the way" sign showed up and vanished.
Nothing happens and nothing start up. i am very lost.
i tried previous version and tried different both windows version.
i tried for 2 hours now and the only solution left for me is to seek help here or just give up and stick with vpn and the limit cap.

https://imgur.com/Pvd6XUW
this flashed for a second and nothing happen. There seems to be quite many people suffer this too?

**Comment by tonikelope** [comment]
I recommend you to try PORTABLE VERSION or JAR version with Java 14 

https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jre_x64_windows_hotspot_14.0.2_12.msi
