### ISSUE TITLE
Apple Silicon support?

### ISSUE THREAD

**Issue by alexanderzuckerman** [tonikelope/megabasterd#277]
Currently Using Azul's build of OpenJDK for Mac and unable to launch the application.

**Comment by tonikelope** [comment]
Hi! This is something very off-topic that does not depend on me logically. What error or problem do you have running MegaBasterd with the Azul's JDK? Have you tried different Azul JDK versions? 

I imagine that as Apple Silicon expands the support for Java applications will be much better given the amount of applications in the market that work with this programming language.

**Comment by doobersn** [comment]
> Currently Using Azul's build of OpenJDK for Mac and unable to launch the application.

Did you ever find a workaround for this? I was able to get the splash screen to show but then get a java error.
