### ISSUE TITLE
Problema en Descargas

### ISSUE THREAD

**Issue by luisr1vas** [tonikelope/megabasterd#282]
Hola! la version va perfectamente tanto en optimización y demás, sin embargo hay ciertos errores con las descargas (no uso proxy, es una cuenta Premium de MEGA).

NOTA: Estoy usando slots a 6 y descargas paralelas 2.

Dejo capturas de pantalla sobre los inconvenientes:

El primer error es este, salta este error y luego reinicia la descarga (partiendo donde quedó).

![image](https://user-images.githubusercontent.com/38728192/103508065-74349f80-4e2e-11eb-9438-44383d656204.png)

![image](https://user-images.githubusercontent.com/38728192/103507601-90840c80-4e2d-11eb-9fe2-5fa46839f283.png)

(Y luego vuelve a agregarse a la cola para volver a intentarse y así terminar la descarga)

![image](https://user-images.githubusercontent.com/38728192/103507655-ab568100-4e2d-11eb-8dd2-dd7e05eb7048.png)

El siguiente error es que a veces se tascan las descargas al completarse y quedan ahí para siempre, asi sea que cierre el megabasterd y lo vuelva a abrir las descargas nuevamente comienzan donde quedaron sin embargo nunca se finalizan.

PD: Pensaba que podía deberse al disco duro (la carencia de velocidad para unir los chunks) ya que anteriormente descargaba a uno normal, sin embargo ahora se descarga a un disco NAS y pasa absolutamente lo mismo.

![image](https://user-images.githubusercontent.com/38728192/103507769-e6f14b00-4e2d-11eb-89ac-787c0133f1cf.png)

-----

![image](https://user-images.githubusercontent.com/38728192/103507883-199b4380-4e2e-11eb-96e1-8babcc5cb5d1.png)

Agrego el archivo debug:

[MEGABASTERD_DEBUG (2).log](https://github.com/tonikelope/megabasterd/files/5763398/MEGABASTERD_DEBUG.2.log)

**Comment by tonikelope** [comment]
A ver si hay suerte.

**Comment by project001-dev** [comment]
> A ver si hay suerte y se soluciona así.

¡Perfecto! hasta el momento va bien y se han descargado más de 500 archivos y ya no crea el poco de carpetas de chunks.

![image](https://user-images.githubusercontent.com/57238150/103599636-97655a80-4ed3-11eb-88bf-143127ec0e16.png)
