### ISSUE TITLE
Megadownload 7.38 - Pausing download.... how can I resume?

### ISSUE THREAD

**Issue by LRNGCODE** [tonikelope/megabasterd#283]
The file says "pausing download...." .. There's no option for me to resume download for that file. Help!

![pausing](https://user-images.githubusercontent.com/22135961/103590339-6fa9ce80-4ea2-11eb-9a7f-e2c451ad4861.png)

**Comment by tonikelope** [comment]
Pause a download is not an instantaneous process. It is necessary that each of the slots finishes downloading the current chunk (20MB each). Until all the slots have been paused, the button to resume the download will not be activated.

**Comment by jcpboho** [comment]
Thank you very much for the application.
I believe that when the limit is reached, and pauses are desired, the de-energize button never appears

**Comment by jcpboho** [comment]
> The file says "pausing download...." .. There's no option for me to resume download for that file. Help!
> 
> ![pausing](https://user-images.githubusercontent.com/22135961/103590339-6fa9ce80-4ea2-11eb-9a7f-e2c451ad4861.png)

This happened to the partner, it does not appear since I reached the discharge limit
