### ISSUE TITLE
Accessing the Mega API Key

### ISSUE THREAD

**Issue by crazyfoot092** [tonikelope/megabasterd#287]
I just downloaded Megabasterd version 7.40 and a initial popup asks to input a Mega API Key in the advanced settings. I have looked at the page and I am not sure what I am looking for when it comes to finding the Key.

**Comment by sparx058** [comment]
I just downloaded it and got the same popup. It seems its just a suggestion/optional?

**Comment by crazyfoot092** [comment]
Yeah, I figured it out, when you go to the download page for Megabasterd, it shows you how to get access to the key
