### ISSUE TITLE
Error Registering download: [SQLITE_CORRUPT] The Database disk image malformed (Database disk image malformed)

### ISSUE THREAD

**Issue by rampradhan64** [tonikelope/megabasterd#288]
Error Registering download: [SQLITE_CORRUPT] The Database disk image malformed (Database disk image malformed)

Plz Help Me

![Capture](https://user-images.githubusercontent.com/37468193/106469414-3f674700-64c5-11eb-8f5d-9f4cf83967c2.PNG)

**Comment by 0-MegaMind-0** [comment]
try to just relaunch the app if it still fails would need the db file with log to debug it.

or You could just delete the folder `C:\Users\<your_user_name>\.megabasterd7.40` and relaunch the app which will reset the app and create a new db file (i think there is a reset option inside the app too haven't tested what it does but you can try that too)

**Comment by alvadyzaa** [comment]
how to fix this in linux?
