### ISSUE TITLE
Can't download anymore.

### ISSUE THREAD

**Issue by AnonymeKing** [tonikelope/megabasterd#289]
Hi, i don't why but the app stop downloading. It's been 4 hours now
![image](https://user-images.githubusercontent.com/78452773/106677068-5cc90d80-65b8-11eb-9f3a-fd7e2a782e5f.png)

**Comment by DJboutit** [comment]
Same problem here the program was downloading files last today will not download jack.   Looks like all the proxies are dead again time to switch to premium proxies that cost a few $$ a month if you took donations for the premium proxies a few users would chip in a few $$ every few months.

**Comment by 0-MegaMind-0** [comment]
> if you took donations for the premium proxies a few users would chip in a few $$ every few months.

this just wouldn't work since if those premium proxies were shared among all the users. Any user can max out the daily limit on all the proxies and just leave others hanging dry

**Comment by DJboutit** [comment]
> 
> 
> > if you took donations for the premium proxies a few users would chip in a few $$ every few months.
> 
> this just wouldn't work since if those premium proxies were shared among all the users. Any user can max out the daily limit on all the proxies and just leave others hanging dry

There is a few premium proxy services that give you unlimited bandwidth https://proxyscrape.com/premium here is one service that has them 2500 to 5000 proxies should be enough for every 5 to 6 1/2 hrs

**Comment by 0-MegaMind-0** [comment]
> > > if you took donations for the premium proxies a few users would chip in a few $$ every few months.
> > 
> > 
> > this just wouldn't work since if those premium proxies were shared among all the users. Any user can max out the daily limit on all the proxies and just leave others hanging dry
> 
> There is a few premium proxy services that give you unlimited bandwidth https://proxyscrape.com/premium here is one service that has them 2500 to 5000 proxies should be enough for every 5 to 6 1/2 hrs

Proxies bandwidth are unlimited but Mega is the one limiting 5GB per IP those 2500-5000 proxies are again shared among their users and would have to assume that they would have a policy on not allowing it to be shared publicly. Also Mega can just block all these proxies with just one command and auto ban all new ip's that show up in the application if they wanted to

**Comment by DJboutit** [comment]
> 
> 
> > > > if you took donations for the premium proxies a few users would chip in a few $$ every few months.
> > > 
> > > 
> > > this just wouldn't work since if those premium proxies were shared among all the users. Any user can max out the daily limit on all the proxies and just leave others hanging dry
> > 
> > 
> > There is a few premium proxy services that give you unlimited bandwidth https://proxyscrape.com/premium here is one service that has them 2500 to 5000 proxies should be enough for every 5 to 6 1/2 hrs
> 
> Proxies bandwidth are unlimited but Mega is the one limiting 5GB per IP those 2500-5000 proxies are again shared among their users and would have to assume that they would have a policy on not allowing it to be shared publicly. Also Mega can just block all these proxies with just one command and auto ban all new ip's that show up in the application if they wanted to

These free proxies the program use one are straight up garbage.  I remember over last summer for 110 days the program would not download jack all the free proxies were dead looks like we are headed that route again.
