### ISSUE TITLE
with proxy so slowly download

### ISSUE THREAD

**Issue by Moustafa-desha** [tonikelope/megabasterd#292]
122.50.5.148:10000 | Indonesia | Transparent | No | 1367
-- | -- | -- | -- | --
180.250.12.10:80 | Indonesia | Elite | No | 1980
103.215.177.231:80 | Indonesia | Elite | No | 3112
102.129.249.120:8080 | United States | Elite | No | 697
161.35.70.249:8080 | United States | Elite | No | 2000
198.199.86.11:8080 | United States | Elite | No | 763
51.81.82.175:2003 | United States | Elite | No | 3028
209.97.150.167:8080 | United States | Elite | No | 1485
113.214.13.1:1080 | China | Elite | No | 2131
90.189.110.170:3128 | Russia | Elite | Yes | 3334
60.191.11.249:3128 | China | Transparent | No | 3494
61.153.251.150:22222 | China | Transparent | No | 2655
112.245.17.202:8080 | China | Elite | No | 2004
95.143.8.182:57169 | Russia | Elite | No | 3960
218.14.108.53:8060 | China | Elite | No | 1550
77.232.186.2:8080 | Russia | Transparent | No | 3557
47.98.112.7:80 | China | Elite | No | 2959
61.145.212.31:3128 | China | Transparent | Yes | 2976
210.26.49.89:3128 | China | Transparent | Yes | 1556
46.4.96.137:8080 | Germany | Elite | No | 862
88.198.50.103:8080 | Germany | Elite | No | 645
91.205.174.26:80 | Germany | Elite | No | 2798
139.59.1.14:8080 | India | Elite | No | 3208
191.96.71.118:8080 | Brazil | Elite | No | 3730
123.252.173.162:80 | India | Elite | No | 3900
51.75.147.35:3128 | France | Elite | No | 4735
139.59.1.14:3128 | India | Elite | No | 2904
5.189.133.231:80 | Germany | Elite | No | 2641
103.240.161.101:6666 | India | Elite | No | 1582
88.198.24.108:3128 | Germany | Elite | No | 590
176.9.75.42:8080 | Germany | Elite | No | 613
154.16.202.22:3128 | Germany | Elite | No | 1202
163.172.47.182:8080 | United Kingdom | Transparent | No | 401
186.219.96.47:54570 | Brazil | Elite | No | 2658
103.250.157.43:6666 | India | Elite | No | 4582
45.250.226.48:8080 | India | Transparent | No | 3491
91.226.45.66:8080 | Ukraine | Elite | No | 1122
91.214.128.243:23500 | Ukraine | Elite | No | 2475
134.209.29.120:3128 | United Kingdom | Elite | No | 4533
167.71.5.83:3128 | Netherlands | Elite | No | 1203
203.202.245.58:80 | Bangladesh | Anonymous | No | 2138
103.92.212.242:43399 | Bangladesh | Elite | No | 3428
213.105.29.14:3128 | United Kingdom | Elite | No | 726
186.179.104.46:8080 | Colombia | Transparent | No | 4485
103.113.197.11:8080 | Bangladesh | Elite | No | 3778
154.16.63.16:3128 | United Kingdom | Elite | No | 3853
185.23.131.133:8080 | Iran | Transparent | Yes | 2071
154.16.63.16:8080 | United Kingdom | Elite | No | 2533
169.57.1.84:8123 | Mexico | Elite | No | 1180
119.93.145.246:8080 | Philippines | Transparent | No | 3640
79.101.55.161:53281 | Serbia | Transparent | No | 2526
169.57.1.85:8123 | Mexico | Elite | No | 1120
169.57.1.84:80 | Mexico | Elite | No | 753
103.7.27.186:8080 | Cambodia | Transparent | No | 3990
41.217.219.53:31398 | Malawi | Elite | No | 2387
128.0.179.234:41258 | Czechia | Elite | No | 4067
161.202.226.194:80 | Japan | Elite | Yes | 4034
203.81.95.42:8080 | Myanmar | Transparent | No | 3369
116.197.133.122:3128 | Indonesia | Transparent | No | 2110
187.216.93.20:55443 | Mexico | Elite | No | 4905
82.137.255.109:8080 | Syria | Transparent | No | 4328
103.115.253.47:80 | Bangladesh | Elite | No | 1649
142.4.203.248:3128 | Canada | Transparent | Yes | 696
59.7.123.37:8080 | South Korea | Elite | Yes | 1130
139.59.110.183:8080 | Singapore | Transparent | Yes | 1427
41.73.15.130:8080 | Nigeria | Transparent | No | 1883
113.254.178.224:8193 | Hong Kong | Elite | No | 1099
113.100.209.184:3128 | China | Transparent | No | 2328
120.42.133.58:3256 | China | Elite | No | 2135
93.153.95.186:56603 | Czechia | Elite | No | 1288
37.49.127.236:8080 | Germany | Elite | No | 2488
84.17.51.233:3128 | United Kingdom | Transparent | Yes | 948
46.5.252.55:8080 | Germany | Elite | No | 4864
218.60.8.99:3129 | China | Transparent | No | 1644
213.108.7.91:3128 | Russia | Elite | Yes | 1882
14.97.2.106:80 | India | Anonymous | No | 1596
59.29.245.151:3128 | South Korea | Transparent | Yes | 1026
27.148.248.203:80 | China | Elite | No | 2055
39.108.230.41:80 | China | Transparent | No | 1581
34.203.142.175:80 | United States | Elite | No | 699
49.234.70.78:8888 | China | Elite | No | 1194
41.73.15.130:80 | Nigeria | Transparent | No | 2167
52.221.239.149:80 | Singapore | Transparent | No | 3631
182.92.243.144:80 | China | Elite | No | 2549
14.139.107.211:3128 | India | Transparent | Yes | 1240
37.120.155.100:3128 | Austria | Transparent | Yes | 1378
207.244.239.235:3128 | United States | Transparent | Yes | 695
106.14.226.120:8080 | China | Elite | Yes | 3041
192.46.228.131:8000 | United States | Transparent | No | 1067
49.75.59.242:3128 | China | Transparent | No | 2242
116.62.226.124:4000 | China | Elite | No | 1877
89.221.223.234:80 | Czechia | Elite | No | 1146
51.75.147.40:3128 | France | Elite | No | 4420
59.125.123.129:81 | Taiwan | Elite | No | 1984
177.130.140.80:8080 | Brazil | Transparent | No | 1921
62.210.83.241:3128 | France | Transparent | Yes | 440
62.210.83.241:8080 | France | Transparent | Yes | 418
1.20.156.230:8080 | Thailand | Transparent | No | 2651
104.248.123.76:18080 | United States | Transparent | Yes | 529
185.198.188.50:8080 | United Kingdom | Elite | No | 431
103.224.195.41:3128 | Taiwan | Transparent | Yes | 1314
106.12.141.71:8080 | China | Elite | No | 1269
49.204.79.81:80 | India | Anonymous | No | 1140
103.120.144.144:80 | Bangladesh | Elite | No | 893
173.255.210.35:8080 | United States | Transparent | Yes | 1725
81.91.137.42:8080 | Iran | Transparent | No | 1713
125.87.83.22:3256 | China | Elite | No | 2439
159.65.154.238:80 | India | Elite | No | 1205
128.199.254.103:23352 | Singapore | Elite | No | 4863
220.174.236.211:8091 | China | Elite | No | 4629
190.121.157.138:999 | Colombia | Transparent | No | 3031
103.59.38.77:80 | Bangladesh | Elite | No | 818
101.132.45.68:8080 | China | Elite | No | 2119
161.35.110.195:3128 | United States | Elite | No | 530
37.49.127.227:8080 | Germany | Elite | No | 4770
113.100.209.90:3128 | China | Transparent | No | 2243
139.99.102.114:80 | Canada | Elite | No | 951
1.20.100.227:57396 | Thailand | Elite | No | 4084
150.109.32.166:80 | Hong Kong | Elite | No | 1603
89.221.223.204:80 | Czechia | Elite | No | 664
176.193.11.123:8080 | Russia | Transparent | No | 3763
201.217.49.2:80 | Paraguay | Elite | No | 3905
185.139.13.12:80 | Lebanon | Elite | No | 376
119.42.97.220:8080 | Thailand | Transparent | Yes | 1595
62.171.144.29:3128 | Germany | Transparent | Yes | 449
14.97.2.107:80 | India | Anonymous | No | 4817
209.126.8.58:3128 | United States | Transparent | Yes | 1046
167.71.40.51:3128 | Germany | Transparent | Yes | 390
94.156.144.228:3128 | Bulgaria | Transparent | Yes | 523
111.177.192.104:3256 | China | Elite | No | 1400
185.198.188.49:8080 | United Kingdom | Elite | No | 741
85.196.183.162:8080 | Bulgaria | Elite | No | 4328
39.98.39.55:80 | China | Elite | No | 2102
185.208.182.149:3128 | Iran | Transparent | Yes | 821
85.206.67.38:80 | Republic of Lithuania | Elite | No | 785
36.89.180.103:58841 | Indonesia | Elite | No | 4404
103.89.156.1:8080 | Nepal | Transparent | No | 3552
122.155.165.191:3128 | Thailand | Transparent | Yes | 1062
178.62.56.172:80 | United Kingdom | Elite | No | 539
103.228.117.244:8080 | Indonesia | Transparent | No | 4697
54.156.164.61:80 | United States | Elite | No | 663
182.72.150.242:8080 | India | Elite | No | 1490
221.2.175.238:8060 | China | Elite | No | 1598
93.157.163.66:35081 | Russia | Elite | No | 2781
14.153.55.211:3128 | China | Transparent | No | 1059
159.89.144.221:3128 | United States | Elite | No | 652
202.5.56.71:8080 | Bangladesh | Transparent | No | 2354
146.120.214.62:8080 | Poland | Transparent | No | 2546
125.122.249.62:4216 | China | Elite | Yes | 1616
45.9.229.28:3128 | Uzbekistan | Elite | No | 874
200.63.65.64:8080 | Argentina | Transparent | No | 3099
58.176.147.14:80 | Hong Kong | Elite | No | 1087
178.128.119.20:8080 | Singapore | Transparent | Yes | 906
41.159.55.129:8080 | Gabon | Transparent | No | 1214
113.195.235.226:9999 | China | Elite | No | 2740
196.27.127.170:47504 | Zimbabwe | Elite | No | 4541
188.170.52.188:58928 | Russia | Elite | No | 2009
36.67.86.183:8080 | Indonesia | Elite | No | 4272
111.177.192.8:3256 | China | Elite | Yes | 1329
116.117.134.134:81 | China | Elite | No | 2434
41.190.92.84:48515 | Malawi | Elite | No | 4088
209.126.4.134:3128 | United States | Transparent | Yes | 783
160.19.155.51:8080 | Sierra Leone | Transparent | No | 3686
185.17.134.149:45984 | Russia | Elite | No | 4182
36.67.27.189:39674 | Indonesia | Elite | No | 4715
136.232.209.70:47423 | India | Elite | No | 2645
116.117.134.134:9999 | China | Elite | No | 1644
136.243.254.196:80 | United States | Elite | No | 605
1.20.235.100:8080 | Thailand | Transparent | Yes | 2584
143.110.218.150:8080 | United States | Transparent | Yes | 661
116.0.2.162:52076 | Indonesia | Elite | No | 3284
103.150.109.138:8080 | Unknown | Transparent | No | 3112
31.146.136.70:8080 | Georgia | Transparent | No | 3556
212.115.232.79:31280 | Ukraine | Elite | No | 2184
201.20.39.235:8080 | Brazil | Transparent | Yes | 2032
102.164.252.150:8080 | Equatorial Guinea | Transparent | Yes | 2522
103.139.103.29:3131 | Vietnam | Transparent | No | 4364
113.195.234.131:9999 | China | Elite | Yes | 2552
113.100.209.211:3128 | China | Transparent | Yes | 1030
116.90.229.186:35561 | Nepal | Elite | No | 3066
122.226.57.70:8888 | China | Elite | No | 2324
102.68.129.30:8080 | Libya | Transparent | Yes | 2662
88.119.130.181:9999 | Republic of Lithuania | Transparent | No | 3802
212.120.186.39:60963 | Russia | Elite | No | 4016
200.7.193.229:54954 | Ecuador | Elite | No | 3850
81.33.4.214:61711 | Spain | Elite | Yes | 2362

**Comment by 0-MegaMind-0** [comment]
Speeds for open proxies are not guaranteed it can fluctuate due to several reasons 
1) maybe someone already used that proxy and went over the daily quota
2) your network speed to the proxy 
3) proxies speed to Mega 
4) dead proxies 
and ore 

i"ve had proxies which get me multi gigabit speeds and while others get few kilobits if you want a guaranteed speed then you'll need to purchase some premium private proxies or just get the mega premium account 

here's a issue that can help with proxy slow downs though https://github.com/tonikelope/megabasterd/issues/265 since you can skip the proxies that are slow or unresponsive

**Comment by Moustafa-desha** [comment]
thxs for comment yes some time slow but it not big problem . thxs for your work but it not download all files complete . read from link right  but when download not download all folder . hope fix t in future
