### ISSUE TITLE
Any MegaBasterd since 7.28 does not work (No text is displayed and UI is squished)

### ISSUE THREAD

**Issue by tjd2** [tonikelope/megabasterd#294]
I am using Windows 10 with Czech language. Any Megabasterd version newer than 7.28 just shows without font with vertically squished buttons. Any idea, how to fix it?
Looks exactly like this except i am using windows 10 (i already removed the old version so i didn't take my own)
![image](https://user-images.githubusercontent.com/39863812/107987580-904f6300-6fce-11eb-945c-03ea971a35e7.png)

**Comment by CodyKool** [comment]
I am having the same issue

**Comment by tonikelope** [comment]
Have you tried portable version?

**Comment by tjd2** [comment]
> Have you tried portable version? This is some Java related problem.

I am using only portable version.

**Comment by tonikelope** [comment]
I think it is some Java problem. The portable version includes Java 14. I have packaged the latest version of MegaBasterd along with Java 11 Try this version of MegaBasterd, see if you have any luck.

https://github.com/tonikelope/megabasterd/releases/download/v7.40/MegaBasterdWINDOWS_7.40_portable_JDK11.zip

**Comment by Chiggy-Playz** [comment]
I ran the bat file in the above zip file, but still got weird UI
