### ISSUE TITLE
Add proxy statistics

### ISSUE THREAD

**Issue by tjd2** [tonikelope/megabasterd#295]
Add (possibly to an another openable window) a real-time proxy statistics (individual speed from each proxy, downloaded data from each proxy, ping of each proxy)

Also possibly make the megabasterd somehow mark the good proxies, that did work pretty well until the user reached the 5gb limit and maybe make it discard never working proxies.

**Comment by tonikelope** [comment]
It's not something I have planned in the short term, sorry.
