### ISSUE TITLE
Ya no eso posible descargar 

### ISSUE THREAD

**Issue by Johan-Palacios** [tonikelope/megabasterd#297]
Me aparece API error a pesar de que si tengo un codigo de API de MEGA y esto imposibilita descargar 

![image](https://user-images.githubusercontent.com/77251405/108610190-4c2adc80-7399-11eb-96ac-d00678a3e812.png)

**Comment by tonikelope** [comment]
Hola. Ese error no es por tu API KEY. Son esos enlaces que algo tienen mal.
¿Puedes mandarme los enlaces para revisarlos?
