### ISSUE TITLE
App no longer working

### ISSUE THREAD

**Issue by CodyKool** [tonikelope/megabasterd#298]
I am having the same issue referenced in #294. 
![image](https://user-images.githubusercontent.com/53815248/109486319-d2040180-7ad6-11eb-8184-f88a44113d9b.png)

I am on windows 10 using MegaBasterd 7.40. I have JRE and JDK installed and it still isn't working.

**Comment by tonikelope** [comment]
Have you tried Portable version?

**Comment by CodyKool** [comment]
> Have you tried Portable version?

That works, thanks. What's wrong with the Jar?
