### ISSUE TITLE
SQLITE_Constraint when 2 files have the same filename

### ISSUE THREAD

**Issue by yul-oh895** [tonikelope/megabasterd#299]
Hello, I've been using your program. It works fantastic.

I was downloading a folder when I got the error "[SQLITE_CONSTRAINT] Abort due to constraint violation (UNIQUE constraint failed: downloads.path, downloads.filename"

![javaw_2021-02-28_00-44-19](https://user-images.githubusercontent.com/64549167/110081423-8446fd80-7d51-11eb-9fc7-b1d27808c55b.png)

However after checking the mega folder and the downloaded files, I noticed there were 2 files using the same filename and extension on the Mega folder. My theory is that after downloading one of the files, it then tried to download the second file but it failed to save/overwrite it.

I saw this was also mentioned on #183 but it seems it was skipped since there was a fatal error message at that time.

To clarify, the content of the files are different and they only had the same filename because the original uploader forgot to change it to a different one.

If it's possible I would like to suggest a solution for this by making Megabasterd detect if there is already a file using the same name and if so, either:

- Continue downloading the 2nd file but add a "(1)" or similar at the end to differentiate it.
OR
- Show different options like "Download and overwrite", "Download and rename" or "Skip".

Or choose another method you prefer but that allows to save both files in case a similar situation happens to someone else.

Thanks.

**Comment by tonikelope** [comment]
Yes, this is an old known "bug". When I have some time I will implement something similar to what you propose.

Regards.

**Comment by rvs101** [comment]
Greetings.
I have the same problem with version 7.43.
Thanks for your attention and for the program you create, it helps me a lot to download links from mega. 
😊👍

**Comment by outer2H** [comment]
Hi, This is still a problem with 8.22

**Comment by theOneSchrill** [comment]
hey, it's still a problem to this day (May 13th 2025)
