### ISSUE TITLE
Just a small tiny problem 

### ISSUE THREAD

**Issue by baraa272** [tonikelope/megabasterd#30]
Megabasterd latest version here
i noticed that there is one small issue 
when you download files with japanese/chinese names 
Megabasterd actually fucked up the names of the files with unknown characters 
i thought may its problem from windows but its not 
i tried mega downloader 1.7 and it got the names of the files right 
so may you look at this tiny issue ?? please 
Also i want to Show my gratitude to you Sir 
You're A legend among Men in this world that lacks real legends 
All love and thanks <3

**Comment by tonikelope** [comment]
Hi! Please try 5.42 and select alternative font in advanced settings. Put here your feedback for this new feature.

Regards.

**Comment by baraa272** [comment]
I'm using megabasterd 5.42 and setting it (font method alternative) and yet Japanese character got corrupted 
I don't why but mega downloader 1.7 got the names and characters right

**Comment by tonikelope** [comment]
Hello. Please, puta here antes example link.

Regards.

**Comment by tonikelope** [comment]
> 
> 
> I'm using megabasterd 5.42 and setting it (font method alternative) and yet Japanese character got corrupted
> I don't why but mega downloader 1.7 got the names and characters right

Hi. Please, run MegaBasterd from CMD.exe 

`java -Dfile.encoding=UTF-8 -jar MegaBasterd_5.42.jar`

**Comment by baraa272** [comment]
Worked Flawlessly 
so what do you advise ?
do I need to run that command whenever I need to download Japanese/Chinese files?

**Comment by tonikelope** [comment]
I recommend you to create a batch file with that command to launch MegaBasterd always with UTF-8 support.

https://www.utilizewindows.com/how-to-create-a-batch-file-in-windows-10/

Regards.

**Comment by baraa272** [comment]
Thanks And all Love & Respect <3
