### ISSUE TITLE
Folder link detected failure

### ISSUE THREAD

**Issue by GEORGEJUNGCOCAINE** [tonikelope/megabasterd#303]
How can I donwload this file then?  **https://mega.nz/folder/SN9gAKxI#5HSDWDSoFc7dPzcTk9BHjw/file/vd8CHQLK**
Thanks in advance.

**Comment by tonikelope** [comment]
https://mega.nz/folder/SN9gAKxI#5HSDWDSoFc7dPzcTk9BHjw
