### ISSUE TITLE
Support for Mega Folder

### ISSUE THREAD

**Issue by MikeHMdr** [tonikelope/megabasterd#305]
There are an error if I paste a Folder link.
Support for Mega Folder would be a great next feature.

![mega_folder_error](https://user-images.githubusercontent.com/36677796/112217741-7e259d80-8be8-11eb-8cc1-1b68fa2db241.png)

**Comment by patros36** [comment]
Same here, tried the previous version and that doesn't work either.

**Comment by patros36** [comment]
nvm, just add the API key and it works...at least for me that was the problem.

**Comment by tonikelope** [comment]
It is on the to-do list..
