### ISSUE TITLE
font problem

### ISSUE THREAD

**Issue by TheOnlyIsmail** [tonikelope/megabasterd#306]
why the font is like that ?
![Untitled](https://user-images.githubusercontent.com/57960792/112738513-6e48e900-8f5b-11eb-8090-6ccbd95a511c.png)

**Comment by tonikelope** [comment]
Have you tried to change font in advanced settings? Java version?

**Comment by TheOnlyIsmail** [comment]
> Have you tried to change font in advanced settings? Java version? Do you use MegaBasterd portable or normal version?

Yes I have tried the default and the alternative font

Java version : Version 8 update 291

And I use the norman version
