### ISSUE TITLE
Joining file chunks does not happen

### ISSUE THREAD

**Issue by ronmr2** [tonikelope/megabasterd#308]
I have several downloads with the message "Joining file chunks please wait" but it does not happen, anything I can do to fix this ?

**Comment by markmghali** [comment]
yes my chunks are stuck! not sure how to proceed?

**Comment by IAHSXIDEAS** [comment]
I think I have an explanation for that problem. At first when i ran into that problem, I got worried and thought the same as you - that the program got stuck, when in fact it was not. So I started digging in the output files. I found the chunks folder, and in it the downloaded chunks were slowely disapearing, starting from the first ones. That assured me that the program was not stuck. Did you check for that happening?
