### ISSUE TITLE
The settings window always opens a blank new window with no visible options

### ISSUE THREAD

**Issue by Jupisoft111** [tonikelope/megabasterd#310]
Hello, I tested this on 7.40 and 7.21, and in both when I try to change the settings it only opens a large blank window. Maybe it has to do with my screen resolution, since I'm still using an old resolution of 1.024 x 768 pixels (4:3 of ratio). If that's the case maybe a horizontal scroll bar might solve the problem, if not then I have no clue why this is happening. Thanks in advance and have a nice day :-)
![Resolution_1024_768](https://user-images.githubusercontent.com/28818179/115181149-3272f080-a0cf-11eb-88c0-d2f64c78866e.png)

**Comment by tonikelope** [comment]
Have you test portable version?

**Comment by Jupisoft111** [comment]
Yes, I did. And I tried both the x86 and x64 versions to test this. I have Windows 10 64 bits with an intel dual core at 3.2 GHz and 12 GB of RAM in case this helps.

Update: I changed my screen resolution to 1280 x 1024 (which I never use because I barely can't read the text on the screen with my very old HP vs 19 screen that has a 5:4 native resolution), and now the settings have appeared for the first time, so now I'm 100% sure it has to do with lower resolutions. Maybe it has a minimum of 1280 of width and less than that somehow stretches the whole window content rendering it invisible or something like that. I hope this can help fixing the issue for other people as well.

**Comment by tonikelope** [comment]
> Yes, I did. And I tried both the x86 and x64 versions to test this. I have Windows 10 64 bits with an intel dual core at 3.2 GHz and 12 GB of RAM in case this helps.
> 
> Update: I changed my screen resolution to 1280 x 1024 (which I never use because I barely can't read the text on the screen with my very old HP vs 19 screen that has a 5:4 native resolution), and now the settings have appeared for the first time, so now I'm 100% sure it has to do with lower resolutions. Maybe it has a minimum of 1280 of width and less than that somehow stretches the whole window content rendering it invisible or something like that. I hope this can help fixing the issue for other people as well.

I promise to look into it as soon as possible.

Regards.

**Comment by rudramsaraf** [comment]
@tonikelope 
@Jupisoft111 
the issue should solve after decreasing the size of the settings windows, i also faced in same issue literally in every version but accidentally i changed the size of the blank settings windows and boom settings appear 
i tried this is in 7.46 release and probably this should work in others also

**Comment by tonikelope** [comment]
Let's see if it works

**Comment by sahilsuman933** [comment]
@tonikelope I am also facing this issue. Can you please help me with this or tell me how to debug this issue? 

Problem Issue:
![image](https://github.com/tonikelope/megabasterd/assets/34382211/d074ae56-7d77-4e86-a6d1-0de0dcab9cd1)

Configuration:
![image](https://github.com/tonikelope/megabasterd/assets/34382211/869a5d1a-2712-44f6-b52f-833cfdc443fe)

**Comment by tonikelope** [comment]
Right now I have hardly any free time. I recommend you to try different versions of Java starting with OpenJDK11 to rule this out.

**Comment by sahilsuman933** [comment]
Sure. I will do that, @tonikelope.
