### ISSUE TITLE
Downloads dont start

### ISSUE THREAD

**Issue by visualhippocracy** [tonikelope/megabasterd#311]
Downloads dont start at all. Stuck at 0 bytes forever.
This happens with smart proxy on or off

**Comment by nnguyen555** [comment]
Same for me

**Comment by RNDrG** [comment]
Same with me ver 7.40

**Comment by awsms** [comment]
RIP megabasterd?

**Comment by tonikelope** [comment]
I cannot reproduce this supposed error. Debug file?

> RIP megabasterd?

No way, but I don't have much time lately, but as long as I can, I'll keep it updated from BUGS. Thanks for using it.

**Comment by Jesu-dotcom** [comment]
I can confirm this issue with 7.40. The download started and suddenly it stopped. It has not resumed despite the hours that passed
![megabasterd not downloading](https://user-images.githubusercontent.com/81889973/117600708-17b1fb80-b112-11eb-9761-79ff58fbaa59.png)

**Comment by tonikelope** [comment]
It looks like you have reached your daily MEGA download limit.
