### ISSUE TITLE
How do you deal with FOLDER links?

### ISSUE THREAD

**Issue by frenchiveruti** [tonikelope/megabasterd#312]
I've tried the wiki but it's empty, say I want to download this:  
https://mega.nz/folder/ozI3UAQI#SiW3kgQV3khyf9NLyzmzGQ/file/ojgQhYxR  
It's a "folder" link but points to a single file. 
Megabasterd sadly doesn't like folder links, so how do I approach this?  
Thanks :D

**Comment by tonikelope** [comment]
Hi. Folder link -> https://mega.nz/folder/ozI3UAQI#SiW3kgQV3khyf9NLyzmzGQ

Regards.

**Comment by frenchiveruti** [comment]
Ok so I have to use the ROOT folder for the program to work? 
Feel free to answer me when you have time I'm in no rush 😄
