### ISSUE TITLE
Fatal Error! Mega API Error: -16

### ISSUE THREAD

**Issue by elias0057** [tonikelope/megabasterd#313]
Cuando pongo el enlace del folder y le doy a descargar me salta este error pero no se por que si mi API es valida.
Dejo el link y una imagen como referencia
https://mega.nz/folder/YhR20YjQ#Fne_W6Xm2ef049bhW1XMeA
Cuando lo copio en el Link Grabber se modifica de esta forma:
https://mega.nz/#F!YhR20YjQ!Fne_W6Xm2ef049bhW1XMeA
![image](https://user-images.githubusercontent.com/77704890/117510216-4a60c600-af51-11eb-8f93-4d6adfa90876.png)

**Comment by tonikelope** [comment]
These files are blocked for violating MEGA's terms of service.
