### ISSUE TITLE
Problemas con los archivos mayores al giga

### ISSUE THREAD

**Issue by pepecachu** [tonikelope/megabasterd#32]
Buenas.
Primero, quería agradecerte por este programa.

El caso es que al descargar archivos más grandes del gigagbyte hay veces, a veces no ocurre, que el archivo llega al 100% y no se acaba de descargar, sigue ahi como descargando, sin consumir linea ni nada. Si tienes el límite de descargas simultáneas en 1, ya no se inicia nueva descarga. Normalmente lo soluciono cerrando y abriendo, pero aun así hay veces que sigue igual, y lo vuelvo a abrir y cerrar.

![eo](https://user-images.githubusercontent.com/43928546/46915005-e4cd1880-cfa5-11e8-8aa9-a56c0a7fe0b2.PNG)

Así se queda, hasta que no cierras el programa se queda así.
Se que es con los mayores de un giga porque me descargué hace poco setenta archivos de 800 mB, e iba perfecto. Pero si es mayor al giga pues pasa esto. 
Por si influye en algo, tengo el reverse mode activado, y el comprobar la integridad del archivo. Pero he hecho pruebas quitándolos y me sigue saliendo el error.

**Comment by tonikelope** [comment]
Hola. ¿Puedes ejecutar MegaBasterd por consola y pegarme aquí lo que va saliendo cuando ocurre eso? ¿Qué sistema operativo usas? Podría ser un problema de que algún chunk del archivo se queda bloqueado por culpa de algún proxy que no responde. Voy a investigarlo. 

Gracias por avisar.

Salu2 ;)

**Comment by pepecachu** [comment]
Ahora estoy usando windows 7 professional, pero eso me ha ocurrido también en Linux Mint 18.1

![eoo](https://user-images.githubusercontent.com/43928546/46916826-3e424100-cfc0-11e8-9a8a-98774e47d267.PNG)

Como ves, lleva así cuarenta minutos.  La GUI lleva parada como en la imagen de mi mensaje anterior el mismo tiempo.

**Comment by baraa272** [comment]
![mega](https://user-images.githubusercontent.com/32843097/46919485-b3c20780-cfe8-11e8-9fe1-c26295fcff2e.PNG)
![megacmd](https://user-images.githubusercontent.com/32843097/46919488-b886bb80-cfe8-11e8-9c64-a2d5a25039c4.PNG)

I have same problem here

**Comment by tonikelope** [comment]
Please, try this https://github.com/tonikelope/megabasterd/releases/tag/v5.43

but redirect all log output to a file in this manner:

`java -jar MegaBasterd_5.43.jar > log.txt 2>&1`

and post here log.txt

Thank you.

**Comment by baraa272** [comment]
I will test it and post the log at this Wednesday at this week 
All love and respect

**Comment by baraa272** [comment]
(megabasterd 5.45) Actually its working and doesnt stuck at all **BUT Cant get over BANDWIDTH LIMIT!!!!! ERROR 503** 
[log.txt](https://github.com/tonikelope/megabasterd/files/2486071/log.txt)

![megastuck](https://user-images.githubusercontent.com/32843097/47066534-2270b200-d1ef-11e8-96a8-c09f3fcdab72.PNG)




I actually tried the old version 5.42 and its working against bandwidth limit 
see 
![megabasterd](https://user-images.githubusercontent.com/32843097/47066358-76c76200-d1ee-11e8-8368-230c91211143.PNG)

**Comment by tonikelope** [comment]
Please, test 5.46

Regards.

**Comment by baraa272** [comment]
Thanks I will test it on Saturday 
All love and respect <3

**Comment by pepecachu** [comment]
Aquí lo tienes. Estoy usando la última, la 5.47. Ya lleva un rato con el error, y se me descargó uno correctamente.
[log.txt](https://github.com/tonikelope/megabasterd/files/2496499/log.txt)

**Comment by tonikelope** [comment]
Hola. Por favor, prueba la 5.48 a ver si hay suerte. El problema es que un chunk no se descarga y se queda la descarga parada. He añadido más mensajes para intentar dar con lo que pasa. Acabará saliendo, está claro. 

Salu2 ;)

**Comment by pepecachu** [comment]
Sigue pasando, pero esta vez se me descargaron ocho archivos antes de que se atascara
[log.txt](https://github.com/tonikelope/megabasterd/files/2498017/log.txt)

**Comment by pepecachu** [comment]
Ahora se me han descargado cuatro archivos antes de que se me parara. Lo he dejado toda la noche a ver si cambiaba algo, pero nada.
[log.txt](https://github.com/tonikelope/megabasterd/files/2499657/log.txt)

**Comment by tonikelope** [comment]
Hola. Creo que ya está. Lo que pasaba es que no se cerraba un fichero temporal cuando fallaba la descarga de un chunk mediante un proxy y cuando se volvía a descargar el chunk correctamente, fallaba al renombrarlo porque el fichero temporal seguía abierto. Ya está corregido en la última versión. Espero que ahora ya funcione correctamente. 

Disculpad las molestias y gracias por la ayuda de testing.

Salu2 ;)

**Comment by tonikelope** [comment]
Creo que ya he dado con el problema. Cuando fallaba la descarga de un chunk
por proxy no se cerraba correctamente el fichero temporal y al volver a
descargarlo bien fallaba al guardar el chunk. Como en mís pruebas no estaba
usando proxys no me daba cuenta.

Prueba la 5.50 a ver si hay suerte y se queda este fallo solucionado.

Salu2 ;)

**Comment by FroggerJJ** [comment]
Hola tengo un problema con mega basterd me sale error 1 2 3 4 5
![image](https://user-images.githubusercontent.com/51304680/60457365-7696b780-9c01-11e9-9d77-3115c0d848e0.png)

**Comment by HeidyRC** [comment]
Hola, quisiera saber porque cuando copio el enlace de mega a MegaBasterd este me "enlace de mega erroneo"; antes me funcionaba normal, incluso con archivos que pesaban más de 40GB, pero ahora no reconoce archivos de mas 10GB y poco a poco me limita el peso de descargas.
Ya me instale la nueva versión pero sigue igual.

**Comment by Zankiev** [comment]
A mi me ocurre algo peor, use por algunos días la versión 6.32 y todo ok, descargaba con alto BW y sólo con un archivo se bloqueo; sin embargo, un par de días después no se bloqueaba todo en 0%, no descargaba nada, creía era un error producto de la nueva versión y descargué la 6.33, e igual, no descarga nada de nada, todo está con 0 % hace una semana. Sinceramente no entiendo qué ocurre, lo inicio desde CMD e igual, no se mueven las descargas...

**Comment by pablocapilla19** [comment]
Hola ami me pasa que la descarga llega al 24% y empieza a tirar error 3 2 1 4 5 en orden invertido... tengo Windows 10 Pro y la ultima version de Megabastard 6.38....
