### ISSUE TITLE
Proxies With Passwords

### ISSUE THREAD

**Issue by BeholdTheKing** [tonikelope/megabasterd#320]
I see the format for proxies in the SmartProxy settings but I'm trying to figure out what I'm missing or adding that should or shouldn't be there. 

Is it supposed to be like?

[*]111.111.11.11:1111[@username:password]

or

*111.111.11.11:1111@username:password

or

111.111.11.11:1111@username:password

or

*111.111.11.11:1111@username_b64:password_b64

or something else...

--

**Comment by tonikelope** [comment]
https://github.com/tonikelope/megabasterd/issues/291
