### ISSUE TITLE
Application Freeze on Pause

### ISSUE THREAD

**Issue by n810K** [tonikelope/megabasterd#328]
While downloading, if I press "Pause all Downloads", the application will freeze and I am unable to interact with any part of the program. I must force close the program then reopen it in order to interact.

**Comment by tonikelope** [comment]
When the pause button is pressed, megabasterd has to wait for all slots in each download to pause. If you have many downloads with many slots, it will take longer and if you are also using proxies that are slow or slow to respond, it will take even longer to pause EVERYTHING (and the continue button will reappear).

**Comment by n810K** [comment]
I only press the Pause All button. When I press this the application freezes. I give it a decent amount of time and when I click back to it the application turns black. Perhaps I need to give it even more time

**Comment by tonikelope** [comment]
I hope the latest version works correctly for you. If not, reopen the issue and paste a debug file and test links.
