### ISSUE TITLE
Just Resets Downloads , Connection Failed

### ISSUE THREAD

**Issue by baraa272** [tonikelope/megabasterd#33]
Megabasterd 5.48 
megabasterd after a few downloads start to behave weird and just reset the downloaded chunks over and over again infinitely 
pls see log 
[log.txt](https://github.com/tonikelope/megabasterd/files/2497848/log.txt)
I have tried mega5.42 it works but downloads stuck

WHILE I actually tried mega5.26 (An old version) and its working perfectly here (downloads over bandwidth limit and no stuck )

maybe you should look at this version 
![mega5 26](https://user-images.githubusercontent.com/32843097/47252177-be492a80-d448-11e8-9e49-263741e6ccaa.PNG)

**Comment by baraa272** [comment]
will download the newest release again , and give you results tomorrow 
cheers <3

**Comment by baraa272** [comment]
Best Love And Respect Young God 
You really deserve to be top notch in programming <3
Everything is working as it should be <3
No stuck
No bandwidth limit
No corrupt data
it just works as it would 
its all because of your god efforts on this masterpiece 
you made lost man happy today 
I love and respect you 
you can close the case

**Comment by tonikelope** [comment]
Thank you!  It has been a pleasure.

Hopefully MEGA will last a long time!

Regards.
