### ISSUE TITLE
Fatal Error! Mega api error: -16

### ISSUE THREAD

**Issue by junior1213** [tonikelope/megabasterd#331]
Hey firstly I want to thank you for creating such a software, but recently I'm experiencing problems getting an error I'm using the latest version, and I'm trying to download files from a folder...
Here is a screenshot of the error.
![Error](https://user-images.githubusercontent.com/29717943/123736054-052c8680-d866-11eb-8a4e-cf07e60d916e.png)

**Comment by flaprocha** [comment]
Hello. Same issue here. I am using V 7.42 portable.
![image](https://user-images.githubusercontent.com/322196/124747482-5983d600-def8-11eb-9d96-e20713ee0438.png)

**Comment by tonikelope** [comment]
Hello Felipe.

ERROR -16 -> MEGA LINK IS BLOCKED or DELETED.

Regards.

**Comment by flaprocha** [comment]
Hi @tonikelope , thanks by your fast reply.

Here you have the link[1] which content is accessible to an unlogged user.

1 - https://mega.nz/folder/70owzABT#yJIanvHCVR8q1EqV_Pnpng/folder/exRRFQxS

Thanks.

**Comment by flaprocha** [comment]
I can list files but I can't access, open them. So, yes, Files are blocked.

**Comment by flaprocha** [comment]
Taking advantage of what has happened. I would like to suggest you to create a clean up procedure of stalled downloads, a way to remove files which were not downloaded. At the current scenario, where MegaBasterd identified that files are not accessable, but, I have them all listed at the Downloads tab, I will need to Close one by one and this will take some time. A cleanup procedure would come handy in this case.

I see an option at 'File' -> 'Remove all no running downloads' but for some reason it is not enabled.

Anyway, thanks by your software, it really rocks.

**Comment by tonikelope** [comment]
I will try to add that button in the next update.

**Comment by flaprocha** [comment]
If feasible, please insert a message explaining the reason of this error to help users identify possible problems with the Mega's link.  A fatal error printed in red scares everyone, as a known API issue, a tip on it would help users. Again, thanks by your effort on this software.
