### ISSUE TITLE
Data loss when downloading

### ISSUE THREAD

**Issue by masharia-john** [tonikelope/megabasterd#333]
I was downloading a 6GB video file and it went up to 80% on ethernet (eth0).When i change connection to wireless interface(wlan0) the download resumed at 55% losing the 25% data...i was wondering if you can create a network interface option radio button to choose from for the download process....Again thanks for the app...i appreciate the work

**Comment by tonikelope** [comment]
Have you tried changing network interface with Megabasterd open? 
What if you PAUSE all transfers, change network interface and then continue downloads (without closing MegaBasterd)? 
This way, the download should continue at the EXACT point.

What you are asking is not easy to do (it was already asked by another user in the past).

**Comment by tonikelope** [comment]
I hope the latest version works correctly for you. If not, reopen the issue and paste a debug file and test links.
