### ISSUE TITLE
Unable to download video file

### ISSUE THREAD

**Issue by upjabir** [tonikelope/megabasterd#334]
Since megabasterd is working fine , suddenly it don't download the video file. Moreover It is able to download the document files. Also i had tried downgrading the version of megabasterd but it all went into fatal
![mega](https://user-images.githubusercontent.com/40956091/125230045-9e8f7a00-e2f5-11eb-945b-2c1b79109a93.png)

**Comment by tonikelope** [comment]
ERROR -16 -> MEGA FILE BLOCKED (probably copyright issue)

Regards.
