### ISSUE TITLE
Download stuck at 99%

### ISSUE THREAD

**Issue by DJboutit** [tonikelope/megabasterd#336]
I am downloading a 5gb file it download 99% in like 15 min it has been stuck at 99% for 4 1/2 hrs now I only have like 17mb left please fix this thx.

**Comment by sonhsien** [comment]
I have the same problem. I got stuck at both 99% and 100%. You can try to use version, 7.40, which I found would avoid this problem.

**Comment by tonikelope** [comment]
https://github.com/tonikelope/megabasterd/issues/337
