### ISSUE TITLE
Megabasterd no descarga

### ISSUE THREAD

**Issue by LetyVic** [tonikelope/megabasterd#345]
Buen Día Solicito su valiosa ayuda
Ya descargue la ultima version 7.43, pero al descargar el archivo aparecen lineas y no descarga, pense que era por la versión anterior pero con la nueva sigue igual, que puedo hacer?
![megabas](https://user-images.githubusercontent.com/89534859/130822783-ed4a9ad3-eb1c-4fa0-9240-19a1d153ee0f.png)

@tonikelope

**Comment by otto500206** [comment]
Why aren't you talking English?

**Comment by alanliew88** [comment]
I have experience this issue, too, it stayed in this page for so long without any progress at all. Not sure what is happening

**Comment by tonikelope** [comment]
MEGA has a download limit every so often that forces you to wait a few hours when you have downloaded too much. To avoid this it is necessary to buy a MEGA account. There is also the alternative (at your own risk) of using proxies (Downloads -> SmartProxy) or a VPN.
