### ISSUE TITLE
i dont't know anymore

### ISSUE THREAD

**Issue by baraa272** [tonikelope/megabasterd#36]
Hi master chief 
megabasterd 5.61 resets chunks over and over again infinitely and just cant get over it at all 
EVEN when using vpn 
i tried 2 different vpns with different locations and yet 
start downloads for bit of time and then start reset chunks to 0% 
[log.txt](https://github.com/tonikelope/megabasterd/files/2544939/log.txt)

i hope theres some hope for me :(

**Comment by tonikelope** [comment]
Can you put here the link you are trying to download (or send me by email)? I can't reproduce your errors, seems like some network problem beyond MegaBasterd or MEGA :(

Regards.

**Comment by baraa272** [comment]
https://mega.nz/#F!qigiVC5D!a24zGK1fBIAQHT_TALlKMQ

https://mega.nz/#F!iygyAIbS!Ky-e7qqsvHgn3wB-LmXVzw

also if you dont mind 
could this https://github.com/JohnDeved/megacrypt.js be implemented ????

**Comment by baraa272** [comment]
also theres an email with details :( on your gmail

**Comment by tonikelope** [comment]
Hello.

Some files of these folders do not download with MegaBasterd nor from the
MEGA website.

It seems there is some connection problem with the physical server where
these files are stored or some kind of file download restriction. There is
no solution other than waiting for mega to fix it, sorry.

Regards.

**Comment by baraa272** [comment]
okay as you would like <3

**Comment by tonikelope** [comment]
Hello. I discovered that some files in those folders have a wrong behavior when downloading some chunks. They return more bytes than expected and MegaBasterd gets confused. I've implemented a feature to control the number of bytes returned (and not trust the MEGA API that does strange things sometimes) and it works: the file ends up downloading. I hope it works for you.

Regards.

**Comment by baraa272** [comment]
it werks completely without any problem <3
