### ISSUE TITLE
Links to files in folders can't be loaded

### ISSUE THREAD

**Issue by shadoxxhd** [tonikelope/megabasterd#360]
When trying to enter a .../file/... link, I get an Error dialog (or, when removing the https:// in front, the application freezes and can only be closed via task manager). Removing the part whole /file/... part correctly opens the folder overview, allowing me to select what to download.

**Comment by tonikelope** [comment]
Added support for links pointing to a file within a folder. 
Note: it is normal for folders with many files to take a few seconds to load.
