### ISSUE TITLE
Megabasterd not downloading anything

### ISSUE THREAD

**Issue by SkyrimFan64** [tonikelope/megabasterd#366]
Hi. Whenever I try to download something from Megabasterd it is always stuck at 0%. I am using links from the Mega website

**Comment by tonikelope** [comment]
Do the links that do not download with MegaBasterd download AT THAT SAME TIME through the MEGA website?

**Comment by masharia-john** [comment]
if you have a mega account...Transfer the file from the website(where the original file is) to your mega account and use the link from your mega account
