### ISSUE TITLE
every time i try to stream something it fails 

### ISSUE THREAD

**Issue by marquinhoos** [tonikelope/megabasterd#367]
![image](https://user-images.githubusercontent.com/93748551/140441856-7fa85105-3c35-4619-801c-c75b0fbe6505.png)

and it is a valid link, i downloaded the video in the link

**Comment by tonikelope** [comment]
Links to files inside folders do not work in the streamer. I will add it as soon as possible. Thanks for the warning.

**Comment by Deniz1433** [comment]
When will this be added? :)
