### ISSUE TITLE
Do folders no longer work? MEGA LINK ERROR

### ISSUE THREAD

**Issue by Tenome** [tonikelope/megabasterd#371]
https://puu.sh/IoKWf/89d9cb1c9d.png

This app used to parse folder links just fine, but now it seems like they never work. I'm on the latest version, and my API key is saved. I guess I'll have to find another app to use until this is resolved...

**Comment by tonikelope** [comment]
Send me your link by mail to test It.

***@***.***

**Comment by Tenome** [comment]
Never replied via Github email before, hope this works.
https://mega.nz/folder/zNdAzbzI#9Msgqo61pRGiEbq7_Xilmw

**Comment by tonikelope** [comment]
https://i.imgur.com/Jb5mwJR.png

**Comment by Tenome** [comment]
Hmm, weird. I redownloaded it and it's parsing correctly now. Whatever, case closed. Thanks.
