### ISSUE TITLE
[FIXED BY MYSELF] System can not find path if the path has a "@" symbol.

### ISSUE THREAD

**Issue by funkman21** [tonikelope/megabasterd#375]
I found out that its not the @ in the path. But something different is triggering the IO Exception.

**Comment by funkman21** [comment]
So i found the issue. 
The mega nz path contains  2 dots in a row and the io.File. removes these. 

"[...] this method first converts this pathname to absolute form if necessary, as if by invoking the getAbsolutePath method, and then maps it to its unique form in a system-dependent way. This typically involves removing redundant names such as "." and ".." from the pathname, [...]"

**Comment by funkman21** [comment]
So the issue was that the dir from mega hat dots at the ending and the java.io.WinNTFileSystem.java didn't liked that because it 
inherts from java.io.Win32FileSystem and that one is From Windows NT/2000 : 
![image](https://user-images.githubusercontent.com/95734291/145265777-9fbe42a8-8eee-47c5-b5c6-11e68794e554.png)

I had some time and programmed a workaround to get rid ofthat issue. There's still a small bug but for me thats fine, it works.

**Comment by tonikelope** [comment]
Hi. Hi. Very interesting what you say, could you post the link that gives you problems to test it even if it is by private? I'll see if I can patch it when I have some time. Thanks for your help.

**Comment by tonikelope** [comment]
I have tried downloading that folder from Linux and it saves it without problems. I think the problem only affects Windows, so I will modify this function to make that change. Thanks for the help! 

https://github.com/tonikelope/megabasterd/blob/03e1824dda67851be653b7a15a02f12c1d117084/src/main/java/com/tonikelope/megabasterd/MiscTools.java#L716

**Comment by funkman21** [comment]
U're welcome. I allways like to help.
