### ISSUE TITLE
App seems bugged after pc reboot?

### ISSUE THREAD

**Issue by r1n0x** [tonikelope/megabasterd#376]
I used it on 14.12.2021 and it was truly perfect app, like, I couldn't think of anything more it could do, but after trying to downlaod something today app seems lagged?

What i tried:
 downloading it few times and removing it,
 adding different API key,
 resetting megabastard (advanced option),
 restarting my pc,
 restarting the app,
 installing java from oracle (didn't have it) and changed in in bat and things still are not working
 using links like: (link thing after copying them in doesnt work either)
  https://mega.nz/embed/x
  https://mega.nz/x

I can download files using browser normally so I don't think its IP related, they should atleast popup in the app with red text right.

Would be thankful if you could help in any way, app is truly magnificent and it downloads things at my actual isp cap not some shit like in-browser which makes things go a lot faster.

https://user-images.githubusercontent.com/16156772/146452205-6981a0f6-cd14-42b7-9e7d-1225e4999018.mp4

**Comment by tonikelope** [comment]
Embed links are not supported for now.

Regards.

**Comment by r1n0x** [comment]
Well thanks im a clown I thought app worked fine 3 days ago with them. 
Thanks for help, for making the app and good luck on the app developement in the future.
