### ISSUE TITLE
Proxy list here on github has stopped updating

### ISSUE THREAD

**Issue by gohamstergo** [tonikelope/megabasterd#378]
Just noticed the last update was 3 days ago as of posting. usually updates every hour or two. thanks.

**Comment by iamleifaa** [comment]
Has anyone got some proxy? The one i get on the net is freaking slow even tho i;ve filtered it on like 9mb/s and 100% uptime.

**Comment by masterofobzene** [comment]
![imagen](https://user-images.githubusercontent.com/94469116/148452803-01261b25-fd66-4192-87b8-fefc80641344.png)

ABANDONED.

**Comment by masterofobzene** [comment]
Guys I just searched for one of the proxies (194.233.73.105:443) recommended and the same proxy was found in this rather obscure github.

https://github.com/DarlingSh1337

![imagen](https://user-images.githubusercontent.com/94469116/148454255-22070434-e55b-41e8-aab8-622d3e1fddeb.png)

Just a heads up... I don't know what those proxies do...

**Comment by gohamstergo** [comment]
the list seems to be updating again.
