### ISSUE TITLE
"Clear Finished" doesn't show up if only links added that are "FILE WITH SAME NAME AND SIZE ALREADY EXISTS"

### ISSUE THREAD

**Issue by ericziethen** [tonikelope/megabasterd#379]
When adding links to a blank download list which all result in "FILE WITH SAME NAME AND SIZE ALREADY EXISTS" the "Clear Finished" button doesn't show up and the links need to be closed individually.

Once a new download is completed, the button shows up and will clear all links.

**Comment by tonikelope** [comment]
Clear finished now clears anything that has finished correctly or with an error. Hope this helps.
