### ISSUE TITLE
Batch uploading problem

### ISSUE THREAD

**Issue by Ruriko** [tonikelope/megabasterd#38]
I added a bunch of files to upload but only 2 files get uploaded. Why is that?
![Image](https://i.imgur.com/ZLRoasd.png)

**Comment by tonikelope** [comment]
Error mesages? I need you to run MegaBasterd from a command prompt (CMD.exe  to see what bugs appear and put them here. 

`java -jar MegaBasterd_xxx.jar`

**Comment by Ruriko** [comment]
There no error message. I add a file but it doesn't get added to the upload list so it not uploading the file
![Image](https://i.imgur.com/PZOaqkY.png)

**Comment by tonikelope** [comment]
It seems there os some problem when reading the directory in your first
screenshot because the total size 31MB is wrong. Mmmmmm... Does it happen
with all directories or just with this example?

**Comment by Ruriko** [comment]
It happens with all directories

**Comment by tonikelope** [comment]
It's really weird. Without errors or exceptions in the execution I can not think what may be happening to you because in my tests works perfectly. What version of Java do you have installed?

**Comment by tonikelope** [comment]
I've changed a bug with the decimal separator character that could be causing problems. Please, try 5.76 release and put here if the problem is fixed.

**Comment by Ruriko** [comment]
Thank you it's working now!
