### ISSUE TITLE
Apple M1 support?

### ISSUE THREAD

**Issue by doobersn** [tonikelope/megabasterd#384]
Hello, does this work for Apple devices running MacOS with M1 chips? I cant seem to get it to work. Thank you!

**Comment by tonikelope** [comment]
Hi. I have no possibility to check it. You can install some jdk with M1
support and go testing.

https://stackoverflow.com/questions/64788005/java-jdk-for-the-apple-m1-chip

**Comment by doobersn** [comment]
Ah, thank you! The splash screen comes up but there is a java error afterwards so im not sure.
