### ISSUE TITLE
Download doesn't starts

### ISSUE THREAD

**Issue by DarknessGab** [tonikelope/megabasterd#385]
I'm trying to download some files but never starts.

![image](https://user-images.githubusercontent.com/97704273/149409488-cbb8477a-1c58-46a5-b540-ff51f2a8313a.png)

**Comment by mridun-gupta** [comment]
yes same issue with me @tonikelope

**Comment by tonikelope** [comment]
Hello, you have reached the download limit imposed by MEGA. From here there are 4 possible options:

1) WAIT for MEGA to let you download again (usually 6/12 hours).

2) Pay for a MEGA PRO account.

3) Use proxies (downloads -> SmartProxy and paste your proxies) -> https://github.com/tonikelope/megabasterd/tree/proxy_list

4) Use a VPN

Regards.

**Comment by mridun-gupta** [comment]
thanks sir

**Comment by MrGTAmodsgerman** [comment]
> Hello, you have reached the download limit imposed by MEGA. From here there are 4 possible **MITIGATIONS** (none perfect or definitive):
> 
>     1. WAIT for MEGA to let you download again (usually 6/12 hours).
> 
>     2. Pay for a MEGA PRO account.
> 
>     3. Use proxies (Settings -> Downloads -> SmartProxy and paste your proxy list) -> https://github.com/tonikelope/megabasterd/tree/proxy_list (Remember
> 
>     4. Use a VPN
> 
> 
> Regards.

Sadly doesn't work for me (proxylist way)

**Comment by hemzmaz** [comment]
Sir my download is fast until 4gb then it starts to lag.....it is now downloading the last file @471B/s.Please tell me how to fix it.

**Comment by Eltik** [comment]
Proxies work perfectly fine. Check the proxy list every so often. The author of this project is insane and updated it literally 1 hour ago, so the proxies work fine then. Keep in mind that looking up proxies from [here](http://free-proxy.cz/en/proxylist/country/US/all/ping/all) will likely not work, so just use the proxies posted [here](https://github.com/tonikelope/megabasterd/tree/proxy_list) instead. Unfortunately, Mega Basterd still freezes for me when using those proxies after a while, so obviously the proxy method isn't perfect. If anyone has solutions for using a VPN though let me know. I haven't tried that yet.

**Comment by lfersan** [comment]
> Hello, you have reached the download limit imposed by MEGA. From here there are 4 possible **MITIGATIONS** (none perfect or definitive):
> 
> 1. WAIT for MEGA to let you download again (usually 6/12 hours).
> 2. Pay for a MEGA PRO account.
> 3. Use proxies (Settings -> Downloads -> SmartProxy and paste your proxy list) -> https://github.com/tonikelope/megabasterd/tree/proxy_list (Remember
> 4. Use a VPN
> 
> Regards.

Is the proxy list for HTTP, HTTPS or SOCKS4/4a/5?

**Comment by Ravn73** [comment]
Do i have to Port Foward the proxys in my router so that they work?

**Comment by blankxwbpzip** [comment]
> > Hello, you have reached the download limit imposed by MEGA. From here there are 4 possible **MITIGATIONS** (none perfect or definitive):
> > ```
> > 1. WAIT for MEGA to let you download again (usually 6/12 hours).
> > 
> > 2. Pay for a MEGA PRO account.
> > 
> > 3. Use proxies (Settings -> Downloads -> SmartProxy and paste your proxy list) -> https://github.com/tonikelope/megabasterd/tree/proxy_list (Remember
> > 
> > 4. Use a VPN
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Regards.
> 
> Sadly doesn't work for me (proxylist way)



how if i usde socks5 proxy from ipvanish 
how i can fill the username and password

**Comment by kelvinjoxe** [comment]
![megabasterd](https://user-images.githubusercontent.com/53129028/176104848-6e5ecac6-bb15-4987-b8b9-45eb175a6558.png)
immediately after reaching 4gb download my speed start deteriorating @tonikelope might be the problem

one more question is it safe to exit megabasterd without waiting for transferences to be stopped safely
thankyou

**Comment by mritunjay-1** [comment]
I tried each and every method but none of them work for me.
If any one have solution for this kindly tell me please.

**Comment by DeathCounter001** [comment]
Using proton VPN helps
It lets u download till 5 GB  thennnn
U just have to re-select the vpn among the list of many 
to get reset your download limit. Then repeat

**Comment by ObviousNiNi** [comment]
What I'm doing is search a bunch of proxy list, every time it stops I change the list and restart. It downloads 3-4GB and stop, so change list and restart, and so on. 

I've tried Proton VPN thing and idk why it doesn't work for me, never continues with the downloading, even after restart. (tried bunch of vpns and proton doesn't work at all, but others get an slightly improvement.) But the improvement is from 0/B to 100-120 KBS. Without the VPN and doing the proxy thing I've mentioned I got this: 

![image](https://user-images.githubusercontent.com/112665036/197062899-706728b8-eab6-41c2-8fe6-2a48514e36fa.png)

Hope it helps? Ah btw sometimes I can download 16gb without changing the list, and other times I need to change it like 5 or 6 times. Sometimes I need to change the list several times before it actually starts the download.

**Comment by binnichtaktiv** [comment]
> What I'm doing is search a bunch of proxy list, every time it stops I change the list and restart. It downloads 3-4GB and stop, so change list and restart, and so on.
> 
> I've tried Proton VPN thing and idk why it doesn't work for me, never continues with the downloading, even after restart. (tried bunch of vpns and proton doesn't work at all, but others get an slightly improvement.) But the improvement is from 0/B to 100-120 KBS. Without the VPN and doing the proxy thing I've mentioned I got this:
> 
> ![image](https://user-images.githubusercontent.com/112665036/197064516-353c7474-9a31-42c5-9448-8fcb6c5f78d3.png)
> 
> Hope it helps? Ah btw sometimes I can download 16gb without changing the list, and other times I need to change it like 5 or 6 times. Sometimes I need to change the list several times before it actually starts the download.

where do you find the proxy lists?

**Comment by Optinux** [comment]
> where do you find the proxy lists? And are they free or paid?

https://github.com/tonikelope/megabasterd/blob/proxy_list/proxy.txt

**Comment by fluffisch** [comment]
you all need some big proxy list for good results, thats the magic.
I can download stuff at almost full speed, thanks for developing this!

**Comment by RadiantDarsh** [comment]
> you all need some big proxy list for good results, thats the magic. I can download stuff at almost full speed, thanks for developing this!

FROM WHERE YOU GET BIG PROXY LIST PLEASE TELL ME

**Comment by tonikelope** [comment]
> > > where do you find the proxy lists? And are they free or paid?
> > 
> > 
> > https://github.com/tonikelope/megabasterd/blob/proxy_list/proxy.txt
> > they are updated every hour or so
> 
> can I just paste the proxy url in smartproxy? or do I have to format it in some way? the example under smartproxy says #PROXY_LIST_URL does that mean: #https://github.com/tonikelope/megabasterd/blob/proxy_list/proxy.txt or without hashtag?

(A "direct" url to txt file is required).

For example

`#https://raw.githubusercontent.com/tonikelope/megabasterd/proxy_list/proxy.txt`

**Comment by fluffisch** [comment]
Better you do a quik Proxy scan of that lists, too.
These lists are often rescanned multiple times per hour, but you dont know from where.
So you need to be sure that these proxys are working from your location, or the downloader will try many connection atemps that dont will work and will result in much CPU and RAM Usage. So Download these lists and rescan em your self, then you can use em right. As Example:

Crawled all lists => 17.000 Proxys 
remove duplicates => 7.000 Proxys
Rescan without http:=> 640 Proxys

Megabasterd goes BRRRRRRR

**Comment by virtualcrane** [comment]
> > > > where do you find the proxy lists? And are they free or paid?
> > > 
> > > 
> > > https://github.com/tonikelope/megabasterd/blob/proxy_list/proxy.txt
> > > they are updated every hour or so
> > 
> > 
> > can I just paste the proxy url in smartproxy? or do I have to format it in some way? the example under smartproxy says #PROXY_LIST_URL does that mean: #https://github.com/tonikelope/megabasterd/blob/proxy_list/proxy.txt or without hashtag?
> 
> (A "direct" url to file is required).
> 
> In your example URL (# is required):
> 
> `#https://raw.githubusercontent.com/tonikelope/megabasterd/proxy_list/proxy.txt`

after adding proxy URL, the download does not start.

**Comment by Jake186** [comment]
@virtualcrane where is the link to the version 7.70?

**Comment by DAPakaDAPPER** [comment]
@tonikelope How can i contact you outside of Github
I have something to share/Discuss
Topic: MEGA PERMANENT LINK.

**Comment by DAPakaDAPPER** [comment]
> @tonikelope How can i contact you outside of Github I have something to share/Discuss Topic: MEGA PERMANENT LINK.

i hv sent an email.
Please Read.

**Comment by FutanariNekoChan** [comment]
some link just stuck on this step 
![изображение_2023-11-05_054851174](https://github.com/tonikelope/megabasterd/assets/48638267/11fbe985-120e-48bb-a2ee-587c87f6c31b)
i wait about 3 hour and nothing happen
![изображение_2023-11-05_054957992](https://github.com/tonikelope/megabasterd/assets/48638267/d1b0d6dd-605d-45de-b109-08c92fe73c1a)

**Comment by Lozt247** [comment]
@tonikelope is there a way of doing a rotating smart proxy list that refreshes every day or hour 
just curious that would be awesome

**Comment by LAKMAR123** [comment]
![1706499102655](https://github.com/tonikelope/megabasterd/assets/158209164/d7459e83-6799-45af-8995-de5f88a28654)

**Comment by Vultrex111** [comment]
i was thinking what makes megabasterd fast, is it because of proxies or what? Thanks

**Comment by dharmveerjakhar** [comment]
https://github.com/TheSpeedX/PROXY-List
try this ^^
