### ISSUE TITLE
'Folder link detected!' freezes app and does not allow downloading

### ISSUE THREAD

**Issue by tudor-ghidarcea** [tonikelope/megabasterd#388]
Hello! I am facing an issue, where everytime i type in a link (tried on first and latest build) it gives me "folder link detected" popup, but is stuck on root and does not allow me to do anything, it just says loading forever. My cpu fan also starts blastig every time this happens. I tried formatting the link in the old and new standard, even tho the app reformats it automatically, just in case it is a link thing but it is not. Any help would be greatly appreciated!

**Comment by thesmartdeveloperr** [comment]
@tudor-ghidarcea same problem i am facing? can you help??
