### ISSUE TITLE
MEGA account with 2FA support?

### ISSUE THREAD

**Issue by Sparoney** [tonikelope/megabasterd#39]
Hello,

When I try to login with my MEGA account that has 2FA enabled, it freezes the program with 'Checking your MEGA accounts, please wait...' because there is no option to enter a 2FA code.

Do you have any plans to implement this feature (if it even can be implemented)? Otherwise I will just disable 2FA no worries.

**Comment by tonikelope** [comment]
Try https://github.com/tonikelope/megabasterd/releases/tag/v5.81

Regards.

**Comment by Sparoney** [comment]
Thank you!
