### ISSUE TITLE
Multiple Bugs

### ISSUE THREAD

**Issue by kuspia** [tonikelope/megabasterd#392]
1. After pausing all downloads it gets stuck as shown and then there is no way to resume all downloads, IDK why this happens I have amazing internet speed and processor speed too.
![image](https://user-images.githubusercontent.com/63403330/154108896-4f4da135-1933-4245-b2d3-450e687a0bdf.png)

2. Despite trying with different high-speed proxies I can never download any single file, its annoying tbh can someone tell me what is the use of this tool or how we can overcome this problem, I tried restarting, resetting, changing proxy lists multiple times but nothing works.

3. Also restarting takes a lot of time, it can never restart again 

![image](https://user-images.githubusercontent.com/63403330/154109606-4ca03d53-f587-45e9-8967-87e596897c54.png)

**Comment by masharia-john** [comment]
if its an old version update to fix the bug megaBasterd and also are you running megaBasterd on linux or windows

**Comment by coys1031** [comment]
I am not OP but same thing happens to me when I download.  I am using the most up to date version of the software, and using MacOS.

**Comment by tonikelope** [comment]
Pausing downloads is not an instantaneous process. Before marking the download as paused all workers have to finish downloading their current chunk. If the download is also using proxies this will take even longer.
