### ISSUE TITLE
Is there a way to hide or not see the .mb_chunks_ folders?

### ISSUE THREAD

**Issue by idgas01** [tonikelope/megabasterd#396]
Sorry for the noob question.  I love your program.  I am downloading some game creation tools and I have like a dozen or two .mb_chunk_ folders in the download location.  I was wondering if there was a way to hide them.  If not, it's cool.  Was just wondering.

**Comment by tonikelope** [comment]
Hi. Unfortunately it is not possible, but in advanced settings you can set
up a different folder to save all temporary chunks folders. Have a look at
it.

Regards.
