### ISSUE TITLE
Errors and Download Stopping

### ISSUE THREAD

**Issue by No1syB0y** [tonikelope/megabasterd#40]
![Capture](https://user-images.githubusercontent.com/25158559/54454206-f10cfb80-4726-11e9-991e-8983b767f8d0.PNG)

**Comment by fuckchina6489** [comment]
I have a similar issue where if I download anything (even if its smaller or bigger than 5gb), it'll stop and give out a fatal error saying that the program can't access this chunk because it's being used by another program.
