### ISSUE TITLE
No conecta con cuentas gmail con "puntos" en la dirección.

### ISSUE THREAD

**Issue by rocknard** [tonikelope/megabasterd#41]
Hola, te escribo en español porque así lo explico mejor (if you prefer on english, i will do xD).

Resulta que con google puedes crear cuentas con nombres como las siguientes:

h.o.l.a@gmail.com
ho.l.a@gmail.com
hol.a@gmail.com
hol.a.@gmail.com
....

Todas ellas hacen de "proxy" (?) con la original creada: hola@gmail.com. La cuestión es que puedo crear cuentas de MEGA con cada una de esas 4 que he puesto de ejemplo, pero al añadirlas al megabasterd, me salta un error. No entiendo por qué MEGA me deja crear la cuenta y el programa no me deja loguearme en ellas, solo en la "principal". Los emails que recibes, los recibe la cuenta principal, es decir, hola@gmail.com.

No sé si es porque el programa no soporta los "puntos" en las direcciones o es porque no se puede.

Saludos y gracias por el programa.

**Comment by tonikelope** [comment]
Hola. Pues es raro y no tiene sentido. Por si acaso, acabo de probar a crearme otra cuenta en Mega usando el truco de los puntos con mi cuenta habitual y he podido acceder desde MegaBasterd con la cuenta nueva y la antigua sin problemas. ¿Qué error te da?

**Comment by rocknard** [comment]
"checking your MEGA accounts, please, wait...".

Antes se me quedaba así cuando tenía más de una cuenta (1º la buena de zoho.mail y la 2º la que me da problemas).
Ahora cuando solo tengo la problemática (puedo loguearme correctamente en la cuenta en MEGA, pero no en el programa):

"There were errors with some accounts (emails and/or passwords are/is wrong). Please, check them:
e.j.empl.o@googlemail.com".

Estas cuentas las creé por "lotes" en una página, y veo que puedo registrarme con ellas en MEGA y usarlas en mi gestor de emails Thunderbird.

He creado una cuenta matriz en gmail, después he creado una cuenta en mega añadiéndole un punto a la cuenta inicial y he recibido el correo y la he activado, pero el programa megabaster me salta con ese error.

**Comment by rocknard** [comment]
Ok, ya he descubierto el "bug" que tiene el megabasterd:

Si activas la opción de "encriptar en el disco información sensitiva" y pones la clave y metes una cuenta con lo de los puntos, te salta el error ese, pero si desactivas eso, te va perfecto.

**Comment by tonikelope** [comment]
Vaya, qué raro porque yo tengo activada esa opción y me funcionaba y acabo de porbar a desactivarla y volver a añadir la cuenta con puntos y funciona... Pero está claro que algo raro hay porque te daba error. Lo revisaré a fondo en cuanto pueda, a ver si doy con el problema.

Sí, exportar incluye las cuentas.

Salu2 ;)

**Comment by rocknard** [comment]
Muestra varios comportamientos raros, relacionados con el establecimiento de la encriptación y de la cuenta MEGA en la misma sesión, sin antes guardar y volver a abrir la ventana.

Aquí he grabado unos gifs (jeje) que muestran el problema:

https://imgur.com/a/uXC48LN

**Comment by rocknard** [comment]
Tras añadir 7 cuentas con los de los puntos (sin tener la encriptación), todo ok. Ahora activo el encript, le pongo la clave, guardo y se queda en "checking" (las rejillas de passwords estaban en blanco).

**Comment by rocknard** [comment]
Añado un nuevo comportamiento extraño:

https://imgur.com/a/uXC48LN   (el tercer gif).

P.S.: le he dado a

**Comment by tonikelope** [comment]
Hola. He reseteado todos los ajustes y no soy capaz de reproducir los errores de los gifs. Me va a tocar revisarlo a fondo porque puede ser alguna condición de carrera y eso suele ser complicado de debugear... Muchas gracias por las molestias que te has tomado. Si no te importa ayudarme un poco más, ¿podrías ejecutar la aplicación desde una línea de comandos y pegarme lo que te salga cuando te de esos errores? Es por intentar tener más información... 

Gracias!

**Comment by rocknard** [comment]
Estas son mis especificaciones:

Windows XP SP3 (build 2060.xpsp_sp3_qfe.130704-0421) Service Pack 3
Java RE 1.8.0_152-b16  (última versión para windows xp que es instalable vía .exe creo).

En realidad he podido ver que es problema del Java antiguo que tengo, ya que me dio por hacer una instalación "no oficial" a la Java RE 1.8.0_201-b09 y ya no me hace esos problemas.

Respecto a la "consola java", no tengo forma de sacarla incluso activándola en opciones avanzadas. ¿Tal vez me hace falta instalar el JDK en vez del JRE? Puedo probarlo, porque la verdad es que tengo curiosidad por ver la consola, ya que hubo un tiempo en el que me iba. Probaré.

**Comment by tonikelope** [comment]
Hola! Windows XP! El mejor SO de Microsoft. Lástima que tengan que vender
los nuevos ...

Me temía que fuera algo de Java. La consola me refiero a ejecutar por
CMD.exe

java -jar MegaBasterd.jar

Salu2 ;)

**Comment by rocknard** [comment]
Dios, no entiendo por qué ahora sí me sale lo de la consola O_o

Microsoft Windows XP [Versión 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.

G:\Documents and Settings\angel>c:

C:\>cd C:\Downloads\[Jdownloader Descargas]\MEGA Gestor de descarga

C:\Downloads\[Jdownloader Descargas]\MEGA Gestor de descarga>java -jar MegaBaste
rd.jar
Error: Unable to access jarfile MegaBasterd.jar

C:\Downloads\[Jdownloader Descargas]\MEGA Gestor de descarga>java -jar MegaBaste
rd_5.94.jar
mar 18, 2019 6:41:22 PM com.tonikelope.megabasterd.SettingsDialog$24 run
GRAVE: null
javax.crypto.IllegalBlockSizeException: Input length must be multiple of 16 when
 decrypting with padded cipher
        at com.sun.crypto.provider.CipherCore.prepareInputBuffer(CipherCore.java
:1005)
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:848)
        at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
        at javax.crypto.Cipher.doFinal(Cipher.java:2164)
        at com.tonikelope.megabasterd.CryptTools.aes_cbc_decrypt_pkcs7(CryptTool
s.java:118)
        at com.tonikelope.megabasterd.SettingsDialog$24.run(SettingsDialog.java:
2210)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThre
ad.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.
java:116)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.
java:109)
        at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
        at java.awt.Dialog.show(Dialog.java:1084)
        at java.awt.Component.show(Component.java:1671)
        at java.awt.Component.setVisible(Component.java:1623)
        at java.awt.Window.setVisible(Window.java:1014)
        at java.awt.Dialog.setVisible(Dialog.java:1005)
        at com.tonikelope.megabasterd.MainPanelView.settings_menuActionPerformed
(MainPanelView.java:845)
        at com.tonikelope.megabasterd.MainPanelView.access$1400(MainPanelView.ja
va:42)
        at com.tonikelope.megabasterd.MainPanelView$18.actionPerformed(MainPanel
View.java:572)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:20
22)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.jav
a:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel
.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259
)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:8
42)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMen
uItemUI.java:886)
        at java.awt.Component.processMouseEvent(Component.java:6539)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6304)
        at java.awt.Container.processEvent(Container.java:2239)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904
)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)

        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
        at java.awt.Container.dispatchEventImpl(Container.java:2283)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThre
ad.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.
java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThre
ad.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)

        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by tonikelope** [comment]
Es algún problema de Java que no lee bien la contraseña de la tabla y salta luego error al descifrarla. Si se te soluciona actualizando Java, lo damos por zanjado.

Un saludo.

**Comment by rocknard** [comment]
No lo sé si con el nuevo java lo soluciona, voy a probar un poco más.

**Comment by rocknard** [comment]
Pues sí, me he asegurado de que ejecutaba el JAVA.exe de la versión última 1.8.0.209 y me lo sigue haciendo:

```
Microsoft Windows XP [Versión 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.

G:\Documents and Settings\angel>java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) Client VM (build 25.201-b09, mixed mode)

G:\Documents and Settings\angel>G:\Archivos de programa\Java\jre1.8.0_201\bin\ja
va.exe -jar C:\Downloads\[Jdownloader Descargas]\MEGA Gestor de descarga\MegaBas
terd_5.94.jar
"G:\Archivos" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Documents and Settings\angel>cd G:\Archivos de programa\Java\jre1.8.0_201\bin
\java.exe -jar C:\Downloads\[Jdownloader Descargas]\MEGA Gestor de descarga\Mega
Basterd_5.94.jar
El nombre de archivo, directorio o etiqueta del volumen no es válido.

G:\Documents and Settings\angel>G:\Archivos de programa\Java\jre1.8.0_201\bin\ja
va.exe -jar C:\Downloads\[Jdownloader Descargas]\MEGA Gestor de descarga\MegaBas
terd_5.94.jar
"G:\Archivos" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Documents and Settings\angel>G:\Archivos de programa\Java\jre1.8.0_201\bin\
"G:\Archivos" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Documents and Settings\angel>cd G:\Archivos de programa\Java\jre1.8.0_201\bin
\

G:\Archivos de programa\Java\jre1.8.0_201\bin>java -jar C:\Downloads\[Jdownloade
r Descargas]\MEGA Gestor de descarga\MegaBasterd_5.94.jar
Error: Unable to access jarfile C:\Downloads\[Jdownloader

G:\Archivos de programa\Java\jre1.8.0_201\bin>java.exe -jar Microsoft Windows XP
 [Versión 5.1.2600]
Error: Unable to access jarfile Microsoft

G:\Archivos de programa\Java\jre1.8.0_201\bin>(C) Copyright 1985-2001 Microsoft
Corp.
No se esperaba Copyright en este momento.

G:\Archivos de programa\Java\jre1.8.0_201\bin>
G:\Archivos de programa\Java\jre1.8.0_201\bin>G:\Documents and Settings\angel>ja
va -version
"G:\Documents" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>java version "1.8.0_201"
Error: no se ha encontrado o cargado la clase principal version

G:\Archivos de programa\Java\jre1.8.0_201\bin>Java(TM) SE Runtime Environment (b
uild 1.8.0_201-b09)
Error: no se ha encontrado o cargado la clase principal (TM)

G:\Archivos de programa\Java\jre1.8.0_201\bin>Java HotSpot(TM) Client VM (build
25.201-b09, mixed mode)
Error: no se ha encontrado o cargado la clase principal HotSpot(TM)

G:\Archivos de programa\Java\jre1.8.0_201\bin>
G:\Archivos de programa\Java\jre1.8.0_201\bin>G:\Documents and Settings\angel>G:
\Archivos de programa\Java\jre1.8.0_201\bin\ja
"G:\Documents" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>va.exe -jar C:\Downloads\[Jdownloa
der Descargas]\MEGA Gestor de descarga\MegaBas
"va.exe" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>terd_5.94.jar
"terd_5.94.jar" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>"G:\Archivos" no se reconoce como
un comando interno o externo,
""G:\Archivos"" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>programa o archivo por lotes ejecu
table.
"programa" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>
G:\Archivos de programa\Java\jre1.8.0_201\bin>G:\Documents and Settings\angel>cd
 G:\Archivos de programa\Java\jre1.8.0_201\bin
"G:\Documents" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>\java.exe -jar C:\Downloads\[Jdown
loader Descargas]\MEGA Gestor de descarga\Mega
"\java.exe" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>Basterd_5.94.jar
"Basterd_5.94.jar" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>El nombre de archivo, directorio o
 etiqueta del volumen no es válido.
"El" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>
G:\Archivos de programa\Java\jre1.8.0_201\bin>G:\Documents and Settings\angel>G:
\Archivos de programa\Java\jre1.8.0_201\bin\ja
"G:\Documents" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>va.exe -jar C:\Downloads\[Jdownloa
der Descargas]\MEGA Gestor de descarga\MegaBas
"va.exe" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>terd_5.94.jar
"terd_5.94.jar" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>"G:\Archivos" no se reconoce como
un comando interno o externo,
""G:\Archivos"" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>programa o archivo por lotes ejecu
table.
"programa" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>
G:\Archivos de programa\Java\jre1.8.0_201\bin>G:\Documents and Settings\angel>G:
\Archivos de programa\Java\jre1.8.0_201\bin\
"G:\Documents" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>"G:\Archivos" no se reconoce como
un comando interno o externo,
""G:\Archivos"" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>programa o archivo por lotes ejecu
table.
"programa" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>
G:\Archivos de programa\Java\jre1.8.0_201\bin>G:\Documents and Settings\angel>cd
 G:\Archivos de programa\Java\jre1.8.0_201\bin
"G:\Documents" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>\
"\" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>
G:\Archivos de programa\Java\jre1.8.0_201\bin>G:\Archivos de programa\Java\jre1.
8.0_201\bin>java -jar C:\Downloads\[Jdownloade
"G:\Archivos" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>r Descargas]\MEGA Gestor de descar
ga\MegaBasterd_5.94.jar
"r" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>Error: Unable to access jarfile C:
\Downloads\[Jdownloader
"Error:" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

G:\Archivos de programa\Java\jre1.8.0_201\bin>
G:\Archivos de programa\Java\jre1.8.0_201\bin>java -jar MegaBasterd_5.94.jar
mar 18, 2019 7:06:56 PM com.tonikelope.megabasterd.SmartMegaProxyManager _refres
hProxyList
INFORMACIËN: pool-1-thread-9 Smart Proxy Manager: proxy list refreshed (234)
mar 18, 2019 7:07:21 PM com.tonikelope.megabasterd.SmartMegaProxyManager _refres
hProxyList
INFORMACIËN: AWT-EventQueue-0 Smart Proxy Manager: proxy list refreshed (234)
mar 18, 2019 7:07:32 PM com.tonikelope.megabasterd.SmartMegaProxyManager _refres
hProxyList
INFORMACIËN: AWT-EventQueue-0 Smart Proxy Manager: proxy list refreshed (234)
mar 18, 2019 7:07:44 PM com.tonikelope.megabasterd.SmartMegaProxyManager _refres
hProxyList
INFORMACIËN: AWT-EventQueue-0 Smart Proxy Manager: proxy list refreshed (234)
mar 18, 2019 7:07:56 PM com.tonikelope.megabasterd.SmartMegaProxyManager _refres
hProxyList
INFORMACIËN: AWT-EventQueue-0 Smart Proxy Manager: proxy list refreshed (234)
mar 18, 2019 7:08:10 PM com.tonikelope.megabasterd.SmartMegaProxyManager _refres
hProxyList
INFORMACIËN: AWT-EventQueue-0 Smart Proxy Manager: proxy list refreshed (234)
mar 18, 2019 7:08:35 PM com.tonikelope.megabasterd.SmartMegaProxyManager _refres
hProxyList
INFORMACIËN: AWT-EventQueue-0 Smart Proxy Manager: proxy list refreshed (234)
mar 18, 2019 7:08:50 PM com.tonikelope.megabasterd.SmartMegaProxyManager _refres
hProxyList
INFORMACIËN: AWT-EventQueue-0 Smart Proxy Manager: proxy list refreshed (234)
mar 18, 2019 7:09:06 PM com.tonikelope.megabasterd.SettingsDialog$23 run
GRAVE: null
com.tonikelope.megabasterd.MegaAPIException: MEGA API ERROR: -9
        at com.tonikelope.megabasterd.MegaAPI._rawRequest(MegaAPI.java:482)
        at com.tonikelope.megabasterd.MegaAPI._realLogin(MegaAPI.java:149)
        at com.tonikelope.megabasterd.MegaAPI.login(MegaAPI.java:240)
        at com.tonikelope.megabasterd.SettingsDialog$23.run(SettingsDialog.java:
1775)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by tonikelope** [comment]
Le echaré un vistazo a esa parte cuando tenga un rato de todas formas. Gracias por las molestias que te has tomado.

Salu2 ;)
