### ISSUE TITLE
Where is the language file please I need to translate to Chinese

### ISSUE THREAD

**Issue by linkea131** [tonikelope/megabasterd#410]
Where is the language file please I need to translate to Chinese

**Comment by jeverling** [comment]
https://github.com/tonikelope/megabasterd/issues/397#issuecomment-1059940085

**Comment by linkea131** [comment]
[MEGABASTERD MULTI LANGUAGE TEMPLATE.txt](https://github.com/tonikelope/megabasterd/files/8675856/MEGABASTERD.MULTI.LANGUAGE.TEMPLATE.txt)

OK Translation completed Some translation errors will be checked and corrected in the next version you publish

**Comment by linkea131** [comment]
[MEGABASTERD.MULTI.LANGUAGE.TEMPLATE.txt](https://github.com/tonikelope/megabasterd/files/8676315/MEGABASTERD.MULTI.LANGUAGE.TEMPLATE.txt)

OK Thanks Translation completed Some translation errors will be checked and corrected in the next version you publish

**Comment by xepo12** [comment]
中文有乱码啊

**Comment by linkea131** [comment]
> 中文有乱码啊

修改了下文本编码 重新上传了 等作者下一个版本更新了 在看看

**Comment by linkea131** [comment]
@bovirus @tonikelope

Please help to solve the Chinese garbled problem Thank you

https://ru.xdnsw.xyz/garbled.png

**Comment by linkea131** [comment]
> 中文有乱码啊

和作者反馈了 修改了下编码重新上传了一个

**Comment by linkea131** [comment]
> 中文有乱码啊

![garbled2](https://user-images.githubusercontent.com/50718406/174442968-b4e3705f-675a-41d6-91be-2a662abf6d3b.png)
经过我测试不乱哦

**Comment by linkea131** [comment]
> 中文有乱码啊

![garbled2](https://user-images.githubusercontent.com/50718406/174443511-43310c70-50b9-438e-89f6-320d8e0082e9.png)

经过我测试不乱哦 把Font项的DEFAULT改为ALTERNATIVE即可
