### ISSUE TITLE
Increased download speed from 60-100KB/s to 400-600KB/s using an alternative proxy list.

### ISSUE THREAD

**Issue by NoobInTheNet** [tonikelope/megabasterd#411]
Hello there community,

I am new here, first time using MegaBasterd. I must say, I am really enjoying it!

Nonetheless, I had to fight with the download setup for quite some time before I was able to download a significant amount of files. Even though @tonikelope proxy list is constantly updated and works great, I only got an average download speed of 50KB/s.

However, after doing some research, I discovered [this proxy list](https://www.megaproxylist.net/), which also appears to be constantly updated and is a little bit wider, and after incorporating it into the Smart Proxy list, I got an average download speed of around 200KB/s with peaks of 400 and 600 KB/s.

I would appreciate it if you could take a look at it and let me know if you think these proxies are suitable for long-term use with MegaBaster. Also, I was wondering if you have ever considered the possibility of the application automatically accessing a proxies repository (such as this repository's proxies.txt file) and fetching the most up-to-date proxies when it detects that a proxy is no longer working.

I hope my contribution was helpful; best regards:)

**Comment by DonPi-Boxer** [comment]
Would indeed be awesome if we can add a 'git-clone "proxy-list-url" ' command to the 'Run this command when download limit is reached'.
