### ISSUE TITLE
Found a "root" folder then error

### ISSUE THREAD

**Issue by Ravn73** [tonikelope/megabasterd#412]
Hi, the program finds a "root" folder and then gets an error. What i am downloads needs an encrypt key (what i have). 
Am i doing something wrong?
![Screenshot 2022-05-08 055005](https://user-images.githubusercontent.com/21908456/167281006-db4abc82-4a64-4ea2-9286-4b54dab24573.png)
![Screenshot 2022-05-08 055024](https://user-images.githubusercontent.com/21908456/167281010-fe301b47-38ef-4232-86ba-d4c0a3949251.png)

**Comment by tonikelope** [comment]
![Screenshot_20220602_112324](https://user-images.githubusercontent.com/1344008/171599388-e5a1eab8-b01d-48c6-a8ed-56ac50a106cd.png)
