### ISSUE TITLE
Download not Starting.

### ISSUE THREAD

**Issue by Naveenchikka** [tonikelope/megabasterd#416]
![image](https://user-images.githubusercontent.com/35519706/169690721-b4a242a3-8140-42cc-9b33-a8bc81878a68.png)
The download is not starting even though the root link is detected. I waited for 2 hours for folder with size 1.5-2 gb. download not starting, what to do?  I have added proxy vpns as well. Someone please help me.

**Comment by tonikelope** [comment]
https://mega.nz/folder/uagg3R6T#IPoVgiYP2BI_0ikf3uCXUw
