### ISSUE TITLE
could you make a AppImage for megabasterd?

### ISSUE THREAD

**Issue by chemel9** [tonikelope/megabasterd#42]
Hi, I really appreciate your work , is a very good application
could you make a AppImage for megabasterd?
in this way, users can install the application in any linux distribution

https://appimage.org/

**Comment by tonikelope** [comment]
Hello. I find that option interesting, but unfortunately I don't have time right now. However, for quite some time there has been the possibility to run MegaBasterd with docker -> https://github.com/JairoQuispe/docker-megabasterd-app 

Regards.

**Comment by tonikelope** [comment]
DONE!

**Comment by chemel9** [comment]
thanks :)
