### ISSUE TITLE
"Settings" window not closing after changes

### ISSUE THREAD

**Issue by rubenandre** [tonikelope/megabasterd#421]
Hello @tonikelope great project :)

I found a little issue that does not happen in the last versions (I'm using the last one).

The issue is: when I open the "settings" window and make some changes, for example, the destination folder, and click on the "Save" button, I cannot close the window after this. 

I found a workaround to solve this, that is in the main window click "Help" > "About" and after this I could close the secondary window.

**Comment by tonikelope** [comment]
Hi. I am not able to reproduce the error you comment in 7.54 When you press the button to save settings the dialog appears as usual and after accepting the settings window closes. could you upload a video with the error?

**Comment by rubenandre** [comment]
https://user-images.githubusercontent.com/9402773/173256410-5d21df23-cf7f-4ad8-b014-d29bdf2b63c2.mp4

**Comment by tonikelope** [comment]
Hi Ruben. Watching the video I can't understand what is happening to you. I
am not able to reproduce this bug, does it happen from any particular
version? Have you tried the MAC portable version? It's weird, really.

**Comment by rubenandre** [comment]
I cloned the repo and executed it, everything works as expected. I think this issue could be closed, very corner case here.
