### ISSUE TITLE
Aplicar en tiempo real "Slots por archivo por defecto" (requiere reiniciar)

### ISSUE THREAD

**Issue by rocknard** [tonikelope/megabasterd#43]
Hola, Tonikelope, vuelvo de nuevo.

Esta vez es para consultar si es así o es un comportamiento no esperado, me explico:

Si añado una carpeta con 30 archivos para subirla a MEGA (da igual si es una carpeta o si son 30 archivos) y tengo preconfigurado "Máximas subidas simultáneas"  en 1, todos los archivos se descargar uno por uno, incluso si a posteriori lo cambiase a 2, el cambio se haría en tiempo real en la sesión de subida (perfecto); ahora bien, si hago esto mismo con "Slots por archivo por defecto", no me lo respeta y me veo obligado a tener que cerrar la aplicación y volverla a abrir para que se aplique a las subidas que tengo en cola.

Bueno, eso es todo.

Saludos.

P.S.: espero que no sea cosa de mi java otra vez, porque con "Máximas subidas simultáneas" sí va.

**Comment by tonikelope** [comment]
Hola. No, esta vez no es cosa de Java. La funcionalidad que comentas no existe. Se podría implementar de tal forma que al cambiar el valor por defecto de slots en ajustes actualizara todas las descargas en cola y en ejecución (estas últimas que no haya sido modificado el número de slots manualmente). Si tengo un hueco lo meteré. Tomo nota de la sugerencia.

Salu2 ;)

**Comment by tonikelope** [comment]
He modificado el comportamiento. A partir de ahora, las transferencias que se inicien (en cola previamente o directamente añadidas), leerán el valor actualizado del número de slots por defecto. (Las que estén en ejecución en el momento de cambiar ese valor no cambiarán el número de slots).

Salu2 ;)
