### ISSUE TITLE
WARNING: File too large

### ISSUE THREAD

**Issue by ThorPham** [tonikelope/megabasterd#436]
I completed download but warning live this how to fix .Thank you.
Jul 04, 2022 2:14:52 PM com.tonikelope.megabasterd.ChunkWriterManager run
WARNING: File too large
Jul 04, 2022 2:14:53 PM com.tonikelope.megabasterd.ChunkWriterManager run
WARNING: File too large
Jul 04, 2022 2:14:54 PM com.tonikelope.megabasterd.ChunkWriterManager run
WARNING: File too large

**Comment by tonikelope** [comment]
Example link?

**Comment by itswck** [comment]
@tonikelope I am also having this issue. The video download seems to complete, but the assembling of the chunks does not work. Any troubleshooting tips?
