### ISSUE TITLE
Add Temp Download Folder

### ISSUE THREAD

**Issue by Markhor123** [tonikelope/megabasterd#44]
Everything working perfectly :)
I just want a feature like IDM where chunks are created in one folder and final file in another one

PS: i don't know where to request for enhancements so i posted here.

**Comment by tonikelope** [comment]
Done. Chunks will be stored in a temp folder inside download dir and it will be automatically deleted when the download is finished.

**Comment by Markhor123** [comment]
Thanks for implementing this so fast :O

But unfortunately this is not what i wanted :(.
I want a new option in Setting under Download folder

"Temp Folder".
This temp can be any folder on the disk other than the download dir and only the final file should go to the Download dir. Is it possible?

PS : It will really help me automate the setup i am currently using :)
