### ISSUE TITLE
[REQUEST] Different Temp Download Folder from the Final Download Directory 

### ISSUE THREAD

**Issue by Markhor123** [tonikelope/megabasterd#45]
Thanks for implementing the last enchantment so freaking fast :O But unfortunately this is not what i wanted :(. I want a new option in Setting under Download folder "Temp Folder". This temp can be any folder on the disk other than the download dir and only the final file should go to the Download dir. Is it possible? PS : It will really help me automate the setup i am currently using :)

**Comment by tonikelope** [comment]
That change takes more work and I don't have much time right now. When I can, I will study it.

**Comment by tonikelope** [comment]
Done. Check ADVANCED SETTINGS.

**Comment by Markhor123** [comment]
Dude Like seriously man. Thanks for everything
