### ISSUE TITLE
my download is stuck in 80% for 3 days

### ISSUE THREAD

**Issue by Zero0Alex** [tonikelope/megabasterd#460]
![image](https://user-images.githubusercontent.com/113265896/189503255-6ae7f3e3-f5f0-4ef1-8c0e-684bb3ce0090.png)
the download was extremely slow but when it reached 80% it just doesn't go anymore, I changed the proxies every day I always keep it up to date

**Comment by whitenoisy** [comment]
The download limit has reached for the day. This happens even with proxies enabled. You can either wait for around 6 hrs or so for the download limit cooldown or close the app and start it again with VPN enabled.

**Comment by Zero0Alex** [comment]
> The download limit has reached for the day. This happens even with proxies enabled. You can either wait for around 6 hrs or so for the download limit cooldown or close the app and start it again with VPN enabled.

not only that day ... i waited for at least 1 week and gave up
