### ISSUE TITLE
All downloads stop at 100% and dont complete

### ISSUE THREAD

**Issue by jimmbo8** [tonikelope/megabasterd#468]
This behavior just started happening.

Downloads reach 100% and just stay at 100%, they don't fully finish. 

The downloads in the folder are still MCTEMP files. 

![broke mb2](https://user-images.githubusercontent.com/116605366/197645961-a2089564-5676-4e03-8bba-8925998a7f14.PNG)

I still have connection, my other downloads are running fine. Ive left these for days and they stay at 100% never completing.

**Comment by tonikelope** [comment]
Log file?

**Comment by jimmbo8** [comment]
> Log file?

Sorry for the long reply on this. I figured out the problem. Its on my end. When adding a large volume of files (especially large files), megaB will rotate the files being downloaded before they are completed and the chunks joined.

This resulted in many files downloading ~80% and then being sent to the bottom of the download queue before they could finish and be transferred to my servers, and it slowly filled up my local storage to the point that there was no free space to finish joining the chunks so everything just sat at 100%.
