### ISSUE TITLE
¿Que módulo java usa MegaBasterd para abrir DLC?

### ISSUE THREAD

**Issue by DrW3b** [tonikelope/megabasterd#47]
Estoy intentando configurar una versión portable con java incluido, uso OpenJDK https://aws.amazon.com/es/corretto/ y https://justinmahar.github.io/easyjre/ pero debe faltarme algun módulo porque cuando intento abrir un archivo DLC no carga. Todas las demás funciones del programa funcionan correctamente.

**Comment by tonikelope** [comment]
You can read the code here:

 megabasterd/src/main/java/com/tonikelope/megabasterd/CryptTools.java (line 494)

Nothing special. 

Regards.
