### ISSUE TITLE
doesn't download nothing

### ISSUE THREAD

**Issue by Triramama** [tonikelope/megabasterd#476]
wtf pendejo transfers stay still without doing shit, i did input the key and logged my ass in, can your brown hands fix this or help me?
[image](https://user-images.githubusercontent.com/97356540/201280077-d7324282-5fbb-44df-a492-efe97f464ae8.png)

**Comment by dasauto1** [comment]
> wtf pendejo transfers stay still without doing shit, i did input the key and logged my ass in, can your brown hands fix this or help me? 

Wow! Calling names? Really? You should return the money back that you paid for this app.
