### ISSUE TITLE
Is it possible to update the proxy list so it scrapes from a .txt rather than manually pasting in the proxies?

### ISSUE THREAD

**Issue by jimmbo8** [tonikelope/megabasterd#487]
Is it possible to have the proxy list from the program  pull directly from a .txt ?

My proxy lists, like most if not all of you, are rotated and updated very frequently. I pull them from a source which is hosted in a raw .txt format, which i just copy and paste into megaB proxy list.

This list is updated far more frequently than i can even manually update myself.

Is it possible to automate this? It would be so handy to simply paste the location (hyper link) of the proxy list that is frequently updated into the program (instead of the raw proxies), and the program will simply ping this list and scrape the new proxies periodically?

**Comment by tonikelope** [comment]
Example URL -> https://pastebin.com/raw/M1rkDwK5

Dont forget # before

`#https://pastebin.com/raw/M1rkDwK5`

**Comment by bannisdale** [comment]
Has anyone tested this successfully yet? As far as I can see, there is no way to see if the list is actually applied. The downloads indicate that it isn't.
