### ISSUE TITLE
Why is it not starting 

### ISSUE THREAD

**Issue by Dreamkid123** [tonikelope/megabasterd#492]
![image](https://user-images.githubusercontent.com/121536470/209763108-7472a9e2-aa1c-4d93-aa83-4767e9681b0b.png)

What to do it is not starting. @tonikelope

**Comment by lagait** [comment]
+
I have the same problem.
upd: now there is no error, the program just does not start

**Comment by lagait** [comment]
here it helped
1. I downloaded java https://www.java.com/ru/
2. and also downloaded Java SE Development Kit 19.0.2 downloads
https://download.oracle.com/java/19/latest/jdk-19_windows-x64_bin.msi
3. open MegaBasterd.jar using java
