### ISSUE TITLE
LINK GRABBER KEEPS GRABBING SAME LINK AGAIN AND AGAIN IT DONT STOP

### ISSUE THREAD

**Issue by RadiantDarsh** [tonikelope/megabasterd#493]
![Screenshot 2022-12-31 174625](https://user-images.githubusercontent.com/120657837/210136441-6c125ba3-638d-4a29-ba6d-210fc9d33640.png)

PLEASE SOLVE THIS ISSUE OR TELL ME SOME SOLUTION

**Comment by tonikelope** [comment]
What OS do you use? Java version? Portable version? Docker?

**Comment by RadiantDarsh** [comment]
> Java version

I USE MISCROSOFT WINDOWS 11

**Comment by tonikelope** [comment]
![Screenshot_20221231_165606](https://user-images.githubusercontent.com/1344008/210148908-02df10a8-95aa-43b5-b096-b496e7cc81a2.png)

There are problems with the clipboard grabber on some platforms. Unfortunately I don't have time to test Megabasterd thoroughly on each of them (I use ArchLinux and everything works fine). I have put the option to disable it. I hope it will be useful. 

Regards.
