### ISSUE TITLE
Version 2.75 - Miss a lot of enhancemnts about languages

### ISSUE THREAD

**Issue by bovirus** [tonikelope/megabasterd#498]
@tonikelope 

Thanks for new version.

You forgot to apply many enhancements about languages

**_Italian language_** 

Italian language contains the same errors that I repeorted.
I dientifeid some strings not transdlated and I added it.
And I posted a new language file.
But you don't use it.

**New German/Hungarian/Vietnamese languages**

The translators post new language files for

German
Hungarian
Vietnamese

but you don't add it

The translator spent time to do it.
i created a temporary build (jat file) to test it but you don't add to teh finale reelase.
What's the matter?

**Comment by tonikelope** [comment]
Hi. No, I have not forgotten about translations. In the first new year update I asked for help to COLLECT and REVIEW ALL new translations here https://github.com/tonikelope/megabasterd/issues/397

If you can help me to review all the pending translations and put them together in one pastebin.com (also reviewing any new phrases that have been added in the last updates).

Thanks.

**Comment by bovirus** [comment]
@tonikelope 

I will check in next day to align translation fiels.

Please cosndier if you can to have separate language files for each language.

Could be better to maintain them.

Thanks.

**Comment by bovirus** [comment]
@tonikelope 

Here all language aligned as number of strings.
Your original languag file has 256 strings ()many missing).
New language files ahve 305 strings.
Please use it to update as soon as the source code.

[Language_Chinese.txt](https://github.com/tonikelope/megabasterd/files/10367944/Language_Chinese.txt)

[Language_English.txt](https://github.com/tonikelope/megabasterd/files/10367945/Language_English.txt)

[Language_German.txt](https://github.com/tonikelope/megabasterd/files/10367946/Language_German.txt)

[Language_Hungarian.txt](https://github.com/tonikelope/megabasterd/files/10367947/Language_Hungarian.txt)

[Language_Italian.txt](https://github.com/tonikelope/megabasterd/files/10367948/Language_Italian.txt)

[Language_Spanish.txt](https://github.com/tonikelope/megabasterd/files/10367949/Language_Spanish.txt)

[Language_Turkish.txt](https://github.com/tonikelope/megabasterd/files/10367950/Language_Turkish.txt)

[Language_Vietnamese.txt](https://github.com/tonikelope/megabasterd/files/10367951/Language_Vietnamese.txt)
