### ISSUE TITLE
I've changed the font from default to alternative and it only shows two folders. Any fix for this?

### ISSUE THREAD

**Issue by Rogus** [tonikelope/megabasterd#50]
Since I've changed in settings the font from default to alternative just to see the difference and now it only shows two folders in the app how to undo this?. Thanks in advance and I using the jar executable file on windows 10 1809 version

**Comment by Rogus** [comment]
I've fixed by deleting the .megabasterd.6.8 folder, thanks

**Comment by Pein1911** [comment]
I cant find that folder to delete it, where is it at ?

**Comment by Pein1911** [comment]
> I've fixed by deleting the .megabasterd.6.8 folder, thanks

I cant find that folder to delete it, where is it at ?
