### ISSUE TITLE
[Request] Can i run this on linux terminal? Is there a cli for this?

### ISSUE THREAD

**Issue by Markhor123** [tonikelope/megabasterd#51]

**Comment by tonikelope** [comment]
"All" Linux (Java JDK required):
$ chmod +x ./MegaBasterdLinux_6.8.run
$ ./MegaBasterdLinux_6.8.run

No Java JDK install required (64bits only):
$ chmod +x ./MegaBasterdLinux_6.8-x86_64.AppImage
$ ./MegaBasterdLinux_6.8-x86_64.AppImage

**Comment by Markhor123** [comment]
I am actually running a headless linux debian strech. How can i run this with cli?

**Comment by tonikelope** [comment]
Try https://en.wikipedia.org/wiki/Xvfb and run MegaBasterd via ssh.

**Comment by Markhor123** [comment]
I am running the linux in google cloud vm instance. i'm a little new to linux. can you explain it in simple words

Can i run this on linux terminal on google cloud virtual machine?

**Comment by tonikelope** [comment]
Yes, it's possible.

1) Download the .appimage version

From here it depends on whether you use Windows or Linux to connect to the Google instance.

WINDOWS:

2) If you use Windows on your computer install these two programs (putty and xming) http://www.geo.mtu.edu/geoschem/docs/putty_install.html 

and connects to the instance.

LINUX:

2) https://unix.stackexchange.com/questions/12755/how-to-forward-x-over-ssh-to-run-graphics-applications-remotely


IN BOTH CASES, MegaBasterd will run in the remote instance but you will see the program window on your local computer.

Translated with www.DeepL.com/Translator

**Comment by Markhor123** [comment]
Great. I will try this and give a reply

**Comment by Markhor123** [comment]
I really really appreciate you being so helpful to me but i tried everything it didn't worked.

Please please Can i use it directly in the Terminal with commands like

getmega https://mega.nz/etc

**Comment by tonikelope** [comment]
> I really really appreciate you being so helpful to me but i tried everything it didn't worked.
> 
> Please please Can i use it directly in the Terminal with commands like
> 
> getmega https://mega.nz/etc

Hi. No, It doesn't work that way. The closest you can get to what you're saying is https://github.com/tonikelope/megadown but it DOES NOT jump the bandwidth limit, sorry.

Regards.
