### ISSUE TITLE
[bug] Pasting more than one link in the Link Grabber doesn't seem to work

### ISSUE THREAD

**Issue by Nanodragon999** [tonikelope/megabasterd#53]
So after some experiment, i noticed that pasting more than one link in the "Link Grabber" window resulted in all except the first link to be discarded (not downloaded from, ignored)

I only tried with folder links so far, i tried different type of formatting but no luck there either.
I tried using the DLC loader, but it seems it does the same there too, and only download from the first link, and even when it finish, never start with the other one.

I can send a test DLC/list of links for you to test if you want.

**Comment by Nanodragon999** [comment]
I always use the latest version, only tried the appimage so far, on ubuntu bionic

**Comment by tonikelope** [comment]
Hi! Could you paste here example links that you have tried?

Thank you.

PS: please, to debug run MegaBasterd from console.
