### ISSUE TITLE
Freezes after downloading 20 GB of data

### ISSUE THREAD

**Issue by kukosek** [tonikelope/megabasterd#54]
When it downloads about 15-22 GB of data, the whole process freezes and i must always close it by killing java. I have enough RAM, so I wonder where the problem is.
My java version:

> openjdk 11.0.3 2019-04-16
> OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
> OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)

**Comment by tonikelope** [comment]
Please run it from the command line to see what error pops up in those freezes.
