### ISSUE TITLE
MegaBasterd no descarga en absoluto

### ISSUE THREAD

**Issue by alexdittoz** [tonikelope/megabasterd#55]
![Captura](https://user-images.githubusercontent.com/51737899/59331321-4e2e3400-8cb9-11e9-9f6c-f60483499e17.PNG)
Reconoce el link y todo pero cuando se debe empezar la descarga aparecen muchos errores, Error 1, Error 9, Error 8, Error 6, Error 4, Error 3, Etc... Y nunca muestra la velocidad de descarga.

**Comment by tonikelope** [comment]
¿Puedes poner aqui el enlace que intentas descargar?

Gracias.

**Comment by alexdittoz** [comment]
Este es: https://mega.nz/#!h1d3AChQ!Tbny74PY9iD-vjGS6GQVAYFaCOgIP9gqx5gqA1TTub0

**Comment by tonikelope** [comment]
![Screenshot_20190612_220704](https://user-images.githubusercontent.com/1344008/59382790-ca2e8780-8d5e-11e9-9a1b-aeadb46075fe.png)
Viendo que la velocidad global está en naranja, habrás llegado al límite de descarga y ha empezado a tirar de proxies. Puede que hubiera algun problema con los proxies (a veces pasa que varios proxies van lentos y hasta que no da fallo el proxy no cambia y puede tardar). En esos casos se puede dejar la descarga o cerrar y volver a abrir MegaBasterd. De todas formas, le echaré un vistazo más a fondo cuando tenga un rato.
