### ISSUE TITLE
Deja de descargar

### ISSUE THREAD

**Issue by N4mc0** [tonikelope/megabasterd#56]
Funciona hasta cierto porcentaje y luego se detiene. Al probar luego con otro link directamente no descarga. He probado en dos redes diferentes y sucede lo mismo.

![Sin título](https://user-images.githubusercontent.com/51764363/59387220-005c0f00-8d3f-11e9-9a06-044698136778.png)

**Comment by jcvr1994** [comment]
![megabasterd](https://user-images.githubusercontent.com/43253672/59390525-2ed5ec00-8d37-11e9-8d32-9460584a98d4.jpg)

**Comment by tonikelope** [comment]
Hola. Parece ser cosa de los proxies. Tened en cuenta que el ancho de banda máximo de descarga a través d eun proxy es completamente INDETERMINADO y en función de la gente que los esté usando para descargar se reduce evidentemente. De todos modos, voy a revisar el módulo SmartProxy a ver si puedo meter alguna optimización. Cuando pasa eso, cancelar la descarga y reiniciarla (para que siga desde donde iba) ayuda a "refrescar" proxys "atascados". 

Siento no poder ser de más ayuda por el momento, pero lo investigaré y trataré de optimizarlo.

Salu2 ;)
