### ISSUE TITLE
Unable to create quick launch shortcut

### ISSUE THREAD

**Issue by bagajohny** [tonikelope/megabasterd#566]
I am trying to create a start menu shortcut on Windows 10 for megabasterd bat file. But I keep getting the error

![image](https://github.com/tonikelope/megabasterd/assets/101859073/c091cc0a-38a4-4ddf-86ff-01276ebbcb90)

I have followed the following guide

https://winaero.com/pin-a-batch-file-to-the-start-menu-or-taskbar-in-windows-10/

Please help me resolve the problem.

**Comment by Zhico** [comment]
@bagajohny 

Add this to the top of the MegaBasterd.bat file.

`CD /d %~dp0`

So it looks like this.

`CD /d %~dp0` 
`start jre\bin\javaw -jar jar\MegaBasterd.jar`

Then it should work. :)

**Comment by bagajohny** [comment]
> @bagajohny
> 
> Add this to the top of the MegaBasterd.bat file.
> 
> `CD /d %~dp0`
> 
> So it looks like this.
> 
> `CD /d %~dp0` `start jre\bin\javaw -jar jar\MegaBasterd.jar`
> 
> Then it should work. :)

It worked! Thank you so much.

**Comment by Zhico** [comment]
You're welcome. :)
