### ISSUE TITLE
megabasterd not streaming

### ISSUE THREAD

**Issue by Steveeeo** [tonikelope/megabasterd#57]
Hi,
Was wondering about this particular issue when the soft asks for a megalink of a video to stream and I paste it in, it will display the message to keep megabasterd running in the background to enable the streaming, which I do, but nothing happens. Does it associate with the default media player or I have to do it manually, if so how?
Thanks
Mike

**Comment by tonikelope** [comment]
The streaming link has to be opened in a video application that allows you to open URLs such as mplayer, VLC, Kodi, etc.
