### ISSUE TITLE
File cant be shared after upload

### ISSUE THREAD

**Issue by JohnnyVai6T9** [tonikelope/megabasterd#572]
Firstly, What is ELC account ??? i didn't put any account in that ELC section. My files are uploaded nicely but as i try to share the file, the person on the other end, cant open the files, because it asks for decryption key (which show to be incorrect when put). Then, tried sending the files in chat, it also doesnt work. Even i tried to go incognito & logging in the account it shows that this files cant be decrypted. But the files do open in the tab where i logged in in the first place. I've tried several times, but can't find any solutions ... Any help??????

**Comment by tonikelope** [comment]
https://github.com/tonikelope/megabasterd/releases/tag/v7.77
