### ISSUE TITLE
copy all url ??

### ISSUE THREAD

**Issue by koreanskater** [tonikelope/megabasterd#575]
How can I copy all the URLs without the need to log in with multiple accounts? I have many accounts, so it's not practical to log in to each of them individually. The folder option has been removed, and it's not practical to copy 150 URLs one by one. The "copy folder" feature was the best, but it has been taken away.

**Comment by koreanskater** [comment]
@tonikelope v7.76 continues to function smoothly with the folder option. I've been using it throughout the day without encountering any issues. I'm aware of the problem with shared folders, but it can be easily resolved by reloading the Mega account through the settings. For me, this isn't a significant issue as I save all my links in a text file. However, if there's any chance of having an option to enable folders, that would be greatly appreciated. I've experimented with MegaDoctor, but I noticed that the upload speed was much slower. Thanks for suggesting it, though.

**Comment by tonikelope** [comment]
I will add an option in settings to generate the folder link and show the button when the download is finished (at the user's own risk, because if MEGA touches something those files could get corrupted and become unusable). PS: Are you sure that the option to reload the account solves the decryption failure of the uploaded folder?

**Comment by koreanskater** [comment]
@tonikelope Thank you very much! 

This solution indeed rectifies the decryption problem. Here's what you need to do:
1.    Access the decrypted folder.
2.    Transfer the undecrypted files to your main drive (or create a new folder and move them there).
3.    In the dropdown menu, click "Reload your account."

I've used this method multiple times, and it consistently produces positive results.

**Comment by tonikelope** [comment]
Understood. I'll check it as soon as I have time and add what I commented before.

Thanks for the information and help.

**Comment by tonikelope** [comment]
https://github.com/tonikelope/megabasterd/releases/tag/v7.81

**Comment by koreanskater** [comment]
@tonikelope Thanks a lot, it's appreciated!

**Comment by koreanskater** [comment]
Issue resolved, closing.
