### ISSUE TITLE
SmartProxy doesn't work anymore

### ISSUE THREAD

**Issue by Auditormadness9** [tonikelope/megabasterd#576]
Downloads just stop after a while and won't resume. I have like a list of 994 proxies in it.

**Comment by Auditormadness9** [comment]
It just runs over the proxies once and doesn't go over them again unless you restart it. But you can't just restart the app every 10 seconds, it's annoying.

**Comment by tonikelope** [comment]
I do not understand. The proxies in the list are chosen randomly and the ones that fail are blocked for X seconds (or ignored altogether) and when there are no more proxies available you wait 30 seconds and refresh the list to start again.

**Comment by Auditormadness9** [comment]
I don't understand either. I put a huge amount of proxies and watch it burst into 200MB/s speed then slowly drop to 0 and halt, and after the so called 30 seconds it starts up again with like a very slow 3MB/s.

I have conducted a test using [Hola proxy](https://github.com/Snawoot/hola-proxy), put 10 endpoints (servers) in the list and launched them at those addresses, and watched in the cmd windows how Megabasterd only uses first random 4 (and each endpoint is around like 50 proxies) and then it stops, not using the rest until maybe 30 secs or 1 min. I have to constantly restart it to budge it.

Nevertheless, I don't understand how for 22GB download even 50 proxies isn't enough. Doesn't Mega allow 2GB per IP? That should mean 11 proxies should do the work, yet even thousands of them don't.

And I'm not talking about overscraped proxies, these are actual premium ones from stuff like Hola and Windscribe.

**Comment by tonikelope** [comment]
A proxy may work for browsing or downloading even but fail with MEGA. Not all are compatible and the only way is to test. Also, some may be blocked by MEGA itself or have exhausted the download bandwidth.

**Comment by Auditormadness9** [comment]
Yeah well I've seen the majority of them either throw error 509 (classic) or error 429 (too many concurrent ip addresses). But what bothers me the most is I don't understand how I can put such huge amount of proxies (PRIVATE proxies, so like, i login to windscribe and use fresh proxies from their very own servers) and they still manage to only hold on for like 30-60 secs before the speed goes back to 0b/s. Could it be that these IPs have also been used by others and credentials don't matter? I don't know at all.

**Comment by Auditormadness9** [comment]
![image](https://github.com/tonikelope/megabasterd/assets/71278545/5dd870de-e8c9-4363-a20b-e2ab8d7949e2)
very slow, any way i can filter out the fastest?

I honestly want to use [Hola proxy](https://github.com/Snawoot/hola-proxy) this with Megabasterd, but I have no idea why it stops halfway when Hola has such a huge amount of proxies and they're all fast.

**Comment by Auditormadness9** [comment]
![image](https://github.com/tonikelope/megabasterd/assets/71278545/b32fe7b8-a094-4c39-adf1-4cb6ccf50cb4)
For example it is in this state right now and it's not even using the proxy endpoints I gave it yet:
![image](https://github.com/tonikelope/megabasterd/assets/71278545/041625a5-07ef-400a-9bba-59da0e0b666d)

**Comment by Auditormadness9** [comment]
Also a lot of times when updating the proxy list, the program freezes. Cannot interact further without force-terminating via Task Manager.

**Comment by tonikelope** [comment]
7.85

1 second timeout it's too aggressive. I recommend 3 seconds and ban proxys. 

If you activate in advanced settings the log file you will be able to see the proxies that are blocked and the cause.

**Comment by Auditormadness9** [comment]
Ok I'll try.

And the setting that executes a command if it detects a 509, where does it execute? If it's like a cmd command, what directory does it run in?

**Comment by Auditormadness9** [comment]
Ok, tailed the log file in Notepad++, found what happens when the speed goes down to low or 0 values:

```
INFO: pool-4-thread-22 Worker [20] has FAILED downloading chunk [107]! \Audi\minaslepsec.mp4
Oct 16, 2023 3:04:25 AM com.tonikelope.megabasterd.ChunkDownloader run
SEVERE: Connection reset
Oct 16, 2023 3:04:25 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-21 Worker [19] has FAILED downloading chunk [83]! \Audi\minaslepsec.mp4
Oct 16, 2023 3:04:27 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-8 Worker [6] is downloading chunk [104]! \Audi\minaslepsec.mp4
Oct 16, 2023 3:04:27 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-13 Worker [11] is downloading chunk [106]! \Audi\minaslepsec.mp4
Oct 16, 2023 3:04:27 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-18 Worker [16] is downloading chunk [107]! \Audi\minaslepsec.mp4
Oct 16, 2023 3:04:28 AM com.tonikelope.megabasterd.ChunkDownloader run
SEVERE: Connection reset
Oct 16, 2023 3:04:28 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-18 Worker [16] has FAILED downloading chunk [107]! \Audi\minaslepsec.mp4
Oct 16, 2023 3:04:28 AM com.tonikelope.megabasterd.ChunkDownloader run
SEVERE: Connection reset
Oct 16, 2023 3:04:28 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-8 Worker [6] has FAILED downloading chunk [104]! \Audi\minaslepsec.mp4
Oct 16, 2023 3:04:28 AM com.tonikelope.megabasterd.ChunkDownloader run
SEVERE: Connection reset
Oct 16, 2023 3:04:28 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-13 Worker [11] has FAILED downloading chunk [106]! \Audi\minaslepsec.mp4
Oct 16, 2023 3:04:29 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-14 Worker [12] is downloading chunk [83]! \Audi\minaslepsec.mp4
Oct 16, 2023 3:04:29 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-20 Worker [18] is downloading chunk [107]! \Audi\minaslepsec.mp4
Oct 16, 2023 3:04:29 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-6 Worker [4] is downloading chunk [104]! \Audi\minaslepsec.mp4
Oct 16, 2023 3:04:30 AM com.tonikelope.megabasterd.ChunkDownloader run
SEVERE: Connection reset
Oct 16, 2023 3:04:30 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-20 Worker [18] has FAILED downloading chunk [107]! \Audi\minaslepsec.mp4
Oct 16, 2023 3:04:30 AM com.tonikelope.megabasterd.ChunkDownloader run
SEVERE: Connection reset
Oct 16, 2023 3:04:30 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-6 Worker [4] has FAILED downloading chunk [104]! \Audi\minaslepsec.mp4
Oct 16, 2023 3:04:30 AM com.tonikelope.megabasterd.ChunkDownloader run
SEVERE: Connection reset
Oct 16, 2023 3:04:30 AM com.tonikelope.megabasterd.ChunkDownloader run
INFO: pool-4-thread-14 Worker [12] has FAILED downloading chunk [83]! \Audi\minaslepsec.mp4
```

No idea what this means...

**Comment by tonikelope** [comment]
No Smart Prlxys errors in your log...

Do you have red numbers below slots spinner? This red numbers are failed slots (MEGA límits máximum paralell conections) 
Keep 10 slots max default in settings (smart proxy Will use 20)

**Comment by Auditormadness9** [comment]
> Do you have red numbers below slots spinner? This red numbers are failed slots (MEGA límits máximum paralell conections).

Omg yes I do, it appears a lot, and a lot of times the speed is in kb/s and in red. I have slots set at 20, maybe that's why?

**Comment by tonikelope** [comment]
Lower the default slots to 10 maximum and try downloading WITHOUT smart proxy. If no red slots appear leave it like that and if not go down one by one. 

When SmartProxy is triggered the "turbo mode" is activated with 20 slots to maximize the download speed. In that case, as each slot uses its own proxy it is much less likely that red slots will appear.

**Comment by Auditormadness9** [comment]
But without SmartProxy my actual IP will be 509'd after 2GB, then I should
enable SmartProxy yes? I already set it to 10, will test today

**Comment by MosoLila** [comment]
are these the red numbers and slots you are talking about?
![Screenshot 2023-10-20 180110](https://github.com/tonikelope/megabasterd/assets/148565925/53c807cb-9108-4293-8f22-714e029b7e14)
i already set it to 10 but it still shows 20 for some reason

**Comment by tonikelope** [comment]
> are these the red numbers and slots you are talking about? ![Screenshot 2023-10-20 180110](https://user-images.githubusercontent.com/148565925/276973169-53c807cb-9108-4293-8f22-714e029b7e14.png) i already set it to 10 but it still shows 20 for some reason

Hi. No, the red numbers appear below the slots (when some slot gives error, it is not usual). The number of slots you choose in settings is for direct download (without smart proxy). When SmartProxy is triggered, the slots are automatically increased to 20 (but for direct downloading the recommended number is between 6 and 10).

**Comment by sicarii0** [comment]
> A proxy may work for browsing or downloading even but fail with MEGA. Not all are compatible and the only way is to test. Also, some may be blocked by MEGA itself or have exhausted the download bandwidth.
> 
> You can give a try -> https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/http.txt

does this list updated regulary and where to find more proxies like this,  is there any website of this..?

**Comment by Auditormadness9** [comment]
App got significant updates that nullified every issue I faced with SmartProxy so far. GG, the author is really actively and effectively working on the app. I'll consider donating even once I am able to.
