### ISSUE TITLE
Nothing uploading since update

### ISSUE THREAD

**Issue by koreanskater** [tonikelope/megabasterd#588]
Hi,

I updated to the latest version 7.99 but always have Pre: number
![image](https://github.com/tonikelope/megabasterd/assets/147644345/483fa06d-68eb-48a2-8ee1-809819c52a9f)

It seems that nothing is loading. To the best of my knowledge, the last working version for upload was v7.88.

**Comment by tonikelope** [comment]
Sorry for the inconvenience. I've been making a lot of corrections and performance improvements and missed one thing. Fixed.

**Comment by koreanskater** [comment]
> Sorry for the inconvenience. I've been making corrections and performance improvements and missed one thing. Fixed.

Working perfect with the new version now. Thank you!
