### ISSUE TITLE
Lots of errors since 6.13 on windows 10?

### ISSUE THREAD

**Issue by Nobrumski** [tonikelope/megabasterd#59]
I just grabbed the 6.13 jar and I keep getting a ton of errors when trying to download files. I don't see any way on windows to run from source or view a log so not sure what info I can provide.

**Comment by tonikelope** [comment]
I don't know what might be happening in your case, but could you run .jar from CMD.exe to see if any Java error comes out?

Regards.

**Comment by Nobrumski** [comment]
I tried that but it looks like I may need Javac so when I get a chance I will install it. If I run the Jar from command it just launches the Windows program so I just see the GUI.

**Comment by tonikelope** [comment]
Hi. Those mistakes are normal for proxies. If any proxy gives timeout or is very slow it is blocked for 5 minutes. MEGA error 503 is because some files (temporarily) have limited simultaneous connections (usually to 10). 

Regards.
