### ISSUE TITLE
Application Stuck Loading on Pasting Link and Clicking 'Let's dance baby' for Large Mega Link

### ISSUE THREAD

**Issue by SaatoruGojo** [tonikelope/megabasterd#596]
When a link is pasted and  'Let's dance baby' is clicked, the application keeps loading and is unable to display the folder for selection or removal. Above, it shows 'File detected' for a 50 TB Mega link, while for smaller links, it works fine.

**Comment by tonikelope** [comment]
Send link by email please.

**Comment by SaatoruGojo** [comment]
Sent

**Comment by tonikelope** [comment]
Try 8.5

**Comment by SaatoruGojo** [comment]
yeah now its fine after 8.6

**Comment by beakwood** [comment]
This is also happening for me in v8.8. I let it load my link for 5 - 10 mins. The download is only 1.5gb. But it never added the folder to download. But, When I used v8.5, worked INSTANTLY. I'm using the java versions.

**Comment by tonikelope** [comment]
> This is also happening for me in v8.8. I let it load my link for 5 - 10 mins. The download is only 1.5gb. But it never added the folder to download. But, When I used v8.5, worked INSTANTLY. I'm using the java versions.

Link?
