### ISSUE TITLE
Wont run since Windows May update

### ISSUE THREAD

**Issue by brainwaster** [tonikelope/megabasterd#60]
Hi,

Since I updated to the latest major windows 10 update MB just doesnt run, it shows the splash screen and then thats it, the splash vanishes and no program. I've tried 6.11, 6.12 and now 6.13 all with the same result. I;ve tried the exe and jar for 6.13 also tried running as admin

**Comment by tonikelope** [comment]
Hi. I tested it on a Windows 10 with the May update and it starts up correctly. 
I don't know what might be happening in your case, but could you run .jar from CMD.exe to see if any Java error comes out?

Regards.

**Comment by brainwaster** [comment]
Hi,

I ran it from the command line and got the following error
![mberror](https://user-images.githubusercontent.com/52125446/59974924-a7e00980-95a9-11e9-938f-1f685d3c761c.JPG)

Cheers
Jason

**Comment by tonikelope** [comment]
It's weird. You get an error when checking if there is another instance of Megabasterd running. I have modified that piece of code so that in case of error it continues with the execution. Try version 6.14 for luck.

**Comment by brainwaster** [comment]
Hi,

Just tried  the exe and jar of 6.14 both work fine now, cheers for the help and quick fix
