### ISSUE TITLE
Megabasterd does not start downloads

### ISSUE THREAD

**Issue by ManuelMdza13** [tonikelope/megabasterd#61]
My problem is that when trying to download a file the program marks error and does not download, there are times when you start the download but then it locks in 44% for example and marks error again, try closing the program and opening it again and still the same. Help!

![11](https://user-images.githubusercontent.com/16968034/59981009-c9ea8380-95cb-11e9-9ee0-5355fe50d592.png)

**Comment by tonikelope** [comment]
Could you run .jar from CMD.exe to see if any Java error comes out?

Regards.

**Comment by Raiiber** [comment]
The same thing happens to me, I have already posted a similar problem, I hope early help

**Comment by tonikelope** [comment]
https://github.com/tonikelope/megabasterd/issues/59
