### ISSUE TITLE
A small problem or bug / Un Pequeño problema o Bug.

### ISSUE THREAD

**Issue by Raiiber** [tonikelope/megabasterd#62]
When you try to download some file, it jumps those errors and the download does not start, I hope soon, Greetings from Venezuela, Very good Project

Cuando se intenta descargar algun archivo salta esos errores y no comienza la descarga, espero pronto solucion, Saludos desde Venezuela, Muy buen Proyecto 

Screen: https://prntscr.com/o5wuz1

**Comment by tonikelope** [comment]
https://github.com/tonikelope/megabasterd/issues/59
