### ISSUE TITLE
8.17-18 broke everything

### ISSUE THREAD

**Issue by horusra** [tonikelope/megabasterd#626]
I went from 8.16 to 8.18 on windows (portable)
It didn't ask to import old settings, all settings were wiped. 
Now when I click "change it" to set default folder it doesn't do anything.
When I exit through file>exit it doesn't exit
somehow everything is completely broken.
right clicking the tray to press exit also doesn't exit it.

where does megabastard save all config data? I already deleted .megabastard17 and 18 folder in the user folder root but that doesn't fix it either. Downgrading to 8.17 also doesn't fix it.

what changed?

edit: downgrading to 8.16 fixed it. settings are back and the application actually works!
something is broken in version 8.17 and 8.18

**Comment by ransom1122** [comment]
Exact same issue with me. on both 818 and 817, it hard freezes the app, it says provisioning download and freezes

reverted back to 816 and its working
using 64bit portable

**Comment by tonikelope** [comment]
Try v8.20

**Comment by afonsopbarros** [comment]
8.20 also doesnt work for me, stuck on provisioning downloads, cant change download folder.
 used 8.16 and it works

**Comment by ransom1122** [comment]
I expoerted my save settings from 8.16... I Created a megabastered 8.20 folder, and dumped my megabasterd.db file from 8.16. Then I imported my saved settings from 8.16 and it works, a bit messy but it works

**Comment by tonikelope** [comment]
Please try v8.21

**Comment by pckrullenbol** [comment]
"v8.21 portable" is working for me (windows 11), thanks!

**Comment by tryal-hub** [comment]
I need help, I can't install the bat file. It says "windows cannot find 'jre\bin\javaw'.
