### ISSUE TITLE
MEGABASTERD_UPLOAD_LOGS folder on home directory

### ISSUE THREAD

**Issue by columndeeply** [tonikelope/megabasterd#628]
Hi! I updated to v8.17 a couple of days ago and now every time I open Megabasterd a folder named "MEGABASTERD_UPLOAD_LOGS" is created on my home directory even when "Create upload logs" is disabled on the settings.

Looking at the code I'm pretty sure the problem is this line here: https://github.com/tonikelope/megabasterd/blob/7a8f1d5ea348a5a88db3392ce77f1c63f3815b5f/src/main/java/com/tonikelope/megabasterd/MainPanel.java#L255

It creates the directory without checking if the setting to do so is enabled. This line was added on v8.16: https://github.com/tonikelope/megabasterd/commit/8ce5b11f85cfba8e64eba7df9e1ce9f722e242c4

**Comment by tonikelope** [comment]
Check  v8.20

**Comment by columndeeply** [comment]
My bad, didn't realize there were new releases. It's fixed on v8.20.
