### ISSUE TITLE
Bandwidth limit error

### ISSUE THREAD

**Issue by ManuelMdza13** [tonikelope/megabasterd#64]
Sometimes when I try to download MegaBasterd files, I get this error "Bandwidth limit error" and it does not let me download more for a few minutes

**Comment by Kuseru** [comment]
I can confirm that, but it only happened after I paused or restarted the download.

**Comment by ManuelMdza13** [comment]
I just start a download and it starts fine, but from time to time that error comes out, and in no time paused the download

**Comment by Noel-P3** [comment]
I have the same problem, Normally the discharge of more than 1Gb will not last more than 10 minutes but this warning or error of the download limit bothers a lot because it limits the download speed to very few Kb

**Comment by moisesal** [comment]
Same here, i just tried to download some movies and then it shows "Bandwidth limit error" after a few minutes

**Comment by luisAzcuaga** [comment]
Just happened to me now. Didn't see this before (I used 6.12), maybe is related to latest version? What versions are you guys using? @moisesal @Noel-P3 @ManuelMdza13 @Kuseru

**Comment by luisAzcuaga** [comment]
Yup, rolled back to 6.12 and the issue disappeared.

**Comment by Kuseru** [comment]
@luisAzcuaga I am on 6.15

**Comment by tonikelope** [comment]
Hi. The bandwidth error does not stop the download (at least it shouldn't). Just warn that it has occurred and from then on you will use proxys to continue the download.  Anyway, I'm going to remove that warning because it can be confusing. As soon as I have an atoto I will update and also put another optimization of the SmartProxy module.

Regards.

**Comment by ManuelMdza13** [comment]
@luisAzcuaga I have the latest version, that is 6.15

**Comment by ManuelMdza13** [comment]
> Hi. The bandwidth error does not stop the download (at least it shouldn't). Just warn that it has occurred and from then on you will use proxys to continue the download. Anyway, I'm going to remove that warning because it can be confusing. As soon as I have some time I will update and also put another optimization of the SmartProxy module.
> 
> Regards.

OK thank you very much

**Comment by DzArcherXD** [comment]
i have the same error, bandwith limit error and my download is stopped in 15% :( please help
![Sin título](https://user-images.githubusercontent.com/52269408/60234508-7c437480-9872-11e9-8923-d34f0fcb67a4.png)

**Comment by tonikelope** [comment]
https://github.com/tonikelope/megabasterd/releases/tag/v6.16
