### ISSUE TITLE
Cant Open MegaBasterd.jar/MegaBasterd Portable on Win10

### ISSUE THREAD

**Issue by TobiPower20** [tonikelope/megabasterd#646]
Every time I try to start MegaBasterd, only the splash screen comes up and then shuts itself down again. And it doesn't matter which version. and yes, I've already tried reinstalling Java and I've also tried it with Java 11 but it still doesn't work.

can someone please help me?

**Comment by ashes-xda** [comment]
Download OpenJdk from https://adoptium.net/
AND uninstall all other Java versions and install this one i also used to have this issue

**Comment by TobiPower20** [comment]
sorry but that still didn't work. still the same problem

**Comment by TobiPower20** [comment]
I found the problem. Another Java program was running in the background which triggered the conflict. When I closed it, megabasterd ran again
