### ISSUE TITLE
Export to TXT file

### ISSUE THREAD

**Issue by alilife** [tonikelope/megabasterd#66]
Hi.
I'm a huge fan of Megabasterd, it's great.
Can you add an option to export upload result to a text file? when I upload bunch of files it's so hard to copy links one by one, it takes too much time, would be great to add an option to export links+file names to a text file.
and there is this message "Mega file link copied to clipboard" it's really annoying when you're working with large number of files, can you add an option so we can disable it from settings?

THANK YOU SO MUCH ❤️

**Comment by tonikelope** [comment]
Hi! I like the idea.  I will add it in the next update.

Regards.

**Comment by tonikelope** [comment]
https://github.com/tonikelope/megabasterd/releases/tag/v6.17

Log file is stored in home folder. To simplify code changes, the log file name is generated automatically.

I hope it's useful.
