### ISSUE TITLE
I am getting "ERROR checking account quota!" when i try to make a new upload

### ISSUE THREAD

**Issue by kostasafxon** [tonikelope/megabasterd#664]
I click on `File > New upload` and then i select my account but this error appears:

`ERROR checking account quota!`

How can I fix this?

**Comment by kostasafxon** [comment]
It was actually fixed by removing the account and adding it again it probably happend because i copied megabasterd from one computer to another

**Comment by dorukhan1** [comment]
Im getting same problem.

**Comment by kostasafxon** [comment]
> Im getting same problem.

check the solution above
