### ISSUE TITLE
WARNING: File too large

### ISSUE THREAD

**Issue by itswck** [tonikelope/megabasterd#678]
My video download seems to complete, but the assembling of the chunks does not work and I get a message in the terminal saying "WARNING: File too large", printing every second. Any troubleshooting tips?

I commented about this issue [here](https://github.com/tonikelope/megabasterd/issues/436), but no response. Not sure if that's because that issue has been closed, so that's why I'm posting it here. Thanks.

**Comment by tonikelope** [comment]
It may be that the file system where the download is being stored does not support the size of the file you are downloading. Check this.

**Comment by itswck** [comment]
This fixed it. The download location was not where I thought it was. Thank you.
