### ISSUE TITLE
How do I split tunnel megabasterd?

### ISSUE THREAD

**Issue by DogtorDoggo** [tonikelope/megabasterd#692]
I have tried including jre\bin\java.exe, jre\bin\javaw.exe, MegaBasterd.bat, jar\MegaBasterd.jar but none of these allows split tunneling.

**Comment by xCeeTee** [comment]
Split tunnel Javaw.exe itself. Then it's always included.

**Comment by DogtorDoggo** [comment]
> Split tunnel Javaw.exe itself. Then it's always included.

Did you tried that yourself? Last time it wasn't working for me as I stated in op. There is possibility that I did this wrong though.
