### ISSUE TITLE
¿Cómo migrar descargas activas entre versiones de megabasterd?

### ISSUE THREAD

**Issue by arxzel** [tonikelope/megabasterd#70]
Comencé una descarga que pesa aproximadamente 30 gb, llevo unos 7 gb descargados, quisiera saber como puedo continuar la descarga al cambiar la versión de megabasterd por la release.

Ya que al abrir la release esta no carga las descargas activas en una versión anterior.

**Comment by tonikelope** [comment]
Hola. Las descargas/subidas activas y demás datos están en el fichero
megabasterd.db dentro de la carpeta .megabasterdxxx en tu carpeta home o en
Windows la carpeta de usuario. Con MegaBasterd cerrado copia el fichero
antiguo y pegarlo sobreescribiendo el nuevo. Después al arrancar la última
versión de MegaBasterd deberías tener todo como en la anterior.

Salu2 ;)

**Comment by arxzel** [comment]
Ufff, excelente, muchas gracias.
