### ISSUE TITLE
Priority system

### ISSUE THREAD

**Issue by Pival81** [tonikelope/megabasterd#71]
I noticed that the program doesn't list all the files in a folder in the correct alphabetical order, a solution could be to fix the order of the files, or maybe add a priority system, which solves a more important problem:
What if I want to download the last (or the middle one, whatever I need in that moment) file first?

**Comment by tonikelope** [comment]
> I noticed that the program doesn't list all the files in a folder in the correct alphabetical order, a solution could be to fix the order of the files, or maybe add a priority system, which solves a more important problem:
> What if I want to download the last (or the middle one, whatever I need in that moment) file first?

I've modified the code to sort the file tree automatically.

I'll study the issue of priority queues (I don't have much time right now).

Greetings.

https://github.com/tonikelope/megabasterd/releases/tag/v6.22
