### ISSUE TITLE
Can't upload big files (over 2GB)

### ISSUE THREAD

**Issue by pilaco** [tonikelope/megabasterd#72]
I'm having trouble uploading files over 2GB
![Captura de tela_2019-07-08_19-05-21-edit001](https://user-images.githubusercontent.com/22872431/60846050-96574e00-a1b4-11e9-9894-be3aa7e6483d.png)

Command typed in terminal:
`$ java -jar MegaBasterd_6.22.jar 
jul 08, 2019 7:16:52 PM com.tonikelope.megabasterd.SmartMegaProxyManager refreshProxyList
INFORMAÇÕES: pool-1-thread-10 Smart Proxy Manager: proxy list refreshed (920)
jul 08, 2019 7:17:01 PM com.tonikelope.megabasterd.MiscTools checkMegaAccountLoginAndShowMasterPassDialog
INFORMAÇÕES: Reutilizando sesión de MEGA guardada para mymail@mail.com
jul 08, 2019 7:17:06 PM com.tonikelope.megabasterd.MiscTools checkMegaAccountLoginAndShowMasterPassDialog
INFORMAÇÕES: Reutilizando sesión de MEGA guardada para mymail@mail.com
`

**Comment by tonikelope** [comment]
Wow, that's weird! I'm not able to reproduce the problem. What operating system do you use? Do you get any file larger than 2GB? If you move the file to C:\ and give it an alphanumeric name, it keeps happening? 
![Screenshot_20190709_151939](https://user-images.githubusercontent.com/1344008/60891438-9d866680-a25d-11e9-8de4-06a35d0cf37e.png)

**Comment by pilaco** [comment]
I have already uploaded files over 10gb in other accounts. Maybe the problem is this account. I'll create a new account and try to upload.

![Captura de tela_2019-07-09_14-18-53-edit](https://user-images.githubusercontent.com/22872431/60910118-5183f380-a256-11e9-8273-dab74f05fdab.png)

Operating system: **Arch Linux**
Linux Kernel: **5.1.15**
`$ java --version
openjdk 12.0.1 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK Server VM (build 12.0.1+12, mixed mode)`

**Comment by tonikelope** [comment]
I'm glad you're up and running. I also use ArchLinux with OpenJDK 1.8 and I didn't have problems as I told you.  But I'm going to check that piece of code to see what might be going on. Thanks for the testing. 

PS: if you need to use Java 12, you can download the version of MegaBasterd AppImage that has Java 1.8 inside.
