### ISSUE TITLE
Changing default download directory

### ISSUE THREAD

**Issue by photosheikh** [tonikelope/megabasterd#73]
Hi, 

I just started using megabasterd and it works really well.

My only issues is that I cannot change the default download directory to an external hard disk. It only lets me use the internal hard drive where the Mac OS is located. 

Is there any way to tell the settings to download to an external hard disk???

I am using a Mac by the way.

Any help is appreciated.

Thanks you.

**Comment by tonikelope** [comment]
Hi, I don't use a Mac but I think the external mounted volumes are in the /Volumes path (It's not like in Windows that different "units" appear).

Let's see if we're lucky.

Regards.

**Comment by photosheikh** [comment]
Hi, thanks for getting back to me so quickly. It doesn't look like I can select external volumes on my Mac. It's ok, I can manage with about 40gb space free. Thanks for your time with this great app.
