### ISSUE TITLE
Feature Request: Change Download Order

### ISSUE THREAD

**Issue by bannisdale** [tonikelope/megabasterd#74]
I might have missed it, but from what I can see, there is no (simple) way to order downloads once they're added. Drag-and-drop, "move up/down", entering new queue numbers, ... would all work for me.

Thanks! :)

**Comment by DFNCTSC** [comment]
+1

This would be very useful when a download errors/fails and when you retry the download it goes to the very bottom of the queue instead of at the top.

**Comment by tonikelope** [comment]
https://github.com/tonikelope/megabasterd/releases/tag/v6.25
