### ISSUE TITLE
Problemas a la hora de descargas

### ISSUE THREAD

**Issue by santiagomadeo** [tonikelope/megabasterd#78]
Actualmente estoy descargando una serie, la cuales cada capitulos pesaran entre 150 a 300 mb. el problema es que arranca bien y luego se dejan de descargar por un tiempo. la descarga se queda en - - - - - - luego retoma hasta 300kb/s cuando deberia descargar a 5,00 MB/s yo cuento con 100 megas de ancho de banda. y estoy conectado con cable ethernet. al principio descargue algunos archivos y los descargo a esa velocidad. pero ahora deje toda la madrugada descargando los videos  solo descargo 4,41gb en mas de 10hs. 
Tambien debajo de donde dice "Slots" me salen error:1 y van subiendo y bajando hasta el 10 masomenos.

**Comment by tonikelope** [comment]
Hola. Cuando salta el límite de descarga de MEGA se activan los proxys de forma automática, pero el problema que tienen los proxys es que su velocidad es muy variable y depende del número de personas usándolos entre otras cosas. He modificado el código para intentar optimizar un poco la descarga y que ignore los proxys en cuanto el límite de MEGA se desactive (por si lo dejas descargando de noche).
