### ISSUE TITLE
Feature request: Paused downloads at startup

### ISSUE THREAD

**Issue by cRazEYgUy** [tonikelope/megabasterd#79]
Love this program! Thank you very much for your hard work.

I know there is an button for 'Pause All', but it would be nice to have an option in the settings that lets the user decide whether to start transfers immediately or wait for user input.

As an example, sometime I want to launch the program and just add items into the queue but not have it download immediately - this scenario would be a great use of this feature.

Another idea would be to allow at least 10 seconds before downloads begin so that the user can manually use the 'Pause All' button to disable transfers temporarily.

**Comment by tonikelope** [comment]
https://github.com/tonikelope/megabasterd/releases/tag/v6.25

**Comment by cRazEYgUy** [comment]
Thank you so much for all your hard work!!
