### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by shiroukamui** [tonikelope/megabasterd#8]
Hi, thanks very much for this excellent app.
I don't know which are the correct libraries to compile this app, exactly in the CrypTools.java file at the import org.codehaus.jackson.map.ObjectMapper. I tryed with https://mvnrepository.com/artifact/org.codehaus.jackson/jackson-mapper-asl/1.9.13  but doesn't work.
Could you share those libraries or their URLs for find them please?
Thanks in advance.

**Comment by tonikelope** [comment]
I have shared a zip with all the libs that MegaBasterd uses.

Regards.
