### ISSUE TITLE
Sugerencia: Guardar configuración localmente

### ISSUE THREAD

**Issue by MariioCL** [tonikelope/megabasterd#83]
¿Es posible guardar la configuración del programa localmente en el PC? Cada vez que actualizo el programa tengo que volver a configurar todo nuevamente, quizás podrías crear un archivo en appdata o algo así.

Gracias!

**Comment by tonikelope** [comment]
Hola. El archivo de configuración de MegaBasterd se guarda en la carpeta
del usuario o el HOME en Linux. Las carpetas se llaman .megabasterdxxx y
dentor hay un archivo llamado megabasterd.db Copia y pega ese archivo desde
una versión anterior en la carpeta de la versión nueva y tendrás todos tus
ajustes.

Si tengo un rato, automatizaré esto.

Salu2 ;)
