### ISSUE TITLE
Can't completely delete MegaBasterd from PC

### ISSUE THREAD

**Issue by GutHib1209** [tonikelope/megabasterd#85]
Hello. I can't completely get rid of MegaBasterd from my PC so I can download a different version. I was running 6.19 when I encountered an error that kept maxing the slots on an active download to 20 and thus having the file not download. I tried deleting it and using 6.24 but still ran into the same issue.

**Comment by Abhay-Pratap-SINGH28** [comment]
Hello can anyone fix the issue of uninstalling megabasterd so that I can update it
