### ISSUE TITLE
download queue lost?

### ISSUE THREAD

**Issue by Souluzumaki** [tonikelope/megabasterd#86]
i just opened the app and all the downloads are missing (unfinished downloads or downloads that didn't start yet)
is there a way to recover the urls?

i'm sorry about my bad grammar, english is not my native language.

**Comment by tonikelope** [comment]
Hello, the MegaBasterd configuration file is saved in the user carpet or HOME on Linux. The folders are called .megabasterdxxx and inside there is a file called megabasterd.db Copy and paste that file from a previous version into the new version folder and you will have all your old settings and transfers.

Regards.

**Comment by sagebeme** [comment]
What about on windows?
