### ISSUE TITLE
Downloads start with fast speed then dies down after 20 seconds or so.

### ISSUE THREAD

**Issue by bnichs5** [tonikelope/megabasterd#88]
As title says. Downloads start between 40-60mbps then drops to between 250kbps-1mbps after roughly 20 seconds. Doesnt matter how many downloads are running simultaneously, it happens whether its only 1 or if it is up to 20. Doesnt change if I start a new download either. I know its not my network also cause I can download from google drive just fine at 60mbps.

Great program BTW.  This is running on 6.22 and has been happening on other versions as well. I think I tried 6.18   6.16  6.14 and 6.12

**Comment by tonikelope** [comment]
The speed drop occurs when the daily MEGA discharge limit is reached and the proxies come into operation, whose discha rge speed is highly variable and dependent on various factors outside of MegaBasterd, i'm sorry.

Regards,
