### ISSUE TITLE
Problems with systray in linux (gnome shell desktop)

### ISSUE THREAD

**Issue by MakuSensei** [tonikelope/megabasterd#9]
Hi, I want to report a bug in the systray icon, it is black and can not be minimized, it also hangs if I close it, it also stays in the taskbar another window called "JavaEnbeddedFrame"

![image](https://user-images.githubusercontent.com/16900914/26983831-7bd46eca-4d13-11e7-928d-967f7b5808ee.png)

![captura de pantalla de 2017-06-09 13-00-13](https://user-images.githubusercontent.com/16900914/26983960-e0c7d006-4d13-11e7-886e-6de04e985db2.png)

**Comment by tonikelope** [comment]
I'll fix it asap.

Thanks.

**Comment by MakuSensei** [comment]
Thank
