### ISSUE TITLE
[Sugerencia] Que la configuración de Megabasterd se guarde en la misma carpeta

### ISSUE THREAD

**Issue by DrW3b** [tonikelope/megabasterd#95]
Antes era así, no entiendo por qué se cambió, lo hace menos portable, va dejando rastro en cada PC donde se usa y es menos seguro. 

Creo que por defecto se debería guardar en la misma carpeta y añadir alguna opcion en la configuración del programa que permita activar la opción de "Guardar los ajustes en este pc"

**Comment by tonikelope** [comment]
Hola. Lo cambié cuando añadí en las releases el formato appimage que necesita que la ruta donde se guarda la configuración esté fuera del directorio de la aplicación (además de que es lo "estándar"). Tampoco se puede poner como opción la ruta del fichero de configuración (es lo único que tiene que ser fijo). 

Si te preocupa la seguridad, activa el cifrado de las cuentas.

Salu2 ;)
