### ISSUE TITLE
Subidas - Error de nombre

### ISSUE THREAD

**Issue by luisr1vas** [tonikelope/megabasterd#97]
Cuando se suben cientos archivos, hay veces que se completa la subida, más sin embargo tanto en megaCMD sale el nombre del archivo "BLANK" y en la version web Sale el nombre del archivo pero al final codificado (por ende no se puede deducir con facilidad cual es cual), ejemplo:

![image](https://user-images.githubusercontent.com/38728192/63191032-2d71ba00-c02d-11e9-9f8f-e10d8a725e3e.png)

Y en megaCMD sale así:

![image](https://user-images.githubusercontent.com/38728192/63191056-3ebac680-c02d-11e9-9dec-4889ccc24117.png)

**Comment by tonikelope** [comment]
¿Puedes ponerme por aquí el nombre exacto de alguno de esos archivos? A ver
si puedo replicar el error que tienes. ¿Usas Windows?

Gracias.

**Comment by luisr1vas** [comment]
Me di cuenta que hay problema con algunos caracteres especiales, por ejemplo los archivos contenían acento: "Rebelde - Capítulo xxx..." Quite el "Capítulo"  volví a subir y todo perfectamente. Hay un problema con los unicode, Y si uso Windows/Ubuntu más veces Windows.

**Comment by tonikelope** [comment]
Lo revisaré. Gracias por avisar.

**Comment by tonikelope** [comment]
¿Si borras el nombre original del fichero y lo vuelves a escribir igual sigue pasando? Acabo de probar a subir un fichero llamado "Capítulo.txt" en ArchLinux y se sube correctamente (comprobado desde la web de MEGA). 

Salu2 ;)

**Comment by luisr1vas** [comment]
Probé subiendo la carpeta que contenia otras carpetas y entre ellas estaba "Pequeños Sabuesos (2019)"  y fue el mismo inconvetiene con esta carpeta, una vez terminada la subida quedo en "BLANK" y desde la web salia MALFORMED_ATTRIBUTES.

Te dejo unos screenshots:

![image](https://user-images.githubusercontent.com/38728192/63214834-1b525300-c0e3-11e9-9246-e2019a5ad1eb.png)

![image](https://user-images.githubusercontent.com/38728192/63214838-20af9d80-c0e3-11e9-9505-644cd4192f0d.png)

![image](https://user-images.githubusercontent.com/38728192/63214839-23aa8e00-c0e3-11e9-8955-de524fdce47a.png)

**Comment by tonikelope** [comment]
Hola. ¿Puedes probar desde Ubuntu?

Salu2 ;)

**Comment by luisr1vas** [comment]
Estoy probando aquí en Ubuntu y todo marcha bien, no hay inconveniente con el nombre. Entonces solo ocurre en Windows.

**Comment by tonikelope** [comment]
¿Puedes probar a ejecutar así:?

`java -Dfile.encoding=UTF-8 -jar MegaBasterd_6.29.jar`

**Comment by rocknard** [comment]
Siento meterme, pero a mí también me pasó cuando hice un backup de mis archivos, me los subió prácticamente todos mal con lo del "atributte malformed". Se ve que la aplicación no reconoce esos caracteres y termina poniéndotelos como BLANK (windows xp).

**Comment by tonikelope** [comment]
Creo que es un problema de algunas versiones de Java en Windows, pero no sé la causa exacta, lo siento. Si alguien puede aportar más datos, podrían ser de ayuda.

**Comment by Mitt9** [comment]
A mi también me ocurre cuando descargo. Si descargo un archivo que contenga acentos, me lo transforma en lo siguiente:
 ![image](https://i.imgur.com/JA0Z55y.png)

Debería poner Piñata.

Es lo que dijeron arriba, el programa java copia el texto del archivo pero no es capaz de leer acentos ni la Ñ.

**Comment by Mitt9** [comment]
> ¿Puedes probar a ejecutar así:?
> 
> `java -Dfile.encoding=UTF-8 -jar MegaBasterd_6.29.jar`

Funciona, pero es un poco incómodo ejecutar ese código todo el rato, ¿No hay alguna forma más cómoda como por ejemplo usando un acceso directo?

Este artículo podría ayudar, no sé: https://es.switch-case.com/50818653

**Comment by tonikelope** [comment]
A ver si hay suerte con la última versión: 

https://github.com/tonikelope/megabasterd/releases/tag/v6.33

Nota: probad el .jar y el .exe por separado.

**Comment by Mitt9** [comment]
Pues con la nueva versión 6.33 parece funcionar bien. Por lo menos en descarga, en subidas no lo he probado.
