### ISSUE TITLE
Not Able To Download File Inside A Folder 

### ISSUE THREAD

**Issue by DJboutit** [tonikelope/megabasterd#98]
When someone creates a folder and your trying to download a file inside the folder or the whole folder I get a mega link error please fix this.

**Comment by tonikelope** [comment]
Please paste here some example link.

Regards.

**Comment by DJboutit** [comment]
#F!MbgX3SRQ!u3xq1MyKMAToJKxilfsMzg?wG5VnSyK

**Comment by tonikelope** [comment]
To be able to download a certain file (or files) inside a folder, you have to put the link to the folder (https://mega.nz/#F!MbgX3SRQ!u3xq1MyKMAToJKxilfsMzg) in MegaBasterd and select the files you want to download from the folder inside MegaBasterd.

Regards.
