### ISSUE TITLE
Se detiene la descarga cierro y abro el programa y no comienza la descarga, como restauro la configuracion

### ISSUE THREAD

**Issue by Valerygov** [tonikelope/megabasterd#99]
Hola estimado Creador de MegaBasterd descargue la version .jar al colocar el fichero de Mega a descarga comienza la descarga pero cuando lleva cierto porcentaje se detiene y debajo de la palabra Slots dice error 1,2, 3,7,4 etc. y no vuelve a comenzar la descarga, entonces procedo a cerrar el programa mediante el administrador de tareas y nuevamente inicio el programa y nada la descarga nunca mas empieza, que hago? Que puede estar sucediendo?

Por otra parte, te quiero preguntar como reinicia la configuracion del programa ya que en "Avanzado" presiono restaurar ajustes por defecto y nada sucede la carpeta de descarga sigue siendo la misma etc. etc. Como Restauro la configuracion por defecto? Debo borrar alguna entrada registro? 

Saludos y un gran abrazo! Gracias por tu gran aporte!

**Comment by tonikelope** [comment]
Hola. Cuando aparecen errores de slots es porque alǵún proxy falla, pero automáticamente se elige otro. Lo de que no empiece la descarga podría deberse a que los proxys están muy saturados en ese momento. ¿Puedes ponerme aqui el link que intentas descargar?

He corregido una cosa que no estaba bien el botón de restaurar ajustes. ya debería funcionar.

Salu2 ;)

**Comment by Valerygov** [comment]
Hola estimado creador ya baje la ultima version y se soluciono el tema de la restauracion de los ajustes pero el tema de los proxys sigue sucediendo, estuve evaluando el comportamiento del programa en mi pc y me di cuento que el problema ocurre cuando se llega al limite de descarga impuesto por Mega, el programa comienza a descarga perfecto y cuando llega al limite "no puede saltarlo"  probe el programa a diferentes horas del dia y nada:( puedes revisar si los proxys para ver si estan trabajando bien? tambien me gustaria darte una sugerencia pudieras agregar un boton que permita cambiar de proxy manualmente? osea que existan las dos formas cambio de proxy "automatico y manual" 

![Gif del Problema](https://user-images.githubusercontent.com/54224032/63311800-4e583a80-c2cd-11e9-8dc5-241becda8107.gif)

Saludos un gran abrazo! y Muchas gracias por tu gran Aporte!
